---
# Implements
# https://github.com/quay/quay-operator#step-by-step
- name: "Prepare Quay Registry"
  block:
    - name: "set_fact jannah_stages_bootstrap_deploy_destination"
      ansible.builtin.set_fact:
        jannah_stages_bootstrap_deploy_destination: "{{ Jannah.stages.bootstrap.deploy.destination }}"
      tags:
        - "deploy_storage"
        - "molecule_prepare"
        - "operator_e2e"
        - "debug_task"
    - name: "set_fact jannah_stages_bootstrap_deploy_wait_time"
      ansible.builtin.set_fact:
        jannah_stages_bootstrap_deploy_wait_time: "{{ Jannah.stages.bootstrap.deploy.wait_time }}"
      tags:
        - "deploy_images"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "Create quay-operator download directory"
      file:
        path: "${MOLECULE_EPHEMERAL_DIRECTORY}/{{ Jannah.stages.bootstrap.deploy.dependencies.quay.namespace }}"
        state: directory
        mode: 0755
      tags:
        - "deploy_images"
        - "molecule_prepare"
        - "operator_e2e" 
    - name: "Read-write git checkout Quay repository"
      ansible.builtin.git:
        repo:  "{{ Jannah.stages.bootstrap.deploy.dependencies.quay.github.repo }}"
        dest: "${MOLECULE_EPHEMERAL_DIRECTORY}/{{ Jannah.stages.bootstrap.deploy.dependencies.quay.namespace }}"
      tags:
        - "deploy_images"
        - "molecule_prepare"
        - "operator_e2e" 
    - name: "Deploy Quay Operator - Create the CatalogSource - kind cluster"
      environment:
        KUBECONFIG: "${MOLECULE_EPHEMERAL_DIRECTORY}/kind/config"
      shell: |
        kubectl create \
        -n "{{ Jannah.stages.bootstrap.deploy.helm_values.common.namespace }}" \
        -f ./bundle/quay-operator.catalogsource.yaml;
      when: (
              ansible_facts['os_family'] == "Darwin"
              and
              jannah_stages_bootstrap_deploy_destination == "kind"
            )
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/{{ Jannah.stages.bootstrap.deploy.dependencies.quay.namespace }}"
      tags:
        - "deploy_images"
        - "molecule_prepare"
        - "operator_e2e" 
    - name: "Deploy Quay Operator - Create the CatalogSource - docker-desktop cluster"
      shell: |
        kubectl create \
        -n "{{ Jannah.stages.bootstrap.deploy.helm_values.common.namespace }}" \
        -f ./bundle/quay-operator.catalogsource.yaml;
      when: (
              ansible_facts['os_family'] == "Darwin"
              and
              jannah_stages_bootstrap_deploy_destination == "docker-desktop"
            )
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/{{ Jannah.stages.bootstrap.deploy.dependencies.quay.namespace }}"
      tags:
        - "deploy_images"
        - "molecule_prepare"
        - "operator_e2e" 
    - name: "Wait for Deploy Quay Operator - Create the CatalogSource"
      shell: |
        sleep {{ Jannah.stages.bootstrap.deploy.wait_time }};
      when: jannah_stages_bootstrap_deploy_wait_time > 0
      tags:
        - "deploy_images"
        - "molecule_prepare"
        - "operator_e2e" 
    - name: "Deploy Quay Operator - kubectl get packagemanifest grep qrep - docker-desktop"
      shell: |
        kubectl get packagemanifest --all-namespaces | grep quay;
      register: kubectl_get_packagemanifest_results
      when: (
              ansible_facts['os_family'] == "Darwin"
              and
              jannah_stages_bootstrap_deploy_destination == "docker-desktop"
            )
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/{{ Jannah.stages.bootstrap.deploy.dependencies.quay.namespace }}"
      tags:
        - "deploy_images"
        - "molecule_prepare"
        - "operator_e2e" 
    - name: "Deploy Quay Operator - kubectl get packagemanifest grep qrep - kind cluster"
      environment:
        KUBECONFIG: "${MOLECULE_EPHEMERAL_DIRECTORY}/kind/config"
      shell: |
        kubectl get packagemanifest --all-namespaces | grep quay;
      register: kubectl_get_packagemanifest_results
      when: (
              ansible_facts['os_family'] == "Darwin"
              and
              jannah_stages_bootstrap_deploy_destination == "kind"
            )
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/{{ Jannah.stages.bootstrap.deploy.dependencies.quay.namespace }}"
      tags:
        - "deploy_images"
        - "molecule_prepare"
        - "operator_e2e"
    - debug: var=kubectl_get_packagemanifest_results
    - assert:
        that:
          - kubectl_get_packagemanifest_results.contains("quay")
    - name: "Deploy Quay Operator - Create the OperatorGroup - docker-desktop"
      shell: |
        kubectl create \
        -n "{{ Jannah.stages.bootstrap.deploy.helm_values.common.namespace }}" \
        -f ./bundle/quay-operator.operatorgroup.yaml;
      when: (
        ansible_facts['os_family'] == "Darwin"
        and
        jannah_stages_bootstrap_deploy_destination == "docker-desktop"
       )
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/quay_operator"
      tags:
        - "deploy_images"
        - "molecule_prepare"
        - "operator_e2e" 
    - name: "Deploy Quay Operator - Create the OperatorGroup - kind cluster"
      environment:
        KUBECONFIG: "${MOLECULE_EPHEMERAL_DIRECTORY}/kind/config"
      shell: |
        kubectl create \
        -n "{{ Jannah.stages.bootstrap.deploy.helm_values.common.namespace }}" \
        -f ./bundle/quay-operator.operatorgroup.yaml;
      when: (
        ansible_facts['os_family'] == "Darwin"
        and
        jannah_stages_bootstrap_deploy_destination == "docker-desktop"
       )
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/quay_operator"
      tags:
        - "deploy_images"
        - "molecule_prepare"
        - "operator_e2e" 
    - name: "Deploy Quay Operator - Create the OperatorGroup Subscription - kind cluster"
      environment:
        KUBECONFIG: "${MOLECULE_EPHEMERAL_DIRECTORY}/kind/config"
      shell: |
        kubectl create \
        -n "{{ Jannah.stages.bootstrap.deploy.helm_values.common.namespace }}" \ 
        -f ./bundle/quay-operator.subscription.yaml;
      when: (
        ansible_facts['os_family'] == "Darwin"
        and
        jannah_stages_bootstrap_deploy_destination == "kind"
       )
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/quay_operator"
      tags:
        - "deploy_images"
        - "molecule_prepare"
        - "operator_e2e" 
    - name: "Deploy Quay Operator - Create the OperatorGroup Subscription - docker-desktop"
      shell: |
        kubectl create \
        -n "{{ Jannah.stages.bootstrap.deploy.helm_values.common.namespace }}" \ 
        -f ./bundle/quay-operator.subscription.yaml;
      when: (
              ansible_facts['os_family'] == "Darwin"
              and
              jannah_stages_bootstrap_deploy_destination == "docker-desktop"
            )
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/quay_operator"
      tags:
        - "deploy_images"
        - "molecule_prepare"
        - "operator_e2e" 
  rescue:
    - name: "Deploy Operators Storage to MacOs Docker Desktop Exception"
      ansible.builtin.debug:
        msg: 'Deploy Operators Storage to MacOs Docker Desktop Exception'
      tags:
        - "deploy_images"
        - "molecule_prepare"
        - "operator_e2e" 
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "deploy_images"
        - "molecule_prepare"
        - "operator_e2e" 
  ignore_errors: false
