---
- name: "documentation/blog/jannah-operator/posts"
  block:
    - name: "Generate blog/jannah-operator/_posts/2023-01-23-Introducing-Jannah-Operator.markdown"
      template:
        src: "files/template/2023-01-23/2023-01-23-Introducing-Jannah-Operator.markdown"
        dest: "../roles/requirements/tasks/documentations/blog/jannah-operator/_posts/2023-01-23-Introducing-Jannah-Operator.markdown"
        backup: yes
      tags:
        - "blog-service-install"
        - "generate-blog-posts"
        - "operator"
  rescue:
    - name: "documentation/blog/jannah-operator/posts exception"
      ansible.builtin.debug:
        msg: 'documentation/blog/jannah-operator/posts exception'
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
  #become: true
  ignore_errors: false
