---
# ('os_family' not in ansible_facts) or  (ansible_facts['os_family'] == "Darwin")
- name: "Deploy Jannah"
  block:
    - name: "Import multipass (Ubuntu on Darwin) build infra tasks"
      include_tasks: '{{ item }}'
      with_fileglob:
        - tasks/create/multipass/exec.yml
      when: ansible_facts['os_family'] == "Darwin"
      tags:
        - "multipass_infra"
        - "molecule_create"
        - "operator_e2e"
    - name: "Import Ubuntu inline infra tasks"
      include_tasks: '{{ item }}'
      with_fileglob:
        - tasks/create/multipass/inline.yml
      when: (ansible_facts['os_family'] == "Ubuntu") or (ansible_facts['os_family'] == "Darwin" and ansible_facts['architecture'] == "arm64")
      tags:
        - "multipass_infra"
        - "molecule_create"
        - "operator_e2e"
  rescue:
    - name: "Deploy Jannah Exception"
      ansible.builtin.debug:
        msg: 'Deploy Jannah Exception'
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
  ignore_errors: false
