---
- name: "documentation/blog/jannah-operator/[pages]"
  block:
    - name: "Generate blog/jannah-operator/boot.markdown"
      template:
        src: "files/template/boot/boot.markdown"
        dest: "../roles/requirements/tasks/documentations/blog/jannah-operator/boot.markdown"
        backup: yes
      tags:
        - "blog-service-install"
        - "generate-blog-pages"
        - "operator"
    - name: "Generate blog/jannah-operator/network.markdown"
      template:
        src: "files/template/network/network.markdown"
        dest: "../roles/requirements/tasks/documentations/blog/jannah-operator/network.markdown"
        backup: yes
      tags:
        - "blog-service-install"
        - "generate-blog-pages"
        - "operator"
    - name: "Generate blog/jannah-operator/storage.markdown"
      template:
        src: "files/template/storage/storage.markdown"
        dest: "../roles/requirements/tasks/documentations/blog/jannah-operator/storage.markdown"
        backup: yes
      tags:
        - "blog-service-install"
        - "generate-blog-pages"
        - "operator"
    - name: "Generate blog/jannah-operator/compute.markdown"
      template:
        src: "files/template/compute/compute.markdown"
        dest: "../roles/requirements/tasks/documentations/blog/jannah-operator/compute.markdown"
        backup: yes
      tags:
        - "blog-service-install"
        - "generate-blog-pages"
        - "operator"
    - name: "Generate blog/jannah-operator/ux.markdown"
      template:
        src: "files/template/ux/ux.markdown"
        dest: "../roles/requirements/tasks/documentations/blog/jannah-operator/ux.markdown"
        backup: yes
      tags:
        - "blog-service-install"
        - "generate-blog-pages"
        - "operator"
    - name: "Generate blog/jannah-operator/feed-back.markdown"
      template:
        src: "files/template/feedback/feed-back.markdown"
        dest: "../roles/requirements/tasks/documentations/blog/jannah-operator/feed-back.markdown"
        backup: yes
      tags:
        - "blog-service-install"
        - "generate-blog-pages"
        - "operator"
    - name: "Generate blog/jannah-operator/index.markdown"
      template:
        src: "files/template/index/index.markdown"
        dest: "../roles/requirements/tasks/documentations/blog/jannah-operator/index.markdown"
        backup: yes
      tags:
        - "blog-service-install"
        - "generate-blog-pages"
        - "operator"
  rescue:
    - name: "documentation/blog/jannah-operator/posts exception"
      ansible.builtin.debug:
        msg: 'documentation/blog/jannah-operator/posts exception'
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
  #become: true
  ignore_errors: false
