---
- name: Cleanup
  hosts: localhost
  connection: local
  gather_facts: true
  collections:
    - kubernetes.core
  tasks:
    - block:
        - name: Import all tasks/cleanup by order
          include_tasks: '{{ cleanup_task_item }}'
          with_fileglob:
            - tasks/cleanup/main.yml
          loop_control:
            loop_var: cleanup_task_item
          tags:
            - "molecule_cleanup"
            - "operator_e2e"
            - "molecule_cleanup_pipeline_images"
      rescue:
        - name: Re-emit failure
          vars:
            failed_task:
              result: '{{ ansible_failed_result }}'
          fail:
            msg: '{{ failed_task }}'
          tags:
            - "molecule_cleanup"
            - "operator_e2e"
            - "molecule_cleanup_pipeline_images"
      ignore_errors: false

