---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: true
  tasks:
    - name: "Import dependency and jannah and deployment tasks"
      include_tasks: '{{ converge_task_item }}'
      with_fileglob:
        - tasks/converge/main.yml
      loop_control:
        loop_var: converge_task_item
      tags:
        - "deploy_dependencies"
        - "molecule_converge"
        - "deploy_jannah"
        - "operator_e2e"
        - "debug_task"
        - "molecule_converge_debug"

