---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: true
  tasks:
    - name: "Molecule create tasks"
      block:
        - name: "Import cluster create tasks"
          include_tasks: '{{ create_task_item }}'
          with_fileglob:
            - tasks/create/main.yml
          loop_control:
            loop_var: create_task_item
          tags:
            - "molecule_create"
            - "operator_e2e"
            - "debug_task"
            - "molecule_create_debug"
      rescue:
        - name: "Molecule create tasks exception is thrown"
          ansible.builtin.debug:
            msg: 'Molecule create tasks exception is thrown'

        - name: Re-emit failure
          vars:
            failed_task:
              result: '{{ ansible_failed_result }}'
          fail:
            msg: '{{ failed_task }}'
