---
- name: "Builds streamos frontend docker images for use in Helm Chart"
  block:
    - name: "Create /images/streamos/frontend directory"
      file:
        path: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/streamos/frontend"
        state: directory
        mode: 0755
      tags:
        - "build_images"
        - "build_frontend_images"
        - "molecule_prepare"
        - "operator_e2e"
        - "dev_debug"
    - name: "Git checkout https://github.com/jannahio/frontend.git for streamos"
      ansible.builtin.git:
        repo: "https://github.com/jannahio/frontend.git"
        dest: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/streamos/frontend"
        version: "task-kSPivE2w-jannah-vue-js.loginlogout.ionic.ui"
      tags:
        - "build_images"
        - "build_frontend_images"
        - "molecule_prepare"
        - "operator_e2e"
        - "dev_debug"
#   https://www.apollographql.com/docs/ios/tutorial/codegen-getting-started
    - name: "Download iOS Apollo CLI"
      shell: |
        wget  \
        https://github.com/apollographql/apollo-ios/releases/download/1.3.0/apollo-ios-cli.tar.gz;
        tar -xvf apollo-ios-cli.tar.gz;
      async: 600
      poll: 5
#      when: ansible_facts['os_family'] == "Darwin" and ansible_facts['architecture'] == "x86_64"
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/streamos/frontend/ios"
      tags:
        - "build_images"
        - "build_frontend_images"
        - "molecule_prepare"
        - "operator_e2e"
        - "dev_debug"
    - name: "Generate frontend/streamos.frontend.Dockerfile"
      template:
        src: "files/templates/streamos/frontend/streamos.frontend.Dockerfile"
        dest: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/streamos/frontend/web/JannahIonic/streamos.frontend.Dockerfile"
      tags:
        - "build_images"
        - "build_frontend_images"
        - "molecule_prepare"
        - "operator_e2e"
        - "dev_debug"
    - name: "Generate streamos/streamos.frontend.Dockerfile.dockerignore"
      template:
        src: "files/templates/streamos/frontend/streamos.frontend.Dockerfile.dockerignore"
        dest: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/streamos/frontend/web/JannahIonic/streamos.frontend.Dockerfile.dockerignore"
      tags:
        - "build_images"
        - "build_frontend_images"
        - "molecule_prepare"
        - "operator_e2e"
        - "dev_debug"
    - name: "Build StreamOs frontend image - jallohmediabuild/jannah-streamos-frontend-web-arm64"
      shell: |
        docker buildx build \
          --builder=kube \
          -t jallohmediabuild/jannah-streamos-frontend-web-arm64:v0.0.1 \
          --platform=linux/arm64 \
          -f streamos.frontend.Dockerfile \
          --load .
      when: ansible_facts['architecture'] != "x86_64"
      async: 1200
      poll: 5
#      when: ansible_facts['os_family'] == "Darwin" and ansible_facts['architecture'] != "x86_64"
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/streamos/frontend/web/JannahIonic/"
      tags:
        - "build_images"
        - "build_frontend_images"
        - "molecule_prepare"
        - "operator_e2e"
        - "dev_debug"
    - name: "Build StreamOs frontend image - jallohmediabuild/jannah-streamos-frontend-web-amd64"
      shell: |
        docker buildx build \
          --builder=kube \
          -t jallohmediabuild/jannah-streamos-frontend-web-amd64:v0.0.1 \
          --platform=linux/amd64 \
          -f streamos.frontend.Dockerfile \
          --load .
      when: ansible_facts['architecture'] == "x86_64"
      async: 1200
      poll: 5
#      when: ansible_facts['os_family'] == "Darwin" and ansible_facts['architecture'] != "x86_64"
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/streamos/frontend/web/JannahIonic/"
      tags:
        - "build_images"
        - "build_frontend_images"
        - "molecule_prepare"
        - "operator_e2e"
        - "dev_debug"
  rescue:
    - name: "Builds StreamOs Frontend Docker Images Exception"
      ansible.builtin.debug:
        msg: 'Builds StreamOs Frontend Docker Images Exception'
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "build_images"
        - "build_frontend_images"
        - "build_streamos_images"
        - "molecule_prepare"
        - "operator_e2e"
  ignore_errors: false
