---
- name: "Builds ubuntu frontend docker images for use in Helm Chart"
  block:
    - name: "Create /images/ubuntu/frontend directory"
      file:
        path: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/ubuntu/frontend"
        state: directory
        mode: 0755
      tags:
        - "build_images"
        - "build_frontend_images"
        - "molecule_prepare"
        - "operator_e2e"
        - "dev_debug"
    - name: "Git checkout https://github.com/jannahio/frontend.git"
      ansible.builtin.git:
        repo: "https://github.com/jannahio/frontend.git"
        dest: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/ubuntu/frontend"
        version: "task-kSPivE2w-jannah-vue-js.loginlogout.ionic.ui"
      tags:
        - "build_images"
        - "build_frontend_images"
        - "molecule_prepare"
        - "operator_e2e"
        - "dev_debug"
    #   https://www.apollographql.com/docs/ios/tutorial/codegen-getting-started
    - name: "Download iOS Apollo CLI"
      shell: |
        wget  \
        https://github.com/apollographql/apollo-ios/releases/download/1.3.0/apollo-ios-cli.tar.gz;
        tar -xvf apollo-ios-cli.tar.gz;
      async: 600
      poll: 5
      #      when: ansible_facts['os_family'] == "Darwin" and ansible_facts['architecture'] == "x86_64"
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/ubuntu/frontend/ios"
      tags:
        - "build_images"
        - "build_frontend_images"
        - "molecule_prepare"
        - "operator_e2e"
        - "dev_debug"
    - name: "Generate frontend/ubuntu.frontend.Dockerfile"
      template:
        src: "files/templates/ubuntu/frontend/ubuntu.frontend.Dockerfile"
        dest: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/ubuntu/frontend/web/JannahIonic/ubuntu.frontend.Dockerfile"
      tags:
        - "build_images"
        - "build_frontend_images"
        - "molecule_prepare"
        - "operator_e2e"
        - "dev_debug"
    - name: "Generate ubuntu/ubuntu.frontend.Dockerfile.dockerignore"
      template:
        src: "files/templates/ubuntu/frontend/ubuntu.frontend.Dockerfile.dockerignore"
        dest: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/ubuntu/frontend/web/JannahIonic/ubuntu.frontend.Dockerfile.dockerignore"
      tags:
        - "build_images"
        - "build_frontend_images"
        - "molecule_prepare"
        - "operator_e2e"
        - "dev_debug"
    - name: "Build Ubuntu frontend imag - jallohmediabuild/jannah-ubuntu-frontend-web-arm64"
      shell: |
        docker buildx build \
          --builder=kube \
          -t jallohmediabuild/jannah-ubuntu-frontend-web-arm64:v0.0.1 \
          --platform=linux/arm64 \
          -f ubuntu.frontend.Dockerfile \
          --load .
      async: 1200
      poll: 5
#      when: ansible_facts['os_family'] == "Darwin" and ansible_facts['architecture'] != "x86_64"
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/ubuntu/frontend/web/JannahIonic/"
      tags:
        - "build_images"
        - "build_frontend_images"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "Build Ubuntu frontend imag - jallohmediabuild/jannah-ubuntu-frontend-web-amd64"
      shell: |
        docker buildx build \
          --builder=kube \
          -t jallohmediabuild/jannah-ubuntu-frontend-web-amd64:v0.0.1 \
          --platform=linux/amd64 \
          -f ubuntu.frontend.Dockerfile \
          --load .
      async: 1200
      poll: 5
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/ubuntu/frontend/web/JannahIonic/"
      tags:
        - "build_images"
        - "build_frontend_images"
        - "molecule_prepare"
        - "operator_e2e"
  rescue:
    - name: "Builds Ubuntu Frontend Docker Images Exception"
      ansible.builtin.debug:
        msg: 'Builds Ubuntu Frontend Docker Images Exception'
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "build_images"
        - "build_frontend_images"
        - "build_ubuntu_images"
        - "molecule_prepare"
        - "operator_e2e"
  ignore_errors: false
