---
- name: "Exec prepare operator - Darwin"
  block:
    - name: "start multipass instance for provisioning"
      shell: |
        multipass start {{ Jannah.stages.bootstrap.build.vm.name }};
      async: 1200
      poll: 5
      tags:
        - "multipass_infra"
        - "molecule_prepare"
        - "operator_e2e"
    #-- sudo snap install juju --classic;
    - name: "install juju"
      shell: |
        multipass exec {{ Jannah.stages.bootstrap.build.vm.name }} \
        -- sudo snap install juju --channel 3.0/stable;
      async: 600
      poll: 5
      register: multipass_infra_install_charmcraft_and_juju
      tags:
        - "multipass_infra"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "Since the juju package is strictly confined, you also need to manually create a path"
      shell: |
        multipass exec {{ Jannah.stages.bootstrap.build.vm.name }} \
        -- mkdir -vp /home/ubuntu/.local/share;
      async: 600
      poll: 5
      register: multipass_infra_manually_create_path
      tags:
        - "multipass_infra"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "juju clouds"
      shell: |
        multipass exec {{ Jannah.stages.bootstrap.build.vm.name }} \
        -- juju clouds;
        exit 0;
      register: multipass_infra_juju_clouds
      tags:
        - "multipass_infra"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "Install juju controller into microk8s cloud - exec"
      shell: |
        multipass exec {{ Jannah.stages.bootstrap.build.vm.name }} \
        -- juju bootstrap --show-log=true --verbose=true microk8s \
        {{ Jannah.stages.bootstrap.build.juju.controller.name }};
      async: 1600
      poll: 3
      register: multipass_infra_install_juju_controller_into_microk8s_cloud
      tags:
        - "multipass_infra"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "Create a workspace/model, on the controller"
      shell: |
        multipass exec {{ Jannah.stages.bootstrap.build.vm.name }} \
        -- juju add-model {{ Jannah.stages.bootstrap.build.juju.model.name }};
      async: 1600
      poll: 3
      register: multipass_infra_create_a_workspace_model_on_the_controller
      tags:
        - "multipass_infra"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "juju status - inline"
      shell: |
        multipass exec {{ Jannah.stages.bootstrap.build.vm.name }} \
        -- juju status;
      tags:
        - "multipass_infra"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "apt update - exec"
      shell: |
        multipass exec {{ Jannah.stages.bootstrap.build.vm.name }} \
        -- sudo apt-get -y update;
        exit 0;
      async: 600
      poll: 5
      register: multipass_infra_install_jhack
      tags:
        - "multipass_infra"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "apt-get -y upgrade - exec"
      environment:
        DEBIAN_FRONTEND: noninteractive
      shell: |
        multipass exec {{ Jannah.stages.bootstrap.build.vm.name }} \
        -- apt-get -y upgrade;
      async: 900
      poll: 10
      register: multipass_infra_install_jhack
      tags:
        - "multipass_infra"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "apt install python3-dev python3-pip virtualenv - exec"
      environment:
        DEBIAN_FRONTEND: noninteractive
      shell: |
        multipass exec {{ Jannah.stages.bootstrap.build.vm.name }} \
        -- sudo DEBIAN_FRONTEND=noninteractive apt install -y make \
        python3-dev \
        python3-pip \
        virtualenv;
        exit 0;
      async: 900
      poll: 10
      register: multipass_infra_install_jhack
      tags:
        - "multipass_infra"
        - "molecule_prepare"
        - "operator_e2e"
    #        - name: "Install jhack"
    #          shell: |
    #            sudo snap install --edge jhack
    #          async: 600
    #          poll: 5
    #          register: multipass_infra_install_jhack
    #          tags:
    #            - "multipass_infra"
    #            - "operator_e2e"
    - name: "Pack operator"
      shell: |
        multipass exec {{ Jannah.stages.bootstrap.build.vm.name }} \
        -- charmcraft pack -v --debug
        exit 0;
      args:
        chdir: "{{ Jannah.global.ansible.working_dir }}/charm/"
      async: 1600
      poll: 15
      register: multipass_infra_pack_operator
      tags:
        - "multipass_infra"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "list jannah-operator_ubuntu-22.04-amd64-arm64.charm"
      shell: |
        multipass exec {{ Jannah.stages.bootstrap.build.vm.name }} \
        -- ls -lrt {{ Jannah.global.ansible.working_dir }}/charm/jannah-operator_ubuntu-22.04-amd64-arm64.charm
        exit 0
      async: 600
      poll: 5
      tags:
        - "multipass_infra"
        - "molecule_prepare"
        - "operator_e2e"
  rescue:
    - name: "Multipass Infra Exception"
      ansible.builtin.debug:
        msg: 'Multipass Infra Exception'
      register: prepare_operator_inline_debug_resources
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
  ignore_errors: false
