---
#   On MacOs M2 or Multipass/Ubuntu, prepare inline for Docker Desktop.
# ('os_family' not in ansible_facts) or  (ansible_facts['os_family'] == "Darwin")
- name: "Prepare Jannah Tasks"
  block:
    - name: "Import prepare tasks - Darwin"
      include_tasks: '{{ item }}'
      with_fileglob:
        - tasks/prepare/exec_prepare.yml
      when: ansible_facts['os_family'] == "Darwin"
      tags:
        - "multipass_infra"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "Import prepare tasks - Ubuntu"
      include_tasks: '{{ item }}'
      with_fileglob:
        - tasks/prepare/inline_prepare.yml
      when: ansible_facts['os_family'] != "Darwin" or ansible_facts['ansible_architecture'] == "arm64"
      tags:
        - "multipass_infra"
        - "molecule_prepare"
        - "operator_e2e"
  rescue:
    - name: "Prepare Jannah Tasks Exception"
      ansible.builtin.debug:
        msg: 'Prepare Jannah Tasks Exception'
      register: preparea_jannah_tasks_debug_resources
    - debug: var=preparea_jannah_tasks_debug_resources
      tags:
        - "perpare_jannah"
        - "operator_e2e"
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
  ignore_errors: false
