---
- name: "Kubernetes Kind cluster tooling cleanup"
  block:
    - name: "Delete cluster"
      environment:
        KUBECONFIG: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/kind/config"
      shell: |
        kind delete clusters "{{ Jannah.stages.bootstrap.deploy.kind.name }}";
        exit 0;
      when: ansible_facts['os_family'] == "Darwin"
      async: 600
      poll: 5
      tags:
        - "molecule_cleanup"
        - "operator_e2e"
  rescue:
    - name: "Kubernetes Kind Tooling Cleanup Exception"
      ansible.builtin.debug:
        msg: 'Kubernetes Kind Tooling Cleanup Exception'
      register: molecule_cleanup_inline_debug_resources
      tags:
        - "molecule_cleanup"
        - "operator_e2e"
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "molecule_cleanup"
        - "operator_e2e"
        - "debug_task"
  ignore_errors: false
