---
- name: "Kubernetes Kind cluster tooling cleanup"
  block:
    - name: "unalias k3ai"
      shell: |
        unalias k3ai;
        exit 0;
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/kind/bin"
      tags:
        - "docker_desktop_infra"
        - "molecule_prepare"
        - "operator_e2e"
        - "debug_task"
    - name: "Install kind 0.18.0 - Darwin(arm64)"
      shell: |
        brew uninstall kind;
      when: ansible_facts['os_family'] == "Darwin"
      async: 600
      poll: 5
      tags:
        - "molecule_create"
        - "operator_e2e"
        - "debug_task"
    - name: "Create MOLECULE_EPHEMERAL_DIRECTORY/kind directory"
      file:
        path: "${MOLECULE_EPHEMERAL_DIRECTORY}/kind/"
        state: absent
      tags:
        - "molecule_create"
        - "operator_e2e"
        - "debug_task"
    - name: "Delete cluster"
      environment:
        KUBECONFIG: "${MOLECULE_EPHEMERAL_DIRECTORY}/kind/config"
      shell: |
        kind delete clusters "{{ Jannah.stages.bootstrap.deploy.kind.name }}";
        exit 0;
      when: ansible_facts['os_family'] == "Darwin" and ansible_facts['architecture'] == "arm64"
      async: 600
      poll: 5
      tags:
        - "molecule_create"
        - "operator_e2e"
        - "debug_task"
  rescue:
    - name: "Kubernetes Kind Tooling Cleanup Exception"
      ansible.builtin.debug:
        msg: 'Kubernetes Kind Tooling Cleanup Exception'
      register: molecule_cleanup_inline_debug_resources
      tags:
        - "molecule_create"
        - "operator_e2e"
        - "debug_task"
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "molecule_create"
        - "operator_e2e"
        - "debug_task"
        -
  ignore_errors: false
