---
- name: "Deploy dependencies for Jannah"
  block:
#    - name: "kubectl get pods -A after dependencies deployment"
#      shell: |
#        kubectl get pods -A
#        exit 0;
#      async: 600
#      poll: 5
#      tags:
#        - "deploy_dependencies"
#        - "operator_e2e"
  rescue:
    - name: "Deploy dependencies for Jannah Exception"
      ansible.builtin.debug:
        msg: 'Deploy dependencies for Jannah Exception'
      register: deploy_dependencies_debug_resources
    - debug: var=deploy_dependencies_debug_resources
      tags:
        - "deploy_dependencies"
        - "operator_e2e"
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
  ignore_errors: false
