---
- name: "Kubernetes m3ai cluster tooling cleanup"
  block:
    - name: "Remove MOLECULE_EPHEMERAL_DIRECTORY/k3ai directory"
      file:
        path: "${MOLECULE_EPHEMERAL_DIRECTORY}/k3ai/bin"
        state: absent
      tags:
        - "molecule_create"
        - "operator_e2e"
    - name: "unalias k3ai"
      shell: |
        unalias k3ai;
        exit 0;
      tags:
        - "docker_desktop_infra"
        - "molecule_prepare"
        - "operator_e2e"
  rescue:
    - name: "Kubernetes Kind Tooling Cleanup Exception"
      ansible.builtin.debug:
        msg: 'Kubernetes Kind Tooling Cleanup Exception'
      register: molecule_cleanup_inline_debug_resources
      tags:
        - "molecule_create"
        - "operator_e2e"
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "molecule_create"
        - "operator_e2e"
  ignore_errors: false
