---
- name: "Exec destroy infra - Inline"
  block:
    - name: "Uninstall lxc  - Inline/Darwin"
      shell: |
        brew uninstall lxc;
      when: ansible_facts['os_family'] == "Darwin"
      async: 600
      poll: 5
      tags:
        - "multipass_infra"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Uninstall charmcraft - Inline/Darwin"
      shell: |
        brew uninstall charmcraft;
      when: ansible_facts['os_family'] == "Darwin"
      async: 600
      poll: 5
      tags:
        - "multipass_infra"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "uninstall microk8s  - Inline/Darwin"
      shell: |
        brew uninstall ubuntu/microk8s/microk8s;
      when: ansible_facts['os_family'] == "Darwin"
      async: 1200
      poll: 5
      tags:
        - "multipass_infra"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "uninstall microk8s  - Inline/Ubuntu"
      shell: |
        sudo snap remove microk8s;
      when: ansible_facts['os_family'] == "Ubuntu"
      async: 600
      poll: 5
      tags:
        - "multipass_infra"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "remove ubuntu from snap_microk8s  - Inline/Ubuntu"
      shell: |
        sudo usermod -r -G snap_microk8s ubuntu;
      when: ansible_facts['os_family'] == "Ubuntu"
      async: 600
      poll: 5
      register: multipass_infra_add_ubuntu_to_snap_microk8s
      tags:
        - "multipass_infra"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "uninstall juju - Darwin"
      shell: |
        brew uninstall juju;
      when: ansible_facts['os_family'] == "Darwin"
      async: 600
      poll: 5
      tags:
        - "multipass_infra"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "uninstall juju - Ubuntu/Darwin(ARM64)"
      shell: |
        snap remove juju;
      when: ansible_facts['os_family'] != "Darwin"
      async: 600
      poll: 5
      tags:
        - "multipass_infra"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "remove  ~/.local/share"
      file:
        path: "~/.local/share"
        state: absent
      tags:
        - "multipass_infra"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Remove jannah-operator_ubuntu-22.04-amd64-arm64.charm - Ubuntu/Darwin(ARM64)"
      shell: |
        rm {{ Jannah.global.ansible.working_dir }}/charm/jannah-operator_ubuntu-22.04-amd64-arm64.charm;
        exit 0;
      async: 600
      poll: 5
      tags:
        - "multipass_infra"
        - "molecule_destroy"
        - "operator_e2e"
  rescue:
    - name: "Exec destroy infra inline Exception "
      ansible.builtin.debug:
        msg: 'Exec destroy infra inline Exception'
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
  ignore_errors: false
