---
#   On MacOs M2 or Multipass/Ubuntu, prepare inline for Docker Desktop.
# ('os_family' not in ansible_facts) or  (ansible_facts['os_family'] == "Darwin")
- name: "Destroy Jannah environment Tasks"
  block:
    - name: "Import destroy tasks - Darwin"
      include_tasks: '{{ destroy_exec_task_item }}'
      with_fileglob:
        - destroy/exec_destroy.yml
      loop_control:
        loop_var: destroy_exec_task_item
      when: ansible_facts['os_family'] == "Darwin"
      tags:
        - "multipass_infra"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Import destroy tasks - Ubuntu, Darwin arm64"
      include_tasks: '{{ destroy_inline_task_item }}'
      with_fileglob:
        - destroy/inline_destroy.yml
      loop_control:
        loop_var: destroy_inline_task_item
      when: ansible_facts['os_family'] != "Darwin" or ansible_facts['architecture'] == "arm64"
      tags:
        - "multipass_infra"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Destroy MOLECULE_EPHEMERAL_DIRECTORY directory"
      file:
        path: "{{ provisioner.env.MOLECULE_EPHEMERAL_DIRECTORY }}"
        state: directory
        mode: 0755
      tags:
        - "deploy_dependencies"
        - "molecule_converge"
        - "operator_e2e"
  rescue:
    - name: "Destroy Jannah Tasks Exception"
      ansible.builtin.debug:
        msg: 'Destroy Jannah Tasks Exception'
      register: preparea_jannah_tasks_debug_resources
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
  ignore_errors: false
