---
- name: "All the required playbooks before Jannah is deployed"
  block:
    - name: Import prerequisite tasks
      include_tasks: '{{ prerequisite_item }}'
      with_fileglob:
        - documentations/main.yml
      loop_control:
        loop_var: prerequisite_item
      tags:
        - "install-chruby-ruby-install"
        - "install-ruby-install-ruby-3-1-3"
        - "zshrc-use-chruby"
        - "show-ruby-version"
        - "gem-install-jekyll"
        - "gem-install-jekyll-bundler"
        - "create-new-jekyll-site-directory"
        - "jekyll-new-jannah-operator"
        - "generate-index-markdown"
        - "generate-site-config"
        - "generate-about-markdown"
        - "generate-404-markdown"
        - "blog-service-install"
        - "generate-blog-posts"
        - "generate-blog-pages"
        - "operator"
  rescue:
    - name: "Install requirements exception is thrown"
      ansible.builtin.debug:
        msg: 'Install requirements exception is thrown'
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
  always:
    - name: "Documentation"
      ansible.builtin.debug:
        msg: 'Documentation'
  #become: true
  ignore_errors: false
