---
- name: Cleanup
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - kubernetes.core
  tasks:
    - block:
        - name: Import all tasks/cleanup by order
          include_tasks: '{{ item }}'
          with_fileglob:
          tags:
            - "bootstrap_namespace_cleanup"
            - "bootstrap_prepared_tasks_cleanup"
            - "bootstrap_secretes_cleanup"
            - "bootstrap_kustomize_cleanup"
      rescue:
        - name: Re-emit failure
          vars:
            failed_task:
              result: '{{ ansible_failed_result }}'
          fail:
            msg: '{{ failed_task }}'
      ignore_errors: false

