---
- name: Converge
  hosts: localhost
  connection: local
  tasks:
    - name: "Include jannahio.bootstrap"
      include_role:
        name: "jannahio.charm"
      tags:
        - "bootstrap_jannah_namespace"
        - "secrets_infra"
        - "bootstrap_make_bundle"
        - "bootstrap_kustomize"
        - "bootstrap_get_kustomize"

