---
- name: "Debug Deploy dependencies for Jannah"
  block:
    - name: "Create MOLECULE_EPHEMERAL_DIRECTORY/stages/bootstrap/build/secrets/root_cert directory"
      file:
        path: "{{ provisioner.env.MOLECULE_EPHEMERAL_DIRECTORY }}/stages/bootstrap/build/secrets/root_cert"
        state: directory
        mode: 0755
      tags:
        - "deploy_dependencies"
        - "molecule_converge"
        - "operator_e2e"
        - "dev_debug"
    - name: "Create MOLECULE_EPHEMERAL_DIRECTORY/stages/bootstrap/build/github directory"
      file:
        path: "{{ provisioner.env.MOLECULE_EPHEMERAL_DIRECTORY }}/stages/bootstrap/build/github/dex"
        state: directory
        mode: 0755
      tags:
        - "deploy_dependencies"
        - "molecule_converge"
        - "operator_e2e"
        - "dev_debug"

    - name: "Clone Dex repository for debugging"
      ansible.builtin.git:
        repo: https://github.com/dexidp/dex.git
        dest: "{{ provisioner.env.MOLECULE_EPHEMERAL_DIRECTORY }}/stages/bootstrap/build/github/dex/"
      tags:
        - "deploy_dependencies"
        - "molecule_converge"
        - "operator_e2e"
        - "dev_debug"


    - name: "Generate MOLECULE_EPHEMERAL_DIRECTORY/stages/bootstrap/build/secrets/root_cert/certificate.sh"
      environment:
        DNS_1: "{{ ansible_facts['all_ipv4_addresses'][1] }}"
        IP_1: "{{ ansible_facts['all_ipv4_addresses'][1] }}"
        DNS_2: "{{ ansible_facts['all_ipv4_addresses'][0] }}"
        IP_2: "{{ ansible_facts['all_ipv4_addresses'][0] }}"
      template:
        src: "files/templates/certificates.sh"
        dest: "{{ provisioner.env.MOLECULE_EPHEMERAL_DIRECTORY }}/stages/bootstrap/build/secrets/root_cert/certificate.sh"
        backup: yes
      tags:
        - "deploy_dependencies"
        - "molecule_converge"
        - "operator_e2e"
        - "dev_debug"

    - name: "run MOLECULE_EPHEMERAL_DIRECTORY/stages/bootstrap/build/secrets/root_cert/certificate.sh - exec"
      shell: |
        multipass exec {{ Jannah.stages.bootstrap.build.vm.name }} \
        -- chmod +x certificate.sh;
      args:
        chdir: "{{ provisioner.env.MOLECULE_EPHEMERAL_DIRECTORY }}/stages/bootstrap/build/secrets/root_cert/"
      tags:
        - "deploy_dependencies"
        - "molecule_converge"
        - "operator_e2e"
        - "dev_debug"

    - name: "run MOLECULE_EPHEMERAL_DIRECTORY/stages/bootstrap/build/secrets/root_cert/certificate.sh - exec"
      shell: |
        multipass exec {{ Jannah.stages.bootstrap.build.vm.name }} \
        -- ./certificate.sh
      args:
        chdir: "{{ provisioner.env.MOLECULE_EPHEMERAL_DIRECTORY }}/stages/bootstrap/build/secrets/root_cert/"
      tags:
        - "deploy_dependencies"
        - "molecule_converge"
        - "operator_e2e"
        - "dev_debug"

  rescue:
    - name: "Debug Deploy dependencies for Jannah Exception"
      ansible.builtin.debug:
        msg: 'Debug Deploy dependencies for Jannah Exception'
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
  ignore_errors: false
