---
- name: "Builds streamos docker images for use in Helm Chart"
  block:
    - name: "set_fact jannah_stages_bootstrap_deploy_destination"
      ansible.builtin.set_fact:
        jannah_stages_bootstrap_deploy_destination: "{{ Jannah.stages.bootstrap.deploy.destination }}"
      tags:
        - "deploy_images"
        - "molecule_create"
        - "operator_e2e"
    - name: "set_fact jannah_stages_bootstrap_deploy_os"
      ansible.builtin.set_fact:
        jannah_stages_bootstrap_deploy_os: "{{ Jannah.stages.bootstrap.deploy.os }}"
      tags:
        - "deploy_images"
        - "molecule_create"
        - "operator_e2e"
    - name: "Create images/streamos directory"
      file:
        path: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/streamos"
        state: directory
        mode: 0755
      tags:
        - "build_images"
        - "molecule_create"
        - "operator_e2e"
    - name: "Generate images/streamos/streamos.Dockerfile"
      template:
        src: "files/templates/streamos/streamos.boot.Dockerfile"
        dest: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/streamos/streamos.boot.Dockerfile"
      tags:
        - "build_images"
        - "molecule_create"
        - "operator_e2e"
    - name: "Generate streamos/streamos.Dockerfile.dockerignore"
      template:
        src: "files/templates/streamos/streamos.boot.Dockerfile.dockerignore"
        dest: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/streamos/streamos.boot.Dockerfile.dockerignore"
      tags:
        - "build_images"
        - "molecule_create"
        - "operator_e2e"
    - name: "Build StreamOs boot image - arm64 - docker-desktop"
      shell: |
        docker buildx build \
          --builder=kube \
          -t \
          {{ Jannah.stages.bootstrap.deploy.helm_values.images.boot.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.arm }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.streamos }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }} \
          --platform=linux/arm64 \
          -f streamos.boot.Dockerfile \
          --load .
      when: (
            ansible_facts['architecture'] != "x86_64" 
            and 
            jannah_stages_bootstrap_deploy_os == "streamos"
            and
            jannah_stages_bootstrap_deploy_destination == "docker-desktop"
          )
      async: 9800
      poll: 5
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/streamos"
      tags:
        - "build_images"
        - "molecule_create"
        - "operator_e2e"
    - name: "Build StreamOs boot image - arm64 - kind"
      shell: |
        docker build \
          -t \
          {{ Jannah.stages.bootstrap.deploy.helm_values.images.boot.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.arm }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.streamos }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }} \
          -f streamos.boot.Dockerfile .;
      when: (
            ansible_facts['architecture'] != "x86_64" 
            and 
            jannah_stages_bootstrap_deploy_os == "streamos"
            and
            jannah_stages_bootstrap_deploy_destination == "kind"
          )
      async: 9800
      poll: 5
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/streamos"
      tags:
        - "build_images"
        - "molecule_create"
        - "operator_e2e"
    - name: "Build StreamOs boot image - amd64 docker-desktop"
      shell: |
        docker buildx build \
          --builder=kube \
          -t \
          {{ Jannah.stages.bootstrap.deploy.helm_values.images.boot.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.amd }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.streamos }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }} \
          --platform=linux/amd64 \
          -f streamos.boot.Dockerfile \
          --load .
      when: (
              ansible_facts['architecture'] == "x86_64" 
              and 
              jannah_stages_bootstrap_deploy_os == "streamos"
              and
              jannah_stages_bootstrap_deploy_destination == "docker-desktop"
            )
      async: 9800
      poll: 5
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/streamos"
      tags:
        - "build_images"
        - "molecule_create"
        - "operator_e2e"
    - name: "Build StreamOs boot image - amd64 kind"
      shell: |
        docker build \
          -t \
          {{ Jannah.stages.bootstrap.deploy.helm_values.images.boot.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.amd }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.streamos }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }} \
          -f streamos.boot.Dockerfile .;
      when: (
              ansible_facts['architecture'] == "x86_64" 
              and 
              jannah_stages_bootstrap_deploy_os == "streamos"
              and
              jannah_stages_bootstrap_deploy_destination == "kind"
            )
      async: 9800
      poll: 5
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/streamos"
      tags:
        - "build_images"
        - "molecule_create"
        - "operator_e2e"
    - name: "Import prepare build image tasks - streamos middleware and frontend"
      include_tasks: '{{ prepare_streamos_middleware_and_frontend_task_items }}'
      with_fileglob:
        - build_streamos_middleware_images.yml
        - build_streamos_frontend_images.yml
      loop_control:
        loop_var: prepare_streamos_middleware_and_frontend_task_items
      tags:
        - "docker_desktop_infra"
        - "molecule_create"
        - "operator_e2e"
  rescue:
    - name: "Builds and StreamOs Docker Images Exception"
      ansible.builtin.debug:
        msg: 'Builds StreamOs Docker Images Exception'
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "build_images"
        - "build_streamos_images"
        - "molecule_create"
        - "operator_e2e"
  ignore_errors: false
