---
- name: "Builds streamos middleware docker images for use in Helm Chart"
  block:
    - name: "set_fact jannah_stages_bootstrap_deploy_destination"
      ansible.builtin.set_fact:
        jannah_stages_bootstrap_deploy_destination: "{{ Jannah.stages.bootstrap.deploy.destination }}"
      tags:
        - "deploy_images"
        - "molecule_converge"
        - "operator_e2e"
    - name: "set_fact jannah_stages_bootstrap_deploy_os"
      ansible.builtin.set_fact:
        jannah_stages_bootstrap_deploy_os: "{{ Jannah.stages.bootstrap.deploy.os }}"
      tags:
        - "deploy_images"
        - "molecule_create"
        - "operator_e2e"
    - name: "Create /images/streamos/middleware directory"
      file:
        path: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/streamos/middleware"
        state: directory
        mode: 0755
      tags:
        - "build_images"
        - "build_middleware_images"
        - "molecule_create"
        - "operator_e2e"
    - name: "Git checkout https://github.com/jannahio/middleware.git for streamos build"
      ansible.builtin.git:
        repo: "https://github.com/jannahio/middleware.git"
        dest: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/streamos/middleware"
        version: "task-aVYVi17T-base-jannah-django-app-model.login_jannah.graphql.cursor_addendum"
      tags:
        - "build_images"
        - "build_middleware_images"
        - "molecule_create"
        - "operator_e2e"
    - name: "Generate middleware/streamos.middleware.Dockerfile"
      template:
        src: "files/templates/streamos/middleware/streamos.middleware.Dockerfile"
        dest: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/streamos/middleware/jannah_graphql/streamos.middleware.Dockerfile"
      tags:
        - "build_images"
        - "molecule_create"
        - "operator_e2e"
    - name: "Generate streamos/streamos.middleware.Dockerfile.dockerignore"
      template:
        src: "files/templates/streamos/middleware/streamos.middleware.Dockerfile.dockerignore"
        dest: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/streamos/middleware/jannah_graphql/streamos.middleware.Dockerfile.dockerignore"
      tags:
        - "build_images"
        - "molecule_create"
        - "operator_e2e"
    - name: "Build StreamOs middleware image - arm64  docker-desktop"
      shell: |
        docker buildx build \
          --builder=kube \
          -t \
          {{ Jannah.stages.bootstrap.deploy.helm_values.images.middleware.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.arm }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.streamos }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }} \
          --platform=linux/arm64 \
          -f streamos.middleware.Dockerfile \
          --load .
      when: (
              ansible_facts['architecture'] != "x86_64" 
              and 
              jannah_stages_bootstrap_deploy_os == "streamos"
              and
              jannah_stages_bootstrap_deploy_destination == "docker-desktop"
            )
      async: 9800
      poll: 5
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/streamos/middleware/jannah_graphql"
      tags:
        - "build_images"
        - "molecule_create"
        - "operator_e2e"
    - name: "Build StreamOs middleware image - arm64  kind"
      shell: |
        docker build \
          -t \
          {{ Jannah.stages.bootstrap.deploy.helm_values.images.middleware.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.arm }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.streamos }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }} \
          -f streamos.middleware.Dockerfile .;
      when: (
              ansible_facts['architecture'] != "x86_64" 
              and 
              jannah_stages_bootstrap_deploy_os == "streamos"
              and
              jannah_stages_bootstrap_deploy_destination == "kind"
            )
      async: 9800
      poll: 5
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/streamos/middleware/jannah_graphql"
      tags:
        - "build_images"
        - "molecule_create"
        - "operator_e2e"
    - name: "Build StreamOs middleware image - amd64 docker-desktop"
      shell: |
        docker buildx build \
          --builder=kube \
          -t \
          {{ Jannah.stages.bootstrap.deploy.helm_values.images.middleware.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.amd }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.streamos }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }} \
          --platform=linux/amd64 \
          -f streamos.middleware.Dockerfile \
          --load .
      when: (
              ansible_facts['architecture'] == "x86_64" 
              and
              jannah_stages_bootstrap_deploy_os == "streamos"
              and
              jannah_stages_bootstrap_deploy_destination == "docker-desktop"
            )
      async: 9800
      poll: 5
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/streamos/middleware/jannah_graphql"
      tags:
        - "build_images"
        - "molecule_create"
        - "operator_e2e"
    - name: "Build StreamOs middleware image - amd64 kind"
      shell: |
        docker build \
          -t \
          {{ Jannah.stages.bootstrap.deploy.helm_values.images.middleware.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.amd }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.streamos }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }} \
          -f streamos.middleware.Dockerfile .;
      when: (
              ansible_facts['architecture'] == "x86_64" 
              and
              jannah_stages_bootstrap_deploy_os == "streamos"
              and
              jannah_stages_bootstrap_deploy_destination == "kind"
            )
      async: 9800
      poll: 5
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/streamos/middleware/jannah_graphql"
      tags:
        - "build_images"
        - "molecule_create"
        - "operator_e2e"
  rescue:
    - name: "Builds StreamOs Middleware Docker Images Exception"
      ansible.builtin.debug:
        msg: 'Builds StreamOs Middleware Docker Images Exception'
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "build_images"
        - "build_ubuntu_images"
        - "molecule_create"
        - "operator_e2e"
  ignore_errors: false
