---
- name: "Builds streamos middleware docker images for use in Helm Chart"
  block:
    - name: "set_fact jannah_stages_bootstrap_deploy_destination"
      ansible.builtin.set_fact:
        jannah_stages_bootstrap_deploy_destination: "{{ Jannah.stages.bootstrap.deploy.destination }}"
      tags:
        - "deploy_images"
        - "molecule_create"
        - "operator_e2e"
    - name: "set_fact jannah_stages_bootstrap_deploy_os"
      ansible.builtin.set_fact:
        jannah_stages_bootstrap_deploy_os: "{{ Jannah.stages.bootstrap.deploy.os }}"
      tags:
        - "deploy_images"
        - "molecule_create"
        - "operator_e2e"
    - name: "Create /images/streamos/middleware directory"
      file:
        path: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/images/streamos/middleware"
        state: directory
        mode: 0755
      tags:
        - "build_images"
        - "build_middleware_images"
        - "molecule_create"
        - "operator_e2e"
    - name: "Git checkout repository for streamos build"
      ansible.builtin.git:
        repo: "{{ Jannah.stages.bootstrap.deploy.helm_values.images.middleware.github.repo }}" 
        dest: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/images/streamos/middleware"
        version: "{{ Jannah.stages.bootstrap.deploy.helm_values.images.middleware.github.branch }}"
        force: yes 
      tags:
        - "build_images"
        - "build_middleware_images"
        - "molecule_create"
        - "operator_e2e"
    - name: "Generate middleware/streamos.middleware.Dockerfile"
      template:
        src: "files/templates/streamos/middleware/streamos.middleware.Dockerfile"
        dest: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/images/streamos/middleware/jannah_graphql/streamos.middleware.Dockerfile"
      tags:
        - "build_images"
        - "molecule_create"
        - "operator_e2e"
    - name: "Generate streamos/streamos.middleware.Dockerfile.dockerignore"
      template:
        src: "files/templates/streamos/middleware/streamos.middleware.Dockerfile.dockerignore"
        dest: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/images/streamos/middleware/jannah_graphql/streamos.middleware.Dockerfile.dockerignore"
      tags:
        - "build_images"
        - "molecule_create"
        - "operator_e2e"
# Part of https://www.percona.com/blog/deploy-django-on-kubernetes-with-percona-operator-for-postgresql
# and https://pypi.org/project/dj-database-url/
    - name: "Generate .env for middleware - streamos"
      template:
        src: "files/templates/helm/middleware/env.template"
        dest: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/images/streamos/middleware/jannah_graphql/.env"
      tags:
        - "molecule_create"
        - "operator_e2e"
    - name: "Get pgbouncer-uri - docker-desktop"
      shell: |
        kubectl get secret \
        "{{ Jannah.stages.bootstrap.secrets.percona_db.name }}" \
        -n "{{ Jannah.stages.bootstrap.deploy.helm_values.common.namespace }}" \
        --template='{{ '{{' }}index .data "pgbouncer-uri" | base64decode {{ '}}' }}';
      # To be used downstream ( prepared_artifacts ) as environment variable in the middleware
      register: cluster1_pguser_cluster1_pgbouncer_uri
      when: (
               jannah_stages_bootstrap_deploy_destination == "docker-desktop"
            )
      tags:
        - "molecule_create"
        - "operator_e2e"
    - name: "cluster1_pguser_cluster1_pgbouncer_uri - docker-desktop"
      debug: var=cluster1_pguser_cluster1_pgbouncer_uri
      when: (
               jannah_stages_bootstrap_deploy_destination == "docker-desktop"
            )
      tags:
        - "molecule_create"
        - "operator_e2e"
    - name: "save pgbouncer-uri to env file - streamos - docker-desktop"
      shell: |
        echo "\nDATABASE_URL={{ cluster1_pguser_cluster1_pgbouncer_uri['stdout_lines'][0]  }}?sslmode=prefer&connect_timeout=10"  >> \
        "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/images/streamos/middleware/jannah_graphql/.env";
      when: (
               jannah_stages_bootstrap_deploy_destination == "docker-desktop"
            )
      tags:
        - "molecule_create"
        - "operator_e2e"
    - name: "Get pgbouncer-uri - kind-cluster"
      environment:
        - KUBECONFIG: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/kind/config"
      shell: |
        kubectl get secret \
        "{{ Jannah.stages.bootstrap.secrets.percona_db.name }}" \
        -n "{{ Jannah.stages.bootstrap.deploy.helm_values.common.namespace }}" \
        --template='{{ '{{' }}index .data "pgbouncer-uri" | base64decode {{ '}}' }}';
      # To be used downstream ( prepared_artifacts ) as environment variable in the middleware
      register: cluster1_pguser_cluster1_pgbouncer_uri
      when: (
               jannah_stages_bootstrap_deploy_destination == "kind"
            )
      tags:
        - "molecule_create"
        - "operator_e2e"
    - name: "cluster1_pguser_cluster1_pgbouncer_uri - kind-cluster"
      debug: var=cluster1_pguser_cluster1_pgbouncer_uri
      when: (
               jannah_stages_bootstrap_deploy_destination == "kind"
            )
      tags:
        - "molecule_create"
        - "operator_e2e"
    - name: "save pgbouncer-uri to env file - streamos - kind-cluster"
      shell: |
        echo "\nDATABASE_URL={{ cluster1_pguser_cluster1_pgbouncer_uri['stdout_lines'][0]  }}?sslmode=disable&connect_timeout=10"  >> \
        "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/images/streamos/middleware/jannah_graphql/.env";
      when: (
               jannah_stages_bootstrap_deploy_destination == "kind"
            )
      tags:
        - "molecule_create"
        - "operator_e2e"
    - name: "Build StreamOs middleware image - arm64  docker-desktop"
      shell: |
        docker buildx build \
          --builder=kube \
          -t \
          {{ Jannah.stages.bootstrap.deploy.helm_values.images.middleware.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.arm }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.streamos }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }} \
          --platform=linux/arm64 \
          -f streamos.middleware.Dockerfile \
          --load .
      when: (
              ansible_facts['architecture'] != "x86_64" 
              and 
              jannah_stages_bootstrap_deploy_os == "streamos"
              and
              jannah_stages_bootstrap_deploy_destination == "docker-desktop"
            )
      async: 9800
      poll: 5
      args:
        chdir: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/images/streamos/middleware/jannah_graphql"
      tags:
        - "build_images"
        - "molecule_create"
        - "operator_e2e"
    - name: "Build StreamOs middleware image - arm64  kind cluster"
      shell: |
        docker build \
          -t \
          {{ Jannah.stages.bootstrap.deploy.helm_values.images.middleware.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.arm }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.streamos }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }} \
          -f streamos.middleware.Dockerfile .;
      when: (
              ansible_facts['architecture'] != "x86_64" 
              and 
              jannah_stages_bootstrap_deploy_os == "streamos"
              and
              jannah_stages_bootstrap_deploy_destination == "kind"
            )
      async: 9800
      poll: 5
      args:
        chdir: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/images/streamos/middleware/jannah_graphql"
      tags:
        - "build_images"
        - "molecule_create"
        - "operator_e2e"
    - name: "Build StreamOs middleware image - amd64 docker-desktop"
      shell: |
        docker buildx build \
          --builder=kube \
          -t \
          {{ Jannah.stages.bootstrap.deploy.helm_values.images.middleware.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.amd }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.streamos }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }} \
          --platform=linux/amd64 \
          -f streamos.middleware.Dockerfile \
          --load .
      when: (
              ansible_facts['architecture'] == "x86_64" 
              and
              jannah_stages_bootstrap_deploy_os == "streamos"
              and
              jannah_stages_bootstrap_deploy_destination == "docker-desktop"
            )
      async: 9800
      poll: 5
      args:
        chdir: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/images/streamos/middleware/jannah_graphql"
      tags:
        - "build_images"
        - "molecule_create"
        - "operator_e2e"
    - name: "Build StreamOs middleware image - amd64 kind cluster"
      shell: |
        docker build \
          -t \
          {{ Jannah.stages.bootstrap.deploy.helm_values.images.middleware.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.amd }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.streamos }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }} \
          -f streamos.middleware.Dockerfile .;
      when: (
              ansible_facts['architecture'] == "x86_64" 
              and
              jannah_stages_bootstrap_deploy_os == "streamos"
              and
              jannah_stages_bootstrap_deploy_destination == "kind"
            )
      async: 9800
      poll: 5
      args:
        chdir: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/images/streamos/middleware/jannah_graphql"
      tags:
        - "build_images"
        - "molecule_create"
        - "operator_e2e"
  rescue:
    - name: "Builds StreamOs Middleware Docker Images Exception"
      ansible.builtin.debug:
        msg: 'Builds StreamOs Middleware Docker Images Exception'
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "build_images"
        - "build_ubuntu_images"
        - "molecule_create"
        - "operator_e2e"
  ignore_errors: false
