---
# Implements https://github.com/kubeflow/manifests#installation
- name: "Create MacOs Docker Desktop Infra"
  block:
    - name: "Create install_kustomize download directory"
      file:
        path: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/install_kustomize"
        state: directory
        mode: 0755
      tags:
        - "docker_desktop_infra"
        - "molecule_create"
        - "operator_e2e"
    # 08/22/2022 - Osmanj - The latest version of Kustomize is buggy?
    # It does not recognize the --load_restrictor='LoadRestrictionsNone' flog
    # Current workaround is to install v3.8.7
    - name: "wget kustomize_v5.0.3_darwin_amd64.tar.gz Darwin/amd64"
      shell: |
        wget  \
        https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.0.3/kustomize_v5.0.3_darwin_amd64.tar.gz;
      async: 1200
      poll: 5
      when: ansible_facts['os_family'] == "Darwin" and ansible_facts['architecture'] == "x86_64"
      args:
        chdir: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/install_kustomize"
      tags:
        - "docker_desktop_infra"
        - "molecule_create"
        - "operator_e2e"
    - name: "wget kustomize_v5.0.3_darwin_amd64.tar.gz Darwin/arm64"
      shell: |
        wget  \
        https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.0.3/kustomize_v5.0.3_darwin_arm64.tar.gz;
      async: 1200
      poll: 5
      when: ansible_facts['os_family'] == "Darwin" and ansible_facts['architecture'] != "x86_64"
      args:
        chdir: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/install_kustomize"
      tags:
        - "docker_desktop_infra"
        - "molecule_create"
        - "operator_e2e"
    - name: "tar xvf kustomize_v5.0.3_darwin_amd64.tar.gz"
      shell: |
        tar xvf kustomize_v5.0.3_darwin_amd64.tar.gz
      when: ansible_facts['os_family'] == "Darwin" and ansible_facts['architecture'] == "x86_64"
      args:
        chdir: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/install_kustomize"
      tags:
        - "docker_desktop_infra"
        - "molecule_create"
        - "operator_e2e"
    - name: "tar xvf kustomize_v5.0.3_darwin_arm64.tar.gz"
      shell: |
        tar xvf kustomize_v5.0.3_darwin_arm64.tar.gz
      when: ansible_facts['os_family'] == "Darwin" and ansible_facts['architecture'] != "x86_64"
      args:
        chdir: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/install_kustomize"
      tags:
        - "docker_desktop_infra"
        - "molecule_create"
        - "operator_e2e"
    - name: "alias kustomize"
      shell: |
        alias kustomize="{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/install_kustomize/kustomize";
      args:
        chdir: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/install_kustomize"
      tags:
        - "docker_desktop_infra"
        - "molecule_create"
        - "operator_e2e"
  rescue:
    - name: "Create MacOs Docker Desktop Infra Exception"
      ansible.builtin.debug:
        msg: 'Create MacOs Docker Desktop Infra Exception'
      tags:
        - "docker_desktop_infra"
        - "molecule_create"
        - "operator_e2e"
    - name: "Re-emit failure"
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "multipass_infra"
        - "molecule_create"
        - "operator_e2e"
  ignore_errors: false
