---
- name: "Cleanup artifacts from MacOs Docker Desktop"
  block:
    - name: "Kubeflow uninstall"
      shell: |
        while ! ${MOLECULE_EPHEMERAL_DIRECTORY}/install_kustomize/kustomize build example | awk '!/well-defined/' | kubectl delete -f -; do echo "Retrying to apply resources"; sleep 10; done;
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/kubeflow/manifests"
      tags:
        - "docker_desktop_infra"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "Remove install_kustomize download directory"
      file:
        path: "${MOLECULE_EPHEMERAL_DIRECTORY}/install_kustomize"
        state: absent
      tags:
        - "docker_desktop_infra"
        - "molecule_cleanup"
        - "operator_e2e"
    - name: "unalias kustomize "
      shell: |
        unalias kustomize;
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/install_kustomize"
      tags:
        - "docker_desktop_infra"
        - "molecule_cleanup"
        - "operator_e2e"
    - name: "Remove kubeflow download directory"
      file:
        path: "${MOLECULE_EPHEMERAL_DIRECTORY}/kubeflow/manifests"
        state: absent
      tags:
        - "docker_desktop_infra"
        - "molecule_cleanup"
        - "operator_e2e"
    - name: "arch -x86_64 gem uninstall ffi"
      shell: |
        arch -x86_64 gem install ffi;
      async: 600
      poll: 5
      when: ansible_facts['os_family'] == "Darwin" and ansible_facts['architecture'] != "x86_64"
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/install_kustomize"
      tags:
        - "docker_desktop_infra"
        - "molecule_cleanup"
        - "operator_e2e"
  rescue:
    - name: "Clean Prepared Operator MacOs Docker Desktop Exception"
      ansible.builtin.debug:
        msg: 'Clean Prepared Operator MacOs Docker Desktop Exception'
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "multipass_infra"
        - "molecule_cleanup"
        - "operator_e2e"
  ignore_errors: false
