---
- name: "Kubernetes m3ai cluster tooling"
  block:
    - name: "Create MOLECULE_EPHEMERAL_DIRECTORY/k3ai directory"
      file:
        path: "${MOLECULE_EPHEMERAL_DIRECTORY}/k3ai/bin"
        state: directory
        mode: 0755
      tags:
        - "molecule_create"
        - "operator_e2e"
    - name: "get-mac.k3ai.in - Darwin(amd64)"
      shell: |
        wget https://github.com/k3ai/k3ai/releases/download/1.0.1/k3ai.darwin.amd64
      when: ansible_facts['os_family'] == "Darwin" and ansible_facts['architecture'] == "x86_64"
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/k3ai/bin"
      async: 600
      poll: 5
      tags:
        - "molecule_create"
        - "operator_e2e"
    - name: "get-mac.k3ai.in - Darwin(arm64)"
      shell: |
        wget https://github.com/k3ai/k3ai/releases/download/1.0.1/k3ai.darwin.armd64
      when: ansible_facts['os_family'] == "Darwin" and ansible_facts['architecture'] == "arm64"
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/k3ai/bin"
      async: 600
      poll: 5
      tags:
        - "molecule_create"
        - "operator_e2e"
    - name: "get-mac.k3ai.in - Darwin(amd64)"
      shell: |
        mv k3ai.darwin.amd64 k3ai;
        chmod +x k3ai
      when: ansible_facts['os_family'] == "Darwin" and ansible_facts['architecture'] == "x86_64"
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/k3ai/bin"
      async: 600
      poll: 5
      tags:
        - "molecule_create"
        - "operator_e2e"
    - name: "get-mac.k3ai.in - Darwin(arm64)"
      shell: |
        mv k3ai.darwin.arm64 k3ai;
        chmod +x k3ai
      when: ansible_facts['os_family'] == "Darwin" and ansible_facts['architecture'] == "arm64"
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/k3ai/bin"
      async: 600
      poll: 5
      tags:
        - "molecule_create"
        - "operator_e2e"
    - name: "alias k3ai"
      shell: |
        alias k3ai="${MOLECULE_EPHEMERAL_DIRECTORY}/k3ai/bin/k3ai";
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/k3ai/bin"
      tags:
        - "docker_desktop_infra"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "alias k3ai"
      shell: |
        ${MOLECULE_EPHEMERAL_DIRECTORY}/k3ai/bin/k3ai cluster deploy -t k3s -n "{{ Jannah.stages.bootstrap.deploy.k3ai.name }}";
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/k3ai/bin"
      tags:
        - "docker_desktop_infra"
        - "molecule_prepare"
        - "operator_e2e"
  rescue:
    - name: "Kubernetes Kind Tooling Exception"
      ansible.builtin.debug:
        msg: 'Kubernetes Kind Tooling Exception'
      register: molecule_create_inline_debug_resources
      tags:
        - "molecule_create"
        - "operator_e2e"
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "molecule_create"
        - "operator_e2e"
  ignore_errors: false
