---
# Implements https://jekyllrb.com/docs/
# https://mac.install.guide/ruby/13.html
  - name: "Install Jekyll Blog Infra"
    block:
#      # Install all prerequisites.
#      - name: "brew install chruby ruby-install"
#        shell: |
#          brew install chruby ruby-install xz
#        tags:
#          - "blog-service-install"
#          - "install-chruby-ruby-install"
#          - "operator"
#      - name: "ruby-install ruby - This will take a few minutes"
#        shell: |
#          ruby-install ruby 3.1.3
#        tags:
#          - "blog-service-install"
#          - "install-ruby-install-ruby-3-1-3"
#          - "operator"
#      - name: "Configure shell to automatically use chruby"
#        shell: |
#          echo "source $(brew --prefix)/opt/chruby/share/chruby/chruby.sh" >> ~/.zshrc
#          echo "source $(brew --prefix)/opt/chruby/share/chruby/auto.sh" >> ~/.zshrc
#          echo "chruby ruby-3.1.3" >> ~/.zshrc # run 'chruby' to see actual version
#        tags:
#          - "blog-service-install"
#          - "zshrc-use-chruby"
#          - "operator"
#      - name: "Show ruby version"
#        shell: |
#          source ~/.zshrc;
#          ruby -v
#        tags:
#          - "d1d2-blog-service-install"
#          - "show-ruby-version"
#          - "operator"
#      - name: "gem install jekyll"
#        shell: |
#          source ~/.zshrc;
#          gem install jekyll
#        tags:
#          - "blog-service-install"
#          - "gem-install-jekyll"
#          - "operator"
#      # Install the jekyll and bundler gems.
#      - name: "gem install jekyll bundler"
#        shell: |
#          source ~/.zshrc;
#          gem install jekyll bundler
#        tags:
#          - "blog-service-install"
#          - "gem-install-jekyll-bundler"
#          - "operator"
#      - name: "Create Jekyll blog working directory"
#        file:
#          path: "../roles/requirements/tasks/documentations/blog"
#          state: absent
#        tags:
#          - "blog-service-install"
#          - "create-new-jekyll-site-directory"
#          - "operator"
#      - name: "Create Jekyll blog working directory"
#        file:
#          path: "../roles/requirements/tasks/documentations/blog"
#          state: directory
#          mode: 0755
#        tags:
#          - "blog-service-install"
#          - "create-new-jekyll-site-directory"
#          - "operator"
#      - name: "Initialize Jekyll site"
#        shell: |
#          source ~/.zshrc;
#          jekyll new --force jannah-operator
#        args:
#          chdir: "../roles/requirements/tasks/documentations/blog"
#        tags:
#          - "blog-service-install"
#          - "jekyll-new-jannah-operator"
#          - "operator"

      - name: "Remove welcome-to-jekyll.markdown"
        shell: |
          rm *welcome-to-jekyll.markdown;
          exit 0;
        args:
          chdir: "../roles/requirements/tasks/documentations/blog/jannah-operator/_posts"
        tags:
          - "blog-service-install"
          - "jekyll-new-jannah-operator"
          - "operator"

      - name: "Generate blog/jannah-operator/_config.yml"
        template:
          src: "files/templates/blog/jannah-operator/_config.yml"
          dest: "../roles/requirements/tasks/documentations/blog/jannah-operator/_config.yml"
          backup: yes
        tags:
          - "blog-service-install"
          - "generate-site-config"
          - "operator"
      - name: "Generate blog/jannah-operator/about.markdown"
        template:
          src: "files/templates/blog/jannah-operator/about.markdown"
          dest: "../roles/requirements/tasks/documentations/blog/jannah-operator/about.markdown"
          backup: yes
        tags:
          - "blog-service-install"
          - "generate-about-markdown"
          - "operator"
      - name: "Generate blog/jannah-operator/404.html"
        template:
          src: "files/templates/blog/jannah-operator/404.html"
          dest: "../roles/requirements/tasks/documentations/blog/jannah-operator/404.html"
          backup: yes
        tags:
          - "blog-service-install"
          - "generate-404-markdown"
          - "operator"
      - name: Import documentations/blog/jannah-operator/posts tasks
        include_tasks: '{{ posts_item }}'
        with_fileglob:
          - posts/main.yml
        loop_control:
          loop_var: posts_item
        tags:
          - "generate-blog-posts"
          - "blog-service-install"
          - "operator"
      - name: Import documentations/blog/jannah-operator/pages tasks
        include_tasks: '{{ pages_item }}'
        with_fileglob:
          - pages/main.yml
        loop_control:
          loop_var: pages_item
        tags:
          - "generate-blog-pages"
          - "blog-service-install"
          - "operator"
      - name: "Synchronize and delete files between blog/jannah-operator/ and /docs/."
        ansible.posix.synchronize:
          src: "../roles/requirements/tasks/documentations/blog/jannah-operator/"
          dest: "{{ provisioner.inventory.group_vars.all.Jannah.global.ansible.working_dir }}/docs/"
          recursive: true
        tags:
          - "generate-blog-pages"
          - "blog-service-install"
          - "operator"
    rescue:
      - name: "Install Jekyll Blog Infra Exception"
        ansible.builtin.debug:
          msg: 'Install Jekyll Blog Infra Exception'
        register: debug_install_jekyll_blog
      - name: Re-emit failure
        vars:
          failed_task:
            result: '{{ ansible_failed_result }}'
        fail:
          msg: '{{ failed_task }}'
    #become: true
    ignore_errors: false
