---
- name: "Cleanup Jannah Environment Tasks"
  block:
    - name: "set_fact jannah_stages_bootstrap_deploy_destination"
      ansible.builtin.set_fact:
        jannah_stages_bootstrap_deploy_destination: "{{ Jannah.stages.bootstrap.deploy.destination }}"
      tags:
        - "molecule_cleanup"
        - "operator_e2e"
        - "cleanup_images"
    - name: "set_fact jannah_stages_bootstrap_deploy_mode"
      ansible.builtin.set_fact:
        jannah_stages_bootstrap_deploy_mode: "{{ Jannah.stages.bootstrap.deploy.mode }}"
      tags:
        - "molecule_cleanup"
        - "operator_e2e"
        - "cleanup_images"
    - name: "Create backup within work directory"
      file:
        path: "{{ Jannah.global.ansible.working_dir }}/backup"
        state: directory
        mode: 0755
      tags:
        - "molecule_cleanup"
        - "operator_e2e"
        - "cleanup_images"  
    - name: "Create backup within /tmp directory"
      file:
        path: "/tmp/Jannah_Working_dir_Backup"
        state: directory
        mode: 0755
      tags:
        - "molecule_cleanup"
        - "operator_e2e"
        - "cleanup_images"
    - name: "Backup to working_dir/backup"
      ansible.posix.synchronize:
        src: "{{ Jannah.global.ansible.working_dir }}/tmp"
        dest: "{{ Jannah.global.ansible.working_dir }}/backup" 
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=*node_modules/*"
        recursive: true
        times: true
        delay_updates: true
    - name: "Backup to /tmp/Jannah_Working_dir_Backup"
      ansible.posix.synchronize:
        src: "{{ Jannah.global.ansible.working_dir }}/tmp"
        dest: "/tmp/Jannah_Working_dir_Backup" 
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=*node_modules/*"
        recursive: true
        times: true
        delay_updates: true
    - name: "Import cleanup registry,secrets tasks - Darwin"
      include_tasks: '{{ prepare_registry_secrete_task_items }}'
      with_fileglob:
        - clusters/secrets/main.yl
        - clusters/registry/main.yml
      loop_control:
        loop_var: prepare_registry_secrete_task_items
      when: (
              ansible_facts['os_family'] == "Darwin" and 
              (
                jannah_stages_bootstrap_deploy_destination == "docker-desktop"
                or 
                jannah_stages_bootstrap_deploy_destination == "kind"
              )
              and 
              jannah_stages_bootstrap_deploy_mode == "dev"
            )
      tags:
        - "molecule_cleanup"
        - "operator_e2e"
        - "cleanup_images"
    - name: "Import cleanup tasks - Darwin"
      include_tasks: '{{ cleanup_task_darwin_items }}'
      with_fileglob:
        - prepared_artifacts/main.yml
        - clusters/kind/main.yml
        - clusters/docker_desktop/main.yml
      loop_control:
        loop_var: cleanup_task_darwin_items
      when: ansible_facts['os_family'] == "Darwin"
      tags:
        - "molecule_cleanup"
        - "operator_e2e"
        - "cleanup_images"
        - "stop_frontend_images"
        - "docker_desktop_infra"
  rescue:
    - name: "Cleanup Jannah Tasks Exception"
      ansible.builtin.debug:
        msg: 'Cleanup Jannah Tasks Exception'
      tags:
        - "molecule_cleanup"
        - "operator_e2e"
        - "cleanup_images"
        - "stop_frontend_images"
    - name: "Print return information from the previous task"
      ansible.builtin.debug:
        var: ansible_facts['architecture']
      tags:
        - "molecule_cleanup"
        - "operator_e2e"
        - "cleanup_images"
        - "stop_frontend_images"
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "molecule_cleanup"
        - "operator_e2e"
        - "cleanup_images"
        - "stop_frontend_images"
  ignore_errors: false
