---
# Implements
# https://docs.percona.com/percona-operator-for-postgresql/2.0/kubectl.html#procedure
- name: "Deploy Storage Operator to Kind cluster"
  block:
    - name: "set_fact tmp_EPHEMERAL_cr_jannah_stages_bootstrap_deploy_wait_time"
      ansible.builtin.set_fact:
        tmp_EPHEMERAL_cr_jannah_stages_bootstrap_deploy_wait_time: "{{ Jannah.stages.bootstrap.deploy.wait_time }}"
      tags:
        - "molecule_create"
        - "operator_e2e"
        - "molecule_create_debug"
    - name: "Deploy Percona Postgresql Operator CRD - kind cluster"
      environment:
        - KUBECONFIG: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/kind/config"
      shell: |
        kubectl apply --server-side -f \
        {{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/percona-postgresql-operator/deploy/crd.yaml \
        -n "{{ Jannah.stages.bootstrap.deploy.dependencies.parcona_postgres.namespace }}";
      tags:
        - "molecule_create"
        - "operator_e2e"
        - "molecule_create_debug_1"
    - name: "Deploy Percona Distribution for PostgreSQL cluster rbac - docker-desktop"
      environment:
        - KUBECONFIG: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/kind/config"
      shell: |
        kubectl apply -f \
        {{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/percona-postgresql-operator/deploy/rbac.yaml \
        -n "{{ Jannah.stages.bootstrap.deploy.dependencies.parcona_postgres.namespace }}";
      tags:
        - "molecule_create"
        - "operator_e2e"
        - "molecule_create_debug"       
    - name: "Deploy Percona Distribution for PostgreSQL operator - kind-cluster"
      environment:
        - KUBECONFIG: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/kind/config"
      shell: |
        kubectl apply -f \
        {{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/percona-postgresql-operator/deploy/operator.yaml \
        -n "{{ Jannah.stages.bootstrap.deploy.dependencies.parcona_postgres.namespace }}";
      tags:
        - "molecule_create"
        - "operator_e2e"
        - "molecule_create_debug_1"
    - name: "Deploy Percona Postgresql Operator CR - kind-cluster - wait for crd/perconapgclusters.pgv2.percona.com"
      environment:
        - KUBECONFIG: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/kind/config"
      shell: |
        kubectl wait --for=condition=Established=True --timeout=60s crd/perconapgclusters.pgv2.percona.com;
      tags:
        - "molecule_create"
        - "operator_e2e"
        - "molecule_create_debug_1"
    - name: "Wait for Create tmp/EPHEMERAL/cr directory - docker-desktop"
      shell: |
        sleep "{{ Jannah.stages.bootstrap.deploy.wait_time }}";
      when: tmp_EPHEMERAL_cr_jannah_stages_bootstrap_deploy_wait_time | int != 0
      tags:
        - "molecule_create"
        - "operator_e2e"
        - "molecule_create_debug"
    - name: "Apply update postgres for with custom user and database - kind"
      environment:
        - KUBECONFIG: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/kind/config"
      shell: |
        kubectl apply -f \
        {{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/percona-postgresql-operator/deploy/cr.yaml \
        -n "{{ Jannah.stages.bootstrap.deploy.dependencies.parcona_postgres.namespace }}";
      tags:
        - "molecule_create"
        - "operator_e2e"
        - "molecule_create_debug"  
  rescue:
    - name: "Deploy Storage Operator to Kind cluster Exception"
      ansible.builtin.debug:
        msg: 'Deploy Storage Operator to Kind cluster Exception'
      tags:
        - "deploy_storage"
        - "molecule_create"
        - "operator_e2e"
        - "molecule_create_debug_1"
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "deploy_storage"
        - "molecule_create"
        - "operator_e2e"
        - "molecule_create_debug_1"
  ignore_errors: false
