---
- name: "Builds streamos docker images for use in Helm Chart"
  block:
    - name: "Create images/streamos directory"
      file:
        path: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/streamos"
        state: directory
        mode: 0755
      tags:
        - "build_images"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "Generate images/streamos/streamos.Dockerfile"
      template:
        src: "files/templates/streamos/streamos.Dockerfile"
        dest: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/streamos/streamos.Dockerfile"
      tags:
        - "build_images"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "Generate project/streamos.Dockerfile"
      template:
        src: "files/templates/streamos/streamos.Dockerfile"
        dest: "{{ Jannah.global.ansible.working_dir }}/streamos.Dockerfile"
      tags:
        - "build_images"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "Generate streamos/streamos.Dockerfile.dockerignore"
      template:
        src: "files/templates/streamos/streamos.Dockerfile.dockerignore"
        dest: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/streamos/streamos.Dockerfile.dockerignore"
      tags:
        - "build_images"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "Generate project/streamos.Dockerfile.dockerignore"
      template:
        src: "files/templates/streamos/streamos.Dockerfile.dockerignore"
        dest: "{{ Jannah.global.ansible.working_dir }}/streamos.Dockerfile.dockerignore"
      tags:
        - "build_images"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "Import prepare build image tasks - streamos middleware and frontend"
      include_tasks: '{{ prepare_streamos_middleware_and_frontend_task_items }}'
      with_fileglob:
        - build_streamos_middleware_images.yml
        - build_streamos_frontend_images.yml
      loop_control:
        loop_var: prepare_streamos_middleware_and_frontend_task_items
      tags:
        - "docker_desktop_infra"
        - "molecule_prepare"
        - "operator_e2e"
  rescue:
    - name: "Builds and StreamOs Docker Images Exception"
      ansible.builtin.debug:
        msg: 'Builds StreamOs Docker Images Exception'
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "build_images"
        - "build_streamos_images"
        - "molecule_prepare"
        - "operator_e2e"
  ignore_errors: false
