---
- name: "Tag and Push streamos middleware docker images for use in Helm Chart"
  block:
    - name: "Tag StreamOs middleware image - arm64"
      shell: |
        docker tag \
          {{ Jannah.stages.bootstrap.deploy.helm_values.images.middleware.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.arm }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.streamos }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }} \
          {{ Jannah.stages.bootstrap.deploy.helm_values.common.repository }}/{{ Jannah.stages.bootstrap.deploy.helm_values.images.middleware.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.arm }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.streamos }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }};
      when: (
              ansible_facts['architecture'] != "x86_64" 
            )
      async: 9800
      poll: 5
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/streamos/middleware/jannah_graphql"
      tags:
        - "build_images"
        - "molecule_create"
        - "operator_e2e"
    - name: "Push StreamOs middleware image - arm64"
      shell: |
        docker push \
          {{ Jannah.stages.bootstrap.deploy.helm_values.common.repository }}/{{ Jannah.stages.bootstrap.deploy.helm_values.images.middleware.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.arm }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.streamos }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }};
      when: (
              ansible_facts['architecture'] != "x86_64" 
            )
      async: 9800
      poll: 5
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/streamos/middleware/jannah_graphql"
      tags:
        - "build_images"
        - "molecule_create"
        - "operator_e2e"
    - name: "Tag StreamOs middleware image - amd64"
      shell: |
        docker tag \
          {{ Jannah.stages.bootstrap.deploy.helm_values.images.middleware.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.amd }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.streamos }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }} \
          {{ Jannah.stages.bootstrap.deploy.helm_values.common.repository }}/{{{ Jannah.stages.bootstrap.deploy.helm_values.images.middleware.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.amd }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.streamos }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }} \;
      when: (
              ansible_facts['architecture'] == "x86_64" 
            )
      async: 9800
      poll: 5
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/streamos/middleware/jannah_graphql"
      tags:
        - "build_images"
        - "molecule_create"
        - "operator_e2e"
    - name: "Push StreamOs middleware image - amd64"
      shell: |
        docker push \
          {{ Jannah.stages.bootstrap.deploy.helm_values.common.repository }}/{{{ Jannah.stages.bootstrap.deploy.helm_values.images.middleware.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.amd }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.streamos }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }} \;
      when: (
              ansible_facts['architecture'] == "x86_64" 
            )
      async: 9800
      poll: 5
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/streamos/middleware/jannah_graphql"
      tags:
        - "build_images"
        - "molecule_create"
        - "operator_e2e"
  rescue:
    - name: "Builds StreamOs Middleware Docker Images Exception"
      ansible.builtin.debug:
        msg: 'Builds StreamOs Middleware Docker Images Exception'
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "build_images"
        - "build_ubuntu_images"
        - "molecule_create"
        - "operator_e2e"
  ignore_errors: false
