---
- name: "Builds ubuntu middleware docker images for use in Helm Chart"
  block:
    - name: "set_fact jannah_stages_bootstrap_deploy_os"
      ansible.builtin.set_fact:
        jannah_stages_bootstrap_deploy_os: "{{ Jannah.stages.bootstrap.deploy.os }}"
      tags:
        - "build_images"
        - "build_frontend_images"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "Create /images/ubuntu/middleware directory"
      file:
        path: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/ubuntu/middleware"
        state: directory
        mode: 0755
      tags:
        - "build_images"
        - "build_middleware_images"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "Git checkout https://github.com/jannahio/middleware.git"
      ansible.builtin.git:
        repo: "https://github.com/jannahio/middleware.git"
        dest: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/ubuntu/middleware"
        version: "task-aVYVi17T-base-jannah-django-app-model.login_jannah.graphql.cursor_addendum"
      tags:
        - "build_images"
        - "build_middleware_images"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "Generate middleware/ubuntu.middleware.Dockerfile"
      template:
        src: "files/templates/ubuntu/middleware/ubuntu.middleware.Dockerfile"
        dest: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/ubuntu/middleware/jannah_graphql/ubuntu.middleware.Dockerfile"
      tags:
        - "build_images"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "Generate ubuntu/ubuntu.middleware.Dockerfile.dockerignore"
      template:
        src: "files/templates/ubuntu/middleware/ubuntu.middleware.Dockerfile.dockerignore"
        dest: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/ubuntu/middleware/jannah_graphql/ubuntu.middleware.Dockerfile.dockerignore"
      tags:
        - "build_images"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "Build Ubuntu middleware image - arm64"
      shell: |
        docker buildx build \
          --builder=kube \
          -t \
          {{ Jannah.stages.bootstrap.deploy.helm_values.images.middleware.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.arm }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.ubuntu }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }} \
          --platform=linux/arm64 \
          -f ubuntu.middleware.Dockerfile \
          --load .
      when: ansible_facts['architecture'] != "x86_64" and jannah_stages_bootstrap_deploy_os == "ubuntu"
      async: 9800
      poll: 5
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/ubuntu/middleware/jannah_graphql"
      tags:
        - "build_images"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "Build Ubuntu middleware image - amd64"
      shell: |
        docker buildx build \
          --builder=kube \
          -t \
          {{ Jannah.stages.bootstrap.deploy.helm_values.images.middleware.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.amd }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.ubuntu }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }} \
          --platform=linux/amd64 \
          -f ubuntu.middleware.Dockerfile \
          --load .
      when: ansible_facts['architecture'] == "x86_64" and jannah_stages_bootstrap_deploy_os = "ubuntu"
      async: 9800
      poll: 5
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/ubuntu/middleware/jannah_graphql"
      tags:
        - "build_images"
        - "molecule_prepare"
        - "operator_e2e"
  rescue:
    - name: "Builds Ubuntu Middleware Docker Images Exception"
      ansible.builtin.debug:
        msg: 'Builds Ubuntu Middleware Docker Images Exception'
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "build_images"
        - "build_ubuntu_images"
        - "molecule_prepare"
        - "operator_e2e"
  ignore_errors: false
