---
- name: "Prepare Phase for Jannah Deployment Tasks"
  block:
    - name: "set_fact jannah_stages_bootstrap_deploy_os"
      ansible.builtin.set_fact:
        jannah_stages_bootstrap_deploy_os: "{{ Jannah.stages.bootstrap.deploy.os }}"
      tags:
        - "prepare_images"
        - "molecule_prepare"
        - "operator_e2e"
        - "molecule_prepare_debug"
    - name: "set_fact jannah_stages_bootstrap_deploy_type"
      ansible.builtin.set_fact:
        jannah_stages_bootstrap_deploy_type: "{{ Jannah.stages.bootstrap.deploy.type }}"
      tags:
        - "prepare_images"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "set_fact jannah_stages_bootstrap_deploy_destination"
      ansible.builtin.set_fact:
        jannah_stages_bootstrap_deploy_destination: "{{ Jannah.stages.bootstrap.deploy.destination }}"
      tags:
        - "prepare_images"
        - "molecule_prepare"
        - "operator_e2e"
        - "molecule_prepare_debug"
    - name: "kind export  and set kubeconfig to kind/config"
      environment:
        KUBECONFIG: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/kind/config"
      shell: |
        kind export kubeconfig --name {{ Jannah.stages.bootstrap.deploy.kind.name }}
      when: jannah_stages_bootstrap_deploy_destination == "kind"
      args:
        chdir: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/kind/"
      async: 600
      poll: 5
      tags:
        - "prepare_images"
        - "molecule_prepare"
        - "operator_e2e"
        - "molecule_prepare_debug"
    - name: "Import prepare  docker desktop tasks - Darwin"
      include_tasks: '{{ prepare_macos_docker_desktop_task_items }}'
      with_fileglob:
        - clusters/main.yml
      loop_control:
        loop_var: prepare_macos_docker_desktop_task_items
      when: (
              ansible_facts['os_family'] == "Darwin"
              and
              jannah_stages_bootstrap_deploy_destination == "docker-desktop"
              or 
              jannah_stages_bootstrap_deploy_destination == "kind"
            )
      tags:
        - "prepare_images"
        - "molecule_prepare"
        - "molecule_prepare_debug"
        - "operator_e2e"
    - name: "Import create tasks - Darwin"
      include_tasks: '{{ prepare_build_artifact_darwin_items }}'
      with_fileglob:
        - prepared_artifacts/main.yml
      loop_control:
        loop_var: prepare_build_artifact_darwin_items
      tags:
        - "prepare_images"
        - "molecule_prepare"
        - "operator_e2e"
  rescue:
    - name: "Prepare Jannah Tasks Exception"
      ansible.builtin.debug:
        msg: 'Prepare Jannah Tasks Exception'
      register: prepare_jannah_tasks_debug_resources
      tags:
        - "prepare_images"
        - "molecule_prepare"
        - "operator_e2e"
    - debug: var=prepare_jannah_tasks_debug_resources
      tags:
        - "prepare_images"
        - "molecule_prepare"
        - "operator_e2e"
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "prepare_images"
        - "molecule_prepare"
        - "operator_e2e"
  ignore_errors: false
