---
- name: "Kubernetes Kind tooling - exec"
  block:
    - name: "Install kind 0.18.0"
      shell: |
        go install sigs.k8s.io/kind@v0.18.0;
      when: ansible_facts['os_family'] == "Debian"
      async: 600
      poll: 5
      tags:
        - "molecule_create"
        - "operator_e2e"
  rescue:
    - name: "Kubernetes Kind Tooling Exception"
      ansible.builtin.debug:
        msg: 'Kubernetes Kind Tooling Exception'
      register: molecule_create_inline_debug_resources
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
  ignore_errors: false
