---
- name: "Kubernetes Kind cluster tooling"
  block:
    - name: "Install kind 0.18.0 - Darwin(arm64)"
      shell: |
        brew install kind;
      when: ansible_facts['os_family'] == "Darwin"
      async: 600
      poll: 5
      tags:
        - "molecule_create"
        - "operator_e2e"
        - "debug_task"
    - name: "Create MOLECULE_EPHEMERAL_DIRECTORY/kind directory"
      file:
        path: "${MOLECULE_EPHEMERAL_DIRECTORY}/kind/"
        state: directory
        mode: 0755
      tags:
        - "molecule_create"
        - "operator_e2e"
        - "debug_task"
    - name: "Generate kind_config_arm64.yml"
      template:
        src: "files/templates/kind_config_arm64.yml"
        dest: "${MOLECULE_EPHEMERAL_DIRECTORY}/kind/kind_config_arm64.yml"
        backup: yes
      when: ansible_facts['os_family'] == "Darwin" and ansible_facts['architecture'] == "arm64"
      tags:
        - "molecule_create"
        - "operator_e2e"
        - "debug_task"
    - name: "Generate kind_config_amd64.yml"
      template:
        src: "files/templates/kind_config_amd64.yml"
        dest: "${MOLECULE_EPHEMERAL_DIRECTORY}/kind/kind_config_amd64.yml"
        backup: yes
      when: ansible_facts['os_family'] == "Darwin" and ansible_facts['architecture'] != "arm64"
      tags:
        - "molecule_create"
        - "operator_e2e"
        - "debug_task"
#    kind create cluster --name "{{ Jannah.stages.bootstrap.build.vm.name }}-kind" \
#    --config=kind_config.yml -v 100 --wait {{ Jannah.stages.bootstrap.build.vm.kind.wait }};
    - name: "Create cluster - Darwin(arm64)"
      environment:
        KUBECONFIG: "${MOLECULE_EPHEMERAL_DIRECTORY}/kind/config"
      shell: |
        kind create cluster --name "{{ Jannah.stages.bootstrap.deploy.kind.name }}" \
        --config "${MOLECULE_EPHEMERAL_DIRECTORY}/kind/kind_config_arm64.yml" \
        -v 100 --wait {{ Jannah.stages.bootstrap.deploy.kind.wait }};
      when: ansible_facts['os_family'] == "Darwin" and ansible_facts['architecture'] == "arm64"
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/kind/"
      async: 1200
      poll: 15
      tags:
        - "molecule_create"
        - "operator_e2e"
        - "debug_task"
    - name: "Create cluster - Darwin(amd64)"
      environment:
        KUBECONFIG: "${MOLECULE_EPHEMERAL_DIRECTORY}/kind/config"
      shell: |
        kind create cluster --name "{{ Jannah.stages.bootstrap.deploy.kind.name }}" \
        --config "${MOLECULE_EPHEMERAL_DIRECTORY}/kind/kind_config_amd64.yml" \
        -v 100 --wait {{ Jannah.stages.bootstrap.deploy.kind.wait }};
      when: ansible_facts['os_family'] == "Darwin" and ansible_facts['architecture'] != "arm64"
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/kind/"
      async: 1200
      poll: 15
      tags:
        - "molecule_create"
        - "operator_e2e"
        - "debug_task"
    - name: "Create cluster - Darwin(amd64)"
      environment:
        KUBECONFIG: "${MOLECULE_EPHEMERAL_DIRECTORY}/kind/config"
      shell: |
        kind export kubeconfig --name {{ Jannah.stages.bootstrap.deploy.kind.name }}
      when: ansible_facts['os_family'] == "Darwin"
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/kind/"
      async: 600
      poll: 5
      tags:
        - "molecule_create"
        - "operator_e2e"
        - "debug_task"
    - name: "kubectl get pods -A"
      environment:
        KUBECONFIG: "${MOLECULE_EPHEMERAL_DIRECTORY}/kind/config"
      shell: |
        kubectl get pods -A
      when: ansible_facts['os_family'] == "Darwin"
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/kind/"
      async: 600
      poll: 5
      tags:
        - "molecule_create"
        - "operator_e2e"
        - "debug_task"
  rescue:
    - name: "Kubernetes Kind Tooling Exception"
      ansible.builtin.debug:
        msg: 'Kubernetes Kind Tooling Exception'
      register: molecule_create_inline_debug_resources
      tags:
        - "molecule_create"
        - "operator_e2e"
        - "debug_task"
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "molecule_create"
        - "operator_e2e"
        - "debug_task"
        -
  ignore_errors: false
