

---
- name: "Remove Secrets for Jannah Deployment"
  block:
    - name: "set_fact jannah_stages_bootstrap_deploy_destination"
      ansible.builtin.set_fact:
        jannah_stages_bootstrap_deploy_destination: "{{ Jannah.stages.bootstrap.deploy.destination }}"
      tags:
        - "remove_secrets"
        - "molecule_destroy"
        - "operator_e2e"
    # image registry ssl cert
    - name: "Remove TLS Secret - docker-desktop"
      shell: |
        kubectl delete secret t"{{ Jannah.stages.bootstrap.secrets.root_cert.name }}";
        exit 0;
      when: jannah_stages_bootstrap_deploy_destination == "docker-desktop"
      tags:
        - "remove_secrets"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Remove TLS Secret - kind"
      environment:
        KUBECONFIG: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/kind/config"
      shell: |
        kubectl delete secret t"{{ Jannah.stages.bootstrap.secrets.root_cert.name }}";
        exit 0;
      when: jannah_stages_bootstrap_deploy_destination == "kind"
      tags:
        - "remove_secrets"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Remove Generic (Registry Auth) Secret - docker-desktop"
      shell: |
        kubectl create secret "{{ Jannah.stages.bootstrap.secrets.auth.name }}";
        exit 0;
      when: jannah_stages_bootstrap_deploy_destination == "docker-desktop"
      tags:
        - "remove_secrets"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Remove Generic (Registry Auth) Secret - kind"
      environment:
        KUBECONFIG: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/kind/config"
      shell: |
        kubectl create secret "{{ Jannah.stages.bootstrap.secrets.auth.name }}";
        exit 0;
      when: jannah_stages_bootstrap_deploy_destination == "kind"
      tags:
        - "remove_secrets"
        - "molecule_destroy"
        - "operator_e2e" 
    - name: 'Remove Registry Persistent Volume - docker-desktop'
      kubernetes.core.k8s:
        definition:
          apiVersion: "{{ Jannah.stages.bootstrap.deploy.helm_values.persistent_volumes.docker_registry.apiVersion }}"
          kind: "{{ Jannah.stages.bootstrap.deploy.helm_values.persistent_volumes.docker_registry.kind }}"
          metadata:
            name: "{{ Jannah.stages.bootstrap.deploy.helm_values.persistent_volumes.docker_registry.metadata.name }}"
            namespace: "default"
        state: absent
      when: jannah_stages_bootstrap_deploy_destination == "docker-desktop"
      tags:
        - "remove_secrets"
        - "molecule_destroy"
        - "operator_e2e"
    - name: 'Remove Registry Persistent Volume - kind'
      environment:
        KUBECONFIG: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/kind/config"
      kubernetes.core.k8s:
        definition:
          apiVersion: "{{ Jannah.stages.bootstrap.deploy.helm_values.persistent_volumes.docker_registry.apiVersion }}"
          kind: "{{ Jannah.stages.bootstrap.deploy.helm_values.persistent_volumes.docker_registry.kind }}"
          metadata:
            name: "{{ Jannah.stages.bootstrap.deploy.helm_values.persistent_volumes.docker_registry.meta.name }}"
            namespace: "default"
        state: absent
      when: jannah_stages_bootstrap_deploy_destination == "kind"
      tags:
        - "remove_secrets"
        - "molecule_destroy"
        - "operator_e2e"
    - name: 'Remove Registry Persistent Volume Claim - docker-desktop'
      kubernetes.core.k8s:
        definition:
          apiVersion: "{{ Jannah.stages.bootstrap.deploy.helm_values.persistent_volume_claims.docker_registry.apiVersion }}"
          kind: "{{ Jannah.stages.bootstrap.deploy.helm_values.persistent_volume_claims.docker_registry.kind }}"
          metadata:
            name: "{{ Jannah.stages.bootstrap.deploy.helm_values.persistent_volume_claims.docker_registry.metadata.name }}"
            namespace: default
        state: absent
      when: jannah_stages_bootstrap_deploy_destination == "docker-desktop"
      tags:
        - "remove_secrets"
        - "molecule_destroy"
        - "operator_e2e"
    - name: 'Remove Registry Persistent Volume Claim - kind'
      environment:
        KUBECONFIG: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/kind/config"
      kubernetes.core.k8s:
        definition:
          apiVersion: "{{ Jannah.stages.bootstrap.deploy.helm_values.persistent_volume_claims.docker_registry.apiVersion }}"
          kind: "{{ Jannah.stages.bootstrap.deploy.helm_values.persistent_volume_claims.docker_registry.kind }}"
          metadata:
            name: "{{ Jannah.stages.bootstrap.deploy.helm_values.persistent_volume_claims.docker_registry.metadata.name }}"
            namespace: default
        state: absent
      when: jannah_stages_bootstrap_deploy_destination == "kind"
      tags:
        - "remove_secrets"
        - "molecule_destroy"
        - "operator_e2e"
    - name: 'Remove Registry Pod - docker-desktop'
      kubernetes.core.k8s:
        definition:
          aapiVersion: v1
          kind: Pod
          metadata:
            name:  "{{ Jannah.stages.bootstrap.deploy.helm_values.pods.registry_pod.name }}"
            labels:
            app: "{{ Jannah.stages.bootstrap.deploy.helm_values.images.registry.name }}"
            namespace: default
        state: absent
      when: jannah_stages_bootstrap_deploy_destination == "docker-desktop"
      tags:
        - "remove_secrets"
        - "molecule_destroy"
        - "operator_e2e"
    - name: 'Remove Registry Pod - kind'
      environment:
        KUBECONFIG: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/kind/config"
      kubernetes.core.k8s:
        definition:
          aapiVersion: v1
          kind: Pod
          metadata:
            name:  "{{ Jannah.stages.bootstrap.deploy.helm_values.pods.registry_pod.name }}"
            labels:
            app: "{{ Jannah.stages.bootstrap.deploy.helm_values.images.registry.name }}"
            namespace: default
        state: absent
      when: jannah_stages_bootstrap_deploy_destination == "kind"
      tags:
        - "remove_secrets"
        - "molecule_destroy"
        - "operator_e2e"
    - name: 'Remove Registry Service - docker-desktop' 
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "{{ Jannah.stages.bootstrap.deploy.helm_values.images.registry.name }}"
            namespace: default
          spec:
            selector:
              app: "{{ Jannah.stages.bootstrap.deploy.helm_values.images.registry.name }}"
        state: absent
      when: jannah_stages_bootstrap_deploy_destination == "docker-desktop"
      tags:
        - "remove_secrets"
        - "molecule_destroy"
        - "operator_e2e"
    - name: 'Remove Registry Service - kind'
      environment:
        KUBECONFIG: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/kind/config" 
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "{{ Jannah.stages.bootstrap.deploy.helm_values.images.registry.name }}"
            namespace: default
          spec:
            selector:
              app: "{{ Jannah.stages.bootstrap.deploy.helm_values.images.registry.name }}"
        state: absent
      when: jannah_stages_bootstrap_deploy_destination == "kind"
      tags:
        - "remove_secrets"
        - "molecule_destroy"
        - "operator_e2e"
     # image registry automated image pull cred
    - name: "Remove registry creds - docker-desktop"
      shell: |
        kubectl delete \
        secret \
        "{{ Jannah.stages.bootstrap.secrets.registry_cred.name }}"
      when: jannah_stages_bootstrap_deploy_destination == "docker-desktop"
      tags:
        - "remove_secrets"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Remove registry creds - kind"
      environment:
        KUBECONFIG: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/kind/config"
      shell: |
        kubectl delete \
        secret \
        "{{ Jannah.stages.bootstrap.secrets.registry_cred.name }}"
      when: jannah_stages_bootstrap_deploy_destination == "kind"
      tags:
        - "remove_secrets"
        - "molecule_destroy"
        - "operator_e2e"
    # - name: "docker rm -f registry:2.6.2"
    #   shell: |
    #     docker rm -f registry:2.6.2;
    #     exit 0;
    #   tags:
    #     - "deploy_images"
    #     - "molecule_prepare"
    #     - "operator_e2e"
  rescue:
    - name: "Remove Secrets for Jannah Exception"
      ansible.builtin.debug:
        msg: "Remove Secrets for Jannah Exception"
      register: remove_jannah_tasks_debug_resources
      tags:
        - "remove_secrets"
        - "molecule_destroy"
        - "operator_e2e"
    - debug: var=remove_jannah_tasks_debug_resources
      tags:
        - "remove_secrets"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Re-emit failure"
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "remove_secrets"
        - "molecule_destroy"
        - "operator_e2e"
  ignore_errors: false
