kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  FeatureGateName: true
nodes:
  - role: control-plane
    image: {{ Jannah.stages.bootstrap.deploy.kind.nodes.arm64.image }}
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        listenAddress: "0.0.0.0"
        protocol: tcp
    extraMounts:
      - hostPath: {{ Jannah.global.ansible.working_dir }}
        containerPath: /jannah/operator
    labels:
      kubernetes.io/arch: arm64
  - role: worker
    image: {{ Jannah.stages.bootstrap.deploy.kind.nodes.arm64.image }}
    labels:
      kubernetes.io/arch: {{ Jannah.stages.bootstrap.deploy.kind.nodes.arm64.arch }}
  - role: worker
    image: {{ Jannah.stages.bootstrap.deploy.kind.nodes.amd64.image }}
    labels:
      kubernetes.io/arch: {{ Jannah.stages.bootstrap.deploy.kind.nodes.amd64.arch }}