---
# Implements:
# https://juju.is/docs/sdk/set-up-your-development-environment
- name: "block for  jannah deployment tasks - exec"
  block:
    - name: "Deploy operator - exec juju"
      shell: |
        multipass exec {{ Jannah.stages.bootstrap.build.vm.name }} \
        -- juju deploy --debug=true --logging-config=true  --show-log=true \
        --verbose=true \
        --model={{ Jannah.stages.bootstrap.build.juju.controller.name }}:{{ Jannah.stages.bootstrap.build.juju.model.name }} \
        ./jannah-operator_ubuntu-22.04-amd64-arm64.charm \
        jannah-operator \
        --resource ubuntu=jujusolutions/jujud-operator:2.9.42 \
        --resource demoserver=ghcr.io/beliaev-maksim/api_demo_server:0.0.9;
        exit 0
      async: 1600
      poll: 15
      tags:
        - "deploy_jannah"
        - "molecule_converge"
        - "operator_e2e"

    - name: "kubectl get pods -A"
      shell: |
        multipass exec {{ Jannah.stages.bootstrap.build.vm.name }} \
        -- kubectl get pods -A
        exit 0;
      async: 600
      poll: 5
      tags:
        - "deploy_jannah"
        - "molecule_converge"
        - "operator_e2e"
  rescue:
    - name: "Multipass Infra Exception"
      ansible.builtin.debug:
        msg: 'Multipass Infra Exception'
      register: multipass_infra_debug_resources
    - debug: var=multipass_infra_debug_resources
      tags:
        - "deploy_jannah"
        - "molecule_converge"
        - "operator_e2e"
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "deploy_jannah"
        - "molecule_converge"
        - "operator_e2e"
  ignore_errors: false
