- name: "Deploy Jannah dev environment"
  block:
    - name: "node --version - exec"
      shell: |
        multipass exec {{ Jannah.stages.bootstrap.build.vm.name }} \
        -- node --version;
      async: 1600
      poll: 15
      tags:
        - "deploy_dependencies"
        - "molecule_converge"
        - "operator_e2e"
  rescue:
    - name: "Deploy Jannah Development Exception"
      ansible.builtin.debug:
        msg: 'Deploy Jannah Development Exception'
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
  ignore_errors: false
