---
# Use the 'create api' subcommand to add watches to this file.
- version: v1alpha1
  group: jannah.jannah.io
  kind: Jannah
  playbook: jannah
  reconcilePeriod: 10s
  snakeCaseParameters: false
  vars:
    ANSIBLE_VERBOSITY_JANNAH_JANNAH_JANNAH_IO: 5
    ANSIBLE_DEBUG_LOGS: true
    ANSIBLE_DEBUG: true

#+kubebuilder:scaffold:watch
