---
# Implements https://jekyllrb.com/docs/
# https://mac.install.guide/ruby/13.html
  - name: "Day 1, Day 2 Documentation Tasks for the Local Development Ansible Host"
    block:
      # Install all prerequisites.
      - name: "brew install chruby ruby-install"
        shell: |
          brew install chruby ruby-install
        tags:
          - "d1d2-blog-service-install"
          - "d1d2-install-chruby-ruby-install"
          - "d1d2-operator"
          - "molecule-notest"
          - "never"
      - name: "ruby-install ruby - This will take a few minutes"
        shell: |
          ruby-install ruby
        tags:
          - "d1d2-blog-service-install"
          - "d1d2-install-ruby-install ruby"
          - "d1d2-operator"
          - "molecule-notest"
          - "never"
      - name: "gem install jekyll"
        shell: |
          gem install jekyll
        tags:
          - "d1d2-blog-service-install"
          - "d1d2-gem-install-jekyll"
          - "d1d2-operator"
          - "molecule-notest"
          - "never"
      # Install the jekyll and bundler gems.
      - name: "gem install jekyll bundler"
        shell: |
          gem install jekyll bundler
        tags:
          - "d1d2-blog-service-install"
          - "d1d2-gem-install-jekyll"
          - "d1d2-operator"
          - "molecule-notest"
          - "never"

      - name: "Create Jekyll blog working directory"
        file:
          path: "roles/jannahio.day1day2/tasks/documentations/blog"
          state: directory
          mode: 0755
        tags:
          - "d1d2-blog-service-install"
          - "d1d2-create-new-jekyll-site"
          - "d1d2-operator"
          - "molecule-notest"
          - "never"

      - name: "Initialize Jekyll site"
        shell: |
          jekyll new jannah-operator
        args:
          chdir: "roles/jannahio.day1day2/tasks/documentations/blog"
        tags:
          - "d1d2-blog-service-install"
          - "d1d2-jekyll-new-jannah-operator"
          - "d1d2-operator"
          - "molecule-notest"
          - "never"

    rescue:
      - name: "D1D2 Documentation Exception"
        ansible.builtin.debug:
          msg: 'TODO: do a kubectl describe'
        register: debug_resources
    #become: true
    ignore_errors: false
