---
- name: "Tag and Push streamos boot docker images for use in Helm Chart"
  block:
    - name: "set_fact jannah_stages_bootstrap_deploy_push_boot_image"
      ansible.builtin.set_fact:
        jannah_stages_bootstrap_deploy_destination: "{{ Jannah.stages.bootstrap.deploy.helm_values.images.boot.dockerfiles.push }}"
      tags:
        - "deploy_images"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "Tag boot image arm64/streamos"
      shell: |
        docker tag \
          {{ Jannah.stages.bootstrap.deploy.helm_values.images.boot.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.arm }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.streamos }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }} \
          {{ Jannah.stages.bootstrap.deploy.helm_values.common.repository }}/{ Jannah.stages.bootstrap.deploy.helm_values.images.boot.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.arm }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.streamos }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }};
      when: (
              ansible_facts['architecture'] != "x86_64" 
            )
      async: 9800
      poll: 5
      args:
        chdir: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/images/streamos/frontend/web/JannahIonic/"
      tags:
        - "prepare_images"
        - "build_boot_images"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "Push frontend image arm64/streamos"
      shell: |
        docker push \
          {{ Jannah.stages.bootstrap.deploy.helm_values.common.repository }}/{ Jannah.stages.bootstrap.deploy.helm_values.images.boot.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.arm }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.streamos }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }};
      when: (
              ansible_facts['architecture'] != "x86_64" 
              and
              jannah_stages_bootstrap_deploy_push_boot_image == True
            )
      async: 9800
      poll: 5
      args:
        chdir: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/images/streamos/frontend/web/JannahIonic/"
      tags:
        - "prepare_images"
        - "build_boot_images"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "Tag boot image amd64/streamos"
      shell: |
        docker tag \
          {{ Jannah.stages.bootstrap.deploy.helm_values.images.boot.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.amd }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.streamos }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }} \
          {{ Jannah.stages.bootstrap.deploy.helm_values.common.repository }}/{{ Jannah.stages.bootstrap.deploy.helm_values.images.boot.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.amd }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.streamos }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }};
      when: (
            ansible_facts['architecture'] == "x86_64" 
            )
      async: 9800
      poll: 5
      args:
        chdir: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/images/streamos/frontend/web/JannahIonic/"
      tags:
        - "prepare_images"
        - "build_boot_images"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "Push boot image amd64/streamos"
      shell: |
        docker push \
          {{ Jannah.stages.bootstrap.deploy.helm_values.common.repository }}/{{ Jannah.stages.bootstrap.deploy.helm_values.images.boot.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.amd }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.streamos }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }};
      when: (
            ansible_facts['architecture'] == "x86_64" 
            and
            jannah_stages_bootstrap_deploy_push_boot_image == True
            )
      async: 9800
      poll: 5
      tags:
        - "prepare_images"
        - "build_boot_images"
        - "molecule_prepare"
        - "operator_e2e"
  rescue:
    - name: "Tag and Push Boot Docker Images Exception"
      ansible.builtin.debug:
        msg: "Tag and Push Boot Docker Images Exception"
      tags:
        - "prepare_images"
        - "build_boot_images"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "Re-emit failure"
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "prepare_images"
        - "build_boot_images"
        - "molecule_prepare"
        - "operator_e2e"
  ignore_errors: false
