---
- name: "Tag and Push streamos frontend docker images for use in Helm Chart"
  block:
    - name: "set_fact jannah_stages_bootstrap_deploy_push_frontend_streamos_image"
      ansible.builtin.set_fact:
        jannah_stages_bootstrap_deploy_destination: "{{ Jannah.stages.bootstrap.deploy.helm_values.images.frontend.dockerfiles.push }}"
      tags:
        - "prepare_image"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "set_fact jannah_stages_bootstrap_deploy_destination"
      ansible.builtin.set_fact:
        jannah_stages_bootstrap_deploy_destination: "{{ Jannah.stages.bootstrap.deploy.destination }}"
      tags:
        - "deploy_storage"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "Tag frontend image arm64/streamos"
      shell: |
        docker tag \
          {{ Jannah.stages.bootstrap.deploy.helm_values.images.frontend.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.arm }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.streamos }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }} \
          {{ Jannah.stages.bootstrap.deploy.helm_values.common.repository }}/{ Jannah.stages.bootstrap.deploy.helm_values.images.frontend.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.arm }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.streamos }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }};
      when: (
              ansible_facts['architecture'] != "x86_64" 
            )
      async: 9800
      poll: 5
      tags:
        - "prepare_image"
        - "prepare_frontend_images"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "load frontend image arm64/streamos - kind cluster"
      shell: |
        kind load docker-image  --name "{{ Jannah.stages.bootstrap.deploy.kind.name }}" \
          {{ Jannah.stages.bootstrap.deploy.helm_values.common.repository }}/{ Jannah.stages.bootstrap.deploy.helm_values.images.frontend.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.arm }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.streamos }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }};
      when: (
              ansible_facts['architecture'] != "x86_64" 
              and 
              jannah_stages_bootstrap_deploy_destination == "kind"
            )
      async: 9800
      poll: 5
      tags:
        - "prepare_image"
        - "prepare_frontend_images"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "Push frontend image arm64/streamos"
      shell: |
        docker push \
          {{ Jannah.stages.bootstrap.deploy.helm_values.common.repository }}/{ Jannah.stages.bootstrap.deploy.helm_values.images.frontend.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.arm }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.streamos }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }};
      when: (
              ansible_facts['architecture'] != "x86_64" 
              and 
              jannah_stages_bootstrap_deploy_push_frontend_streamos_image == True
            )
      async: 9800
      poll: 5
      tags:
        - "prepare_image"
        - "prepare_frontend_images"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "Tag frontend image amd64/streamos"
      shell: |
        docker tag \
          {{ Jannah.stages.bootstrap.deploy.helm_values.images.frontend.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.amd }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.streamos }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }} \
          {{ Jannah.stages.bootstrap.deploy.helm_values.common.repository }}/{{ Jannah.stages.bootstrap.deploy.helm_values.images.frontend.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.amd }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.streamos }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }};
      when: (
            ansible_facts['architecture'] == "x86_64" 
            )
      async: 9800
      poll: 5
      tags:
        - "prepare_image"
        - "prepare_frontend_images"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "Push frontend image amd64/streamos - kind cluster"
      shell: |
        kind load docker-image  --name "{{ Jannah.stages.bootstrap.deploy.kind.name }}" \
          {{ Jannah.stages.bootstrap.deploy.helm_values.common.repository }}/{{ Jannah.stages.bootstrap.deploy.helm_values.images.frontend.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.amd }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.streamos }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }};
      when: (
            ansible_facts['architecture'] == "x86_64" 
            and
            jannah_stages_bootstrap_deploy_destination == "kind"
            )
      async: 9800
      poll: 5
      tags:
        - "prepare_image"
        - "prepare_frontend_images"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "Push frontend image amd64/streamos"
      shell: |
        docker push \
          {{ Jannah.stages.bootstrap.deploy.helm_values.common.repository }}/{{ Jannah.stages.bootstrap.deploy.helm_values.images.frontend.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.amd }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.streamos }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }};
      when: (
            ansible_facts['architecture'] == "x86_64" 
            )
      async: 9800
      poll: 5
      tags:
        - "prepare_image"
        - "prepare_frontend_images"
        - "molecule_prepare"
        - "operator_e2e"
  rescue:
    - name: "Tag and Push StreamOs Frontend Docker Images Exception"
      ansible.builtin.debug:
        msg: "Tag and Push StreamOs Frontend Docker Images Exception"
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "prepare_image"
        - "prepare_frontend_images"
        - "build_streamos_images"
        - "molecule_prepare"
        - "operator_e2e"
  ignore_errors: false
