---
- name: "Tag and Push ubuntu docker images for use in Helm Chart"
  block:
    - name: "set_fact jannah_stages_bootstrap_deploy_push_boot_ubuntu_image"
      ansible.builtin.set_fact:
        jannah_stages_bootstrap_deploy_destination: "{{ Jannah.stages.bootstrap.deploy.helm_values.images.boot.dockerfiles.push }}"
      tags:
        - "prepare_images"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "Tag Ubuntu boot image - arm64"
      shell: |
        docker tag \
          {{ Jannah.stages.bootstrap.deploy.helm_values.images.middleware.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.arm }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.ubuntu }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }} \
          {{ Jannah.stages.bootstrap.deploy.helm_values.common.repository }}/{{ Jannah.stages.bootstrap.deploy.helm_values.images.middleware.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.arm }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.ubuntu }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }} \;
      when: (
              ansible_facts['architecture'] != "x86_64" 
            )
      async: 9800
      poll: 5
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/ubuntu"
      tags:
        - "prepare_images"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "Push Ubuntu boot image - arm64"
      shell: |
        docker push \
          {{ Jannah.stages.bootstrap.deploy.helm_values.common.repository }}/{{ Jannah.stages.bootstrap.deploy.helm_values.images.middleware.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.arm }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.ubuntu }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }};
      when: (
              ansible_facts['architecture'] != "x86_64"
              and
              jannah_stages_bootstrap_deploy_push_boot_ubuntu_image == True 
            )
      async: 9800
      poll: 5
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/ubuntu"
      tags:
        - "prepare_images"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "Tag Ubuntu boot image - amd64"
      shell: |
        docker tag \
          {{ Jannah.stages.bootstrap.deploy.helm_values.images.boot.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.amd }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.ubuntu }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }} \
          {{ Jannah.stages.bootstrap.deploy.helm_values.common.repository }}/{{ Jannah.stages.bootstrap.deploy.helm_values.images.boot.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.amd }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.ubuntu }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }};
      when: (
              ansible_facts['architecture'] == "x86_64" 
            )
      async: 9800
      poll: 5
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/ubuntu/middleware/jannah_graphql"
      tags:
        - "prepare_images"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "Push Ubuntu boot image - amd64"
      shell: |
        docker push \
          {{ Jannah.stages.bootstrap.deploy.helm_values.common.repository }}/{{ Jannah.stages.bootstrap.deploy.helm_values.images.boot.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.amd }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.ubuntu }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }};
      when: (
              ansible_facts['architecture'] == "x86_64" 
              and
              jannah_stages_bootstrap_deploy_push_boot_ubuntu_image == True
            )
      async: 9800
      poll: 5
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/ubuntu/middleware/jannah_graphql"
      tags:
        - "prepare_images"
        - "molecule_prepare"
        - "operator_e2e"   
    - name: "Import prepare build image tasks - ubuntu middleware and frontend"
      include_tasks: '{{ prepare_ubuntu_middleware_and_frontend_task_items }}'
      with_fileglob:
        - build_ubuntu_middleware_images.yml
        - build_ubuntu_frontend_images.yml
      loop_control:
        loop_var: prepare_ubuntu_middleware_and_frontend_task_items
      tags:
        - "prepare_images"
        - "molecule_prepare"
        - "operator_e2e" 
  rescue:
    - name: "Tag and Push Ubuntu Docker Images Exception"
      ansible.builtin.debug:
        msg: "Tag and Push Ubuntu Docker Images Exception"
      tags:
        - "prepare_images"
        - "prepare_ubuntu_images"
        - "molecule_prepare"
        - "operator_e2e" 
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "prepare_images"
        - "prepare_ubuntu_images"
        - "molecule_prepare"
        - "operator_e2e"
  ignore_errors: false
