---
- name: "Prepare Build Artifact for Jannah Deployment Tasks"
  block:
    - name: "set_fact jannah_stages_bootstrap_deploy_destination"
      ansible.builtin.set_fact:
        jannah_stages_bootstrap_deploy_destination: "{{ Jannah.stages.bootstrap.deploy.destination }}"
      tags:
        - "deploy_images"
        - "molecule_prepare"
        - "operator_e2e"
        - "molecule_prepare_pipeline_images"
    - name: "set_fact jannah_stages_bootstrap_deploy_os"
      ansible.builtin.set_fact:
        jannah_stages_bootstrap_deploy_os: "{{ Jannah.stages.bootstrap.deploy.os }}"
      tags:
        - "deploy_images"
        - "molecule_prepare"
        - "operator_e2e"
        - "molecule_prepare_pipeline_images"
    - name: "Import prepare build_base_image tasks - Darwin"
      include_tasks: '{{ prepare_build_base_image_task_items }}'
      with_fileglob:
        - build_base_image.yml
      loop_control:
        loop_var: prepare_build_base_image_task_items
      when: (
              ansible_facts['os_family'] == "Darwin" 
              and 
              (
                jannah_stages_bootstrap_deploy_destination == "docker-desktop"
                or 
                jannah_stages_bootstrap_deploy_destination == "kind"
              ) 
            )
      tags:
        - "docker_desktop_infra"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "Import prepare build streamos images tasks - StreamOS"
      include_tasks: '{{ prepare_build_streamos_images_task_items }}'
      with_fileglob:
        - build_streamos_images.yml
      loop_control:
        loop_var: prepare_build_streamos_images_task_items
      when: (
            ansible_facts['os_family'] == "Darwin" 
            and 
              (
                jannah_stages_bootstrap_deploy_destination == "docker-desktop"
                or 
                jannah_stages_bootstrap_deploy_destination == "kind"
              )
            and 
            jannah_stages_bootstrap_deploy_os == "streamos"
            )
      tags:
        - "docker_desktop_infra"
        - "molecule_prepare"
        - "operator_e2e"
    - name: "Import prepare build ubuntu images tasks"
      include_tasks: '{{ prepare_build_ubuntu_images_task_items }}'
      with_fileglob:
        - build_ubuntu_images.yml
      loop_control:
        loop_var: prepare_build_ubuntu_images_task_items
      when: (
              ansible_facts['os_family'] == "Darwin" 
              and 
                (
                  jannah_stages_bootstrap_deploy_destination == "docker-desktop"
                  or 
                  jannah_stages_bootstrap_deploy_destination == "kind"
                )
              and 
              jannah_stages_bootstrap_deploy_os == "ubuntu" 
            )
      tags:
        - "docker_desktop_infra"
        - "molecule_prepare"
        - "operator_e2e"
        - "molecule_prepare_debug"
    - name: "Import prepare pipeline images tasks"
      include_tasks: '{{ prepare_pipeline_images_task_items }}'
      with_fileglob:
        - prepare/pipelines/prepare_pipeline_images.yml
      loop_control:
        loop_var: prepare_pipeline_images_task_items
      when: (
              ansible_facts['os_family'] == "Darwin" 
              and 
                (
                  jannah_stages_bootstrap_deploy_destination == "docker-desktop"
                  or 
                  jannah_stages_bootstrap_deploy_destination == "kind"
                )
              and 
              jannah_stages_bootstrap_deploy_os == "ubuntu" 
            )
      tags:
        - "docker_desktop_infra"
        - "molecule_prepare"
        - "operator_e2e"
        - "molecule_prepare_pipeline_images"
  rescue:
    - name: "Prepare Build Artifact for Jannah Deployment Exception"
      ansible.builtin.debug:
        msg: "Prepare Build Artifact for Jannah Deployment Exception"
      register: prepare_jannah_tasks_debug_resources
      tags:
        - "docker_desktop_infra"
        - "molecule_prepare"
        - "operator_e2e"
        - "molecule_prepare_pipeline_images"
    - debug: var=prepare_jannah_tasks_debug_resources
      tags:
        - "docker_desktop_infra"
        - "molecule_prepare"
        - "operator_e2e"
        - "molecule_prepare_pipeline_images"
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "docker_desktop_infra"
        - "molecule_prepare"
        - "operator_e2e"
        - "molecule_prepare_pipeline_images"
  ignore_errors: false
