apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jannah-compute
spec:
  hosts:
  - "*"
  gateways:
  - kubeflow-gateway
  http:
  - match:
    - uri:
        exact: /graphql
    - uri:
        prefix: /admin
    - uri:
        exact: /media
    route:
    - destination:
        host: jannah-compute
        port:
          number: 8200