apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Values.images.middleware.name  }}
  namespace: jannah
spec:
  parentRefs:
  - name: {{ .Values.gateway.name }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /graphql
    - path:
        type: PathPrefix
        value: /admin
    - path:
        type: PathPrefix
        value: /media
    backendRefs:
    - name: {{ .Values.images.middleware.name  }}
      port: {{ .Values.images.middleware.port }}