apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.images.middleware.name  }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.gateway.name }}
  http:
  - match:
    - uri:
        exact: /graphql
    - uri:
        prefix: /admin
    - uri:
        exact: /media
    route:
    - destination:
        host: {{ .Values.images.middleware.name  }}
        port:
          number: {{ .Values.images.middleware.port }}
