apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: jannah-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
    app: jannah-gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"