apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: jannah
spec:
  selector:
    {{- include "jannah-helm.gateway.selectorLabels" . | nindent 6 }}  
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"