apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
spec:
  selector:
    matchLabels:
      {{- include "jannah-helm.gateway.selectorLabels" . | nindent 6 }}  
  template:
    metadata:
      labels:
        {{- include "jannah-helm.gateway.selectorLabels" . | nindent 8 }}
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"