apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.images.frontend.name }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.gateway.name }}
  http:
  - match:
    - uri:
        exact: /
    - uri:
        prefix: /static
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /register
    - uri:
        prefix: /workflows
    route:
    - destination:
        host: {{ .Values.images.frontend.name }}
        port:
          number: {{ .Values.images.frontend.port }}