apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Values.images.frontend.name  }}
  namespace: jannah
spec:
  parentRefs:
  - name: {{ .Values.gateway.name }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /static/admin/
    - path:
        type: PathPrefix
        value: /src/
    - path:
        type: PathPrefix
        value: /favicon.png
    - path:
        type: PathPrefix
        value: /login
    - path:
        type: PathPrefix
        value: /@vite/
    - path:
        type: PathPrefix
        value: /node_modules/
    - path:
        type: PathPrefix
        value: /@id/
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ .Values.images.frontend.name  }}
      port: {{ .Values.images.frontend.port }}