apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jannah-web
spec:
  hosts:
  - "*"
  gateways:
  - kubeflow-gateway
  http:
  - match:
    - uri:
        exact: /admin
    - uri:
        prefix: /static
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /graphql
    route:
    - destination:
        host: productpage
        port:
          number: 9080