apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Values.images.frontend.name  }}
  namespace: jannah
spec:
  parentRefs:
  - name: {{ .Values.gateway.name }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /static/admin
    - path:
        type: PathPrefix
        value: /login
    - path:
        type: PathPrefix
        value: /logout
    - path:
        type: PathPrefix
        value: /register
    - path:
        type: PathPrefix
        value: /workflows
    backendRefs:
    - name: {{ .Values.images.frontend.name  }}
      port: {{ .Values.images.frontend.port }}