---
- name: "Remove Builds from Ubuntu middleware docker images"
  block:
    - name: "Remove /images/ubuntu/middleware directory"
      file:
        path: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/ubuntu/middleware"
        state: absent
      tags:
        - "build_images"
        - "build_middleware_images"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Remove middleware/ubuntu.middleware.Dockerfile"
      file:
        path: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/ubuntu/middleware/jannah_graphql/ubuntu.middleware.Dockerfile"
        state: absent
      tags:
        - "build_images"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Remove ubuntu/ubuntu.middleware.Dockerfile.dockerignore"
      file:
        path: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/ubuntu/middleware/jannah_graphql/ubuntu.middleware.Dockerfile.dockerignore"
        state: absent
      tags:
        - "build_images"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Remove Ubuntu middleware image - arm64"
      shell: |
        docker image rm -f \
        {{ Jannah.stages.bootstrap.deploy.helm_values.images.middleware.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.arm }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.ubuntu }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }};
        exit 0;
      when: ansible_facts['architecture'] != "x86_64"
      async: 600
      poll: 5
      tags:
        - "build_images"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Remove Ubuntu middleware image - amd64"
      shell: |
        docker image rm -f \
        {{ Jannah.stages.bootstrap.deploy.helm_values.images.middleware.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.amd }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.ubuntu }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }};
        exit 0;
      when: ansible_facts['architecture'] == "x86_64"
      async: 600
      poll: 5
      tags:
        - "build_images"
        - "molecule_destroy"
        - "operator_e2e"
  rescue:
    - name: "Remove Builds Ubuntu Middleware Docker Images Exception"
      ansible.builtin.debug:
        msg: 'Remove Builds Ubuntu Middleware Docker Images Exception'
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "build_images"
        - "build_ubuntu_images"
        - "molecule_destroy"
        - "operator_e2e"
  ignore_errors: false
