---
- name: "Remove Builds from Ubuntu frontend docker images"
  block:
    - name: "Remove /images/ubuntu/frontend directory"
      file:
        path: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/ubuntu/frontend"
        state: absent
      tags:
        - "cleanup_ubuntu_frontend_images"
        - "build_frontend_images"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Remove frontend/ubuntu.frontend.Dockerfile"
      file:
        dest: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/ubuntu/frontend/web/JannahIonic/ubuntu.frontend.Dockerfile"
        state: absent
      tags:
        - "cleanup_ubuntu_frontend_images"
        - "build_frontend_images"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Remove ubuntu/ubuntu.frontend.Dockerfile.dockerignore"
      file:
        path: "${MOLECULE_EPHEMERAL_DIRECTORY}/images/ubuntu/frontend/web/JannahIonic/ubuntu.frontend.Dockerfile.dockerignore"
        state: absent
      tags:
        - "cleanup_ubuntu_frontend_images"
        - "build_frontend_images"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Remove Ubuntu frontend image - arm64"
      shell: |
        docker image rm -f \
        {{ Jannah.stages.bootstrap.deploy.helm_values.images.frontend.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.arm }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.ubuntu }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }};
        exit 0;
      when: ansible_facts['architecture'] != "x86_64"
      async: 600
      poll: 5
      tags:
        - "cleanup_ubuntu_frontend_images"
        - "build_frontend_images"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Remove Ubuntu frontend image - amd64"
      shell: |
        docker image rm -f \
        {{ Jannah.stages.bootstrap.deploy.helm_values.images.frontend.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.amd }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.ubuntu }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }};
        exit 0;
      when: ansible_facts['architecture'] == "x86_64"
      async: 600
      poll: 5
      tags:
        - "cleanup_ubuntu_frontend_images"
        - "build_frontend_images"
        - "molecule_destroy"
        - "operator_e2e"
  rescue:
    - name: "Builds Ubuntu Frontend Docker Images Exception"
      ansible.builtin.debug:
        msg: 'Builds Ubuntu Frontend Docker Images Exception'
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "cleanup_ubuntu_frontend_images"
        - "build_frontend_images"
        - "build_ubuntu_images"
        - "molecule_destroy"
        - "operator_e2e"
  ignore_errors: false
