---
- name: "Remove streamos docker images"
  block:
    - name: "set_fact jannah_stages_bootstrap_deploy_os"
      ansible.builtin.set_fact:
        jannah_stages_bootstrap_deploy_os: "{{ Jannah.stages.bootstrap.deploy.os }}"
      tags:
        - "deploy_images"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Remove images/streamos directory"
      file:
        path: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/images/streamos"
        state: absent
      tags:
        - "cleanup_streamos_build_images"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Remove images/streamos/streamos.Dockerfile"
      file:
        path: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/images/streamos/streamos.Dockerfile"
        state: absent
      tags:
        - "cleanup_streamos_build_images"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Remove project/streamos.Dockerfile"
      file:
        path: "{{ Jannah.global.ansible.working_dir }}/streamos.Dockerfile"
        state: absent
      tags:
        - "cleanup_streamos_build_images"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Remove streamos/streamos.Dockerfile.dockerignore"
      file:
        path: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/images/streamos/streamos.Dockerfile.dockerignore"
        state: absent
      tags:
        - "cleanup_streamos_build_images"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Remove project/streamos.Dockerfile.dockerignore"
      file:
        path: "{{ Jannah.global.ansible.working_dir }}/streamos.Dockerfile.dockerignore"
        state: absent
      tags:
        - "cleanup_streamos_build_images"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Import cleanup prepared build image tasks - streamos middleware and frontend"
      include_tasks: '{{ cleanup_prepared_streamos_middleware_and_frontend_task_items }}'
      with_fileglob:
        - cleanup_build_streamos_middleware_images.yml
        - cleanup_build_streamos_frontend_images.yml
      loop_control:
        loop_var: cleanup_prepared_streamos_middleware_and_frontend_task_items
      tags:
        - "docker_desktop_infra"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Remove StreamOs boot image - arm64"
      shell: |
        docker image rm -f \
        {{ Jannah.stages.bootstrap.deploy.helm_values.images.boot.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.arm }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.streamos }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }};
        exit 0;
      when: ansible_facts['architecture'] != "x86_64" and jannah_stages_bootstrap_deploy_os == "streamos"
      async: 9800
      poll: 5
      args:
        chdir: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/images/streamos"
      tags:
        - "build_images"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Remove StreamOs boot image - amd64"
      shell: |
        docker image rm -f \
        {{ Jannah.stages.bootstrap.deploy.helm_values.images.boot.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.amd }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.streamos }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }};
        exit 0;
      when: ansible_facts['architecture'] == "x86_64" and jannah_stages_bootstrap_deploy_os == "streamos"
      async: 9800
      poll: 5
      args:
        chdir: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/images/streamos"
      tags:
        - "build_images"
        - "molecule_destroy"
        - "operator_e2e"
  rescue:
    - name: "Cleanup Builds for StreamOs Docker Images Exception"
      ansible.builtin.debug:
        msg: 'Cleanup Builds for StreamOs Docker Images Exception'
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "cleanup_streamos_build_images"
        - "molecule_destroy"
        - "operator_e2e"
  ignore_errors: false
