---
- name: "Remove Builds for streamos frontend docker images"
  block:
    - name: "Remove /images/streamos/frontend directory"
      file:
        path: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/images/streamos/frontend"
        state: absent
      tags:
        - "cleanup_streamos_middleware_images"
        - "build_frontend_images"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Remove frontend/streamos.frontend.Dockerfile"
      file:
        path: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/images/streamos/frontend/web/JannahIonic/streamos.frontend.Dockerfile"
        state: absent
      tags:
        - "cleanup_streamos_middleware_images"
        - "build_frontend_images"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Remove streamos/streamos.frontend.Dockerfile.dockerignore"
      file:
        path: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/images/streamos/frontend/web/JannahIonic/streamos.frontend.Dockerfile.dockerignore"
        state: absent
      tags:
        - "cleanup_streamos_middleware_images"
        - "build_frontend_images"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Remove frontend image arm64/streamos"
      shell: |
        docker image rm -f \
        {{ Jannah.stages.bootstrap.deploy.helm_values.images.frontend.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.arm }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.streamos }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }};
        exit 0;
      when: ansible_facts['architecture'] != "x86_64"
      async: 600
      poll: 5
      tags:
        - "cleanup_streamos_middleware_images"
        - "build_frontend_images"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Remove frontend image amd64/streamos"
      shell: |
        docker image rm -f \
        {{ Jannah.stages.bootstrap.deploy.helm_values.images.frontend.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.amd }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.streamos }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }};
        exit 0;
      when: ansible_facts['architecture'] == "x86_64"
      async: 600
      poll: 5
      tags:
        - "cleanup_streamos_middleware_images"
        - "build_frontend_images"
        - "molecule_destroy"
        - "operator_e2e"
  rescue:
    - name: "Remove Builds for StreamOs Frontend Docker Images Exception"
      ansible.builtin.debug:
        msg: 'Remove Builds for StreamOs Frontend Docker Images Exception'
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "cleanup_streamos_middleware_images"
        - "build_frontend_images"
        - "build_streamos_images"
        - "molecule_destroy"
        - "operator_e2e"
  ignore_errors: false
