---
- name: "Remove Builds for ubuntu docker images"
  block:
    - name: "set_fact jannah_stages_bootstrap_deploy_os"
      ansible.builtin.set_fact:
        jannah_stages_bootstrap_deploy_os: "{{ Jannah.stages.bootstrap.deploy.os }}"
      tags:
        - "deploy_images"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Remove images/ubuntu directory"
      file:
        path: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/images/ubuntu"
        state: absent
      tags:
        - "remove_ubuntu_base_images"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Remove images/ubuntu/ubuntu.Dockerfile"
      file:
        path: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/images/ubuntu/ubuntu.Dockerfile"
        state: absent
      tags:
        - "remove_ubuntu_base_images"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Remove project/ubuntu.Dockerfile"
      file:
        path: "{{ Jannah.global.ansible.working_dir }}/ubuntu.Dockerfile"
        state: absent
      tags:
        - "remove_ubuntu_base_images"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Remove ubuntu/ubuntu.Dockerfile.dockerignore"
      file:
        path: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/images/ubuntu/ubuntu.Dockerfile.dockerignore"
        state: absent
      tags:
        - "remove_ubuntu_base_images"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Remove project/ubuntu.Dockerfile.dockerignore"
      file:
        path: "{{ Jannah.global.ansible.working_dir }}/ubuntu.Dockerfile.dockerignore"
        state: absent
      tags:
        - "remove_ubuntu_base_images"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Import prepare build image tasks - ubuntu middleware and frontend"
      include_tasks: '{{ cleanup_prepared_ubuntu_middleware_and_frontend_task_items }}'
      with_fileglob:
        - cleanup_build_ubuntu_middleware_images.yml
        - cleanup_build_ubuntu_frontend_images.yml
      loop_control:
        loop_var: cleanup_prepared_ubuntu_middleware_and_frontend_task_items
      tags:
        - "docker_desktop_infra"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Remove Ubuntu boot image - arm64"
      shell: |
        docker image rm -f \
        {{ Jannah.stages.bootstrap.deploy.helm_values.images.middleware.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.arm }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.ubuntu }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }};
        exit 0;
      when: ansible_facts['architecture'] != "x86_64" and jannah_stages_bootstrap_deploy_os == "ubuntu"
      async: 9800
      poll: 5
      tags:
        - "build_images"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Remove Ubuntu boot image - amd64"
      shell: |
        docker image rm -f \
        {{ Jannah.stages.bootstrap.deploy.helm_values.images.boot.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.amd }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.ubuntu }}:{{ Jannah.stages.bootstrap.deploy.helm_values.common.tag }};
        exit 0;
      when: ansible_facts['architecture'] == "x86_64" and jannah_stages_bootstrap_deploy_os == "ubuntu"
      async: 9800
      poll: 5
      tags:
        - "build_images"
        - "molecule_destroy"
        - "operator_e2e"
  rescue:
    - name: "Builds Ubuntu Docker Images Exception"
      ansible.builtin.debug:
        msg: 'Builds Ubuntu Docker Images Exception'
      tags:
        - "remove_ubuntu_base_images"
        - "build_ubuntu_images"
        - "molecule_destroy"
        - "operator_e2e"
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "remove_ubuntu_base_images"
        - "build_ubuntu_images"
        - "molecule_destroy"
        - "operator_e2e"
  ignore_errors: false
