---
- name: "Cleanup storage artifacts from MacOs Docker Desktop"
  block:
    - name: 'Delete Parcona Postgres Namespace'
      shell: |
        kubectl delete all --all -n "{{ Jannah.stages.bootstrap.deploy.dependencies.parcona_postgres.namespace }}";
        exit 0;
      tags:
        - "docker_desktop_infra"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "set_fact jannah_stages_bootstrap_deploy_destination"
      ansible.builtin.set_fact:
        jannah_stages_bootstrap_deploy_destination: "{{ Jannah.stages.bootstrap.deploy.destination }}"
      tags:
        - "deploy_images"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "set_fact jannah_stages_bootstrap_deploy_wait_time"
      ansible.builtin.set_fact:
        jannah_stages_bootstrap_deploy_wait_time: "{{ Jannah.stages.bootstrap.deploy.wait_time }}"
      tags:
        - "deploy_images"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Wait for Delete Parcona Postgres Namespace on Docker-Desktop"
      shell: |
        sleep {{ Jannah.stages.bootstrap.deploy.wait_time }};
      when: (
              jannah_stages_bootstrap_deploy_destination == "docker-desktop"
              and 
              jannah_stages_bootstrap_deploy_wait_time > 0
            )
  rescue:
    - name: "Clean Prepared Operator MacOs Docker Desktop Exception"
      ansible.builtin.debug:
        msg: 'Clean Prepared Operator MacOs Docker Desktop Exception'
      tags:
        - "docker_desktop_infra"
        - "molecule_destroy"
        - "operator_e2e"
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "docker_desktop_infra"
        - "molecule_destroy"
        - "operator_e2e"
  ignore_errors: false
