---
- name: "Cleanup prepared Jannah Tasks"
  block:
    - name: "Import clean prepared docker desktop tasks - Darwin"
      include_tasks: '{{ cleanup_prepared_macos_docker_desktop_task_items }}'
      with_fileglob:
        - cleanup_macos_docker_desktop.yml
        - cleanup_storage_to_macos_docker_desktop.yml
      loop_control:
        loop_var: cleanup_prepared_macos_docker_desktop_task_items
      when: ansible_facts['os_family'] == "Darwin"
      tags:
        - "docker_desktop_infra"
        - "molecule_destroy"
        - "operator_e2e"
        - "debug_task"
    - name: "Import cleanup prepared build_base_image tasks - Darwin"
      include_tasks: '{{ cleanup_prepared_build_base_image_task_items }}'
      with_fileglob:
        - cleanup_build_base_image.yml
      loop_control:
        loop_var: cleanup_prepared_build_base_image_task_items
      when: ansible_facts['os_family'] == "Darwin"
      tags:
        - "docker_desktop_infra"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Import cleanup prepared build streamos images tasks - StreamOS"
      include_tasks: '{{ cleanup_prepare_build_streamos_images_task_items }}'
      with_fileglob:
        - cleanup_build_streamos_images.yml
      loop_control:
        loop_var: cleanup_prepare_build_streamos_images_task_items
      when: ansible_facts['os_family'] == "Darwin" or ansible_facts['os_family'] != "Debian"
      tags:
        - "docker_desktop_infra"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Import cleanup prepared build ubuntu images tasks - Darwin"
      include_tasks: '{{ cleanup_prepared_build_ubuntu_images_task_items }}'
      with_fileglob:
        - cleanup_build_ubuntu_images.yml
      loop_control:
        loop_var: cleanup_prepared_build_ubuntu_images_task_items
      when: ansible_facts['os_family'] == "Darwin" or ansible_facts['os_family'] == "Debian"
      tags:
        - "docker_desktop_infra"
        - "molecule_destroy"
        - "operator_e2e"
  rescue:
    - name: "Cleanup prepared Jannah Tasks Exception"
      ansible.builtin.debug:
        msg: 'Cleanup prepared Jannah Tasks Exception'
      register: cleanup_prepared_jannah_tasks_debug_resources
    - debug: var=cleanup_prepared_jannah_tasks_debug_resources
      tags:
        - "perpare_jannah"
        - "operator_e2e"
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
  ignore_errors: false
