---
provisioner:
  inventory:
    group_vars:
      all:
        Jannah:
          stages:
            bootstrap:
              downloads:
                opm: opm
                base_dir: downloads
    host_vars:
      localhost:
        name: localhost
