---
- name: "Prepare kind cluster"
  block:
    - name: 'Create Jannah namespace if not already existing'
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ Jannah.stages.bootstrap.deploy.helm_values.common.namespace }}"
      tags:
        - "deploy_images"
        - "molecule_prepare"
        - "operator_e2e"
  rescue:
    - name: "Prepare kind cluster Exception"
      ansible.builtin.debug:
        msg: 'Prepare kind cluster Exception'
      tags:
        - "deploy_images"
        - "molecule_prepare"
        - "operator_e2e"
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "deploy_images"
        - "molecule_prepare"
        - "operator_e2e"
  ignore_errors: false
