---
- name: "Remove Docker Registry"
  block:
    - name: "set_fact jannah_stages_bootstrap_deploy_destination"
      ansible.builtin.set_fact:
        jannah_stages_bootstrap_deploy_destination: "{{ Jannah.stages.bootstrap.deploy.destination }}"
      tags:
        - "remove_registry"
        - "molecule_destroy"
        - "operator_e2e"
        - "debug_task"
    - name: "set_fact jannah_stages_bootstrap_deploy_wait_time"
      ansible.builtin.set_fact:
        jannah_stages_bootstrap_deploy_wait_time: "{{ Jannah.stages.bootstrap.deploy.wait_time }}"
      tags:
        - "remove_registry"
        - "molecule_destroy"
        - "operator_e2e"
    - name: "Deploy Quay Operator - Remove the CatalogSource - docker-desktop"
      shell: |
        kubectl delete \
        -n "{{ Jannah.stages.bootstrap.deploy.helm_values.common.namespace }}" \
        -f ./bundle/quay-operator.catalogsource.yaml;
      when: jannah_stages_bootstrap_deploy_destination == "docker-desktop"
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/{{ Jannah.stages.bootstrap.deploy.dependencies.quay.namespace }}"
      tags:
        - "remove_registry"
        - "molecule_destroy"
        - "operator_e2e" 
    - name: "Deploy Quay Operator - Remove the CatalogSource - kind"
      environment:
        KUBECONFIG: "${MOLECULE_EPHEMERAL_DIRECTORY}/kind/config"
      shell: |
        kubectl delete \
        -n "{{ Jannah.stages.bootstrap.deploy.helm_values.common.namespace }}" \
        -f ./bundle/quay-operator.catalogsource.yaml;
      when: jannah_stages_bootstrap_deploy_destination == "kind"
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/{{ Jannah.stages.bootstrap.deploy.dependencies.quay.namespace }}"
      tags:
        - "remove_registry"
        - "molecule_destroy"
        - "operator_e2e" 
    - name: "Deploy Quay Operator - Delete the OperatorGroup - docker-desktop"
      shell: |
        kubectl delete \
        -n "{{ Jannah.stages.bootstrap.deploy.helm_values.common.namespace }}" \
        -f ./bundle/quay-operator.operatorgroup.yaml;
      when: jannah_stages_bootstrap_deploy_destination == "docker-desktop"
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/quay_operator"
      tags:
        - "remove_registry"
        - "molecule_destroy"
        - "operator_e2e" 
    - name: "Deploy Quay Operator - Delete the OperatorGroup - kind"
      environment:
        KUBECONFIG: "${MOLECULE_EPHEMERAL_DIRECTORY}/kind/config"
      shell: |
        kubectl delete \
        -n "{{ Jannah.stages.bootstrap.deploy.helm_values.common.namespace }}" \
        -f ./bundle/quay-operator.operatorgroup.yaml;
      when: jannah_stages_bootstrap_deploy_destination == "kind"
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/quay_operator"
      tags:
        - "remove_registry"
        - "molecule_destroy"
        - "operator_e2e" 
    - name: "Deploy Quay Operator - Delete the OperatorGroup - docker-desktop"
      shell: |
        kubectl delete \
        -n "{{ Jannah.stages.bootstrap.deploy.helm_values.common.namespace }}" \ 
        -f ./bundle/quay-operator.subscription.yaml;
      when: jannah_stages_bootstrap_deploy_destination == "docker-desktop"
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/quay_operator"
      tags:
        - "remove_registry"
        - "molecule_destroy"
        - "operator_e2e" 
    - name: "Deploy Quay Operator - Delete the OperatorGroup - kind cluster"
      environment:
        KUBECONFIG: "${MOLECULE_EPHEMERAL_DIRECTORY}/kind/config"
      shell: |
        kubectl delete \
        -n "{{ Jannah.stages.bootstrap.deploy.helm_values.common.namespace }}" \ 
        -f ./bundle/quay-operator.subscription.yaml;
      when: jannah_stages_bootstrap_deploy_destination == "kind"
      args:
        chdir: "${MOLECULE_EPHEMERAL_DIRECTORY}/quay_operator"
      tags:
        - "remove_registry"
        - "molecule_destroy"
        - "operator_e2e" 
  rescue:
    - name: "Deploy Operators Storage to MacOs Docker Desktop Exception"
      ansible.builtin.debug:
        msg: 'Deploy Operators Storage to MacOs Docker Desktop Exception'
      tags:
        - "remove_registry"
        - "molecule_destroy"
        - "operator_e2e" 
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "remove_registry"
        - "molecule_destroy"
        - "operator_e2e" 
  ignore_errors: false
