---
- name: "Cleanup Jannah Environment Tasks"
  block:
    - name: "Import cleanup tasks - Darwin"
      include_tasks: '{{ cleanup_kind_task_darwin_items }}'
      with_fileglob:
        - prepared_artifacts/main.yml
      loop_control:
        loop_var: cleanup_kind_task_darwin_items
      when: ansible_facts['os_family'] == "Darwin"
      tags:
        - "molecule_cleanup"
        - "operator_e2e"
  rescue:
    - name: "Cleanup Jannah Tasks Exception"
      ansible.builtin.debug:
        msg: 'Cleanup Jannah Tasks Exception'
    - name: "Print return information from the previous task"
      ansible.builtin.debug:
        var: ansible_facts['architecture']
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
  ignore_errors: false
