---
  - name: "Day 1, Day 2: Operator SDK Tasks"
    block:
      - name: "Import Other Day1 Day 2 Tasks"
        include_tasks: '{{ item }}'
        with_fileglob:
          - bootstrap_config/main.yml
          - bootstrap_charm/main.yml
        tags:
          - "d1d2-generate-molecule-configurations"
          - "d1d2-blog-service-install"
          - "d1d2-jekyll-new-jannah-operator"
          - "d1d2-juju-olm-install"
          - "d1d2-juju-olm-install-one-time-event"
          - "d1d2-olm-install"
    rescue:
      - name: 'TODO: do a kubectl describe'
        ansible.builtin.debug:
          msg: 'TODO: do a kubectl describe'
    always:
      - name: "Bootstrap Resources"
        k8s_info:
          api_version: '{{ item.api_version }}'
          kind: '{{ item.kind }}'
          namespace: '{{ Jannah.credentials[1].namespace }}'
        loop:
          - api_version: v1
            kind: Pod
          - api_version: apps/v1
            kind: Deployment
          - api_version: v1
            kind: Secret
          - api_version: v1
            kind: ConfigMap
          - api_version: v1
            kind: ClusterIssuer
          - api_version: v1
            kind: Certificate
          - api_version: v1
            kind: Secret
          - api_version: v1
            kind: Issuer
        register: debug_resources
    #become: true
    ignore_errors: false
    