
---
- name: "Uninstall Jannah specific services"
  block:
    - name: "Jannab un-install"
      shell: |
        kubectl delete all --all -n \
        {{ Jannah.stages.bootstrap.deploy.helm_values.common.namespace }};
        exit 0;
      tags:
        - "docker_desktop_infra"
        - "molecule_cleanup"
        - "operator_e2e"

  rescue:
    - name: "Clean Prepared Operator MacOs Docker Desktop Exception"
      ansible.builtin.debug:
        msg: 'Clean Prepared Operator MacOs Docker Desktop Exception'
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "multipass_infra"
        - "molecule_cleanup"
        - "operator_e2e"
  ignore_errors: false
