---
- name: "Cleanup storage artifacts from MacOs Docker Desktop"
  block:
    - name: "Delete Percona Distribution for PostgreSQL cluster"
      shell: |
        sleep 10;
        kubectl delete -f https://raw.githubusercontent.com/percona/percona-postgresql-operator/v2.2.0/deploy/cr.yaml \
        -n "{{ Jannah.stages.bootstrap.deploy.dependencies.parcona_postgres.namespace }}";
        exit 0;
      tags:
        - "docker_desktop_infra"
        - "molecule_converge"
        - "operator_e2e"
        - "debug_task"
    - name: "Delete Percona Postgresql Operator"
      shell: |
        kubectl delete -f \
        https://raw.githubusercontent.com/percona/percona-postgresql-operator/v2.2.0/deploy/bundle.yaml \
        -n "{{ Jannah.stages.bootstrap.deploy.dependencies.parcona_postgres.namespace }}";
        exit 0;
      tags:
        - "docker_desktop_infra"
        - "molecule_converge"
        - "operator_e2e"
        - "debug_task"
    - name: 'Delete Parcona Postgres Namespace'
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: '{{ Jannah.stages.bootstrap.deploy.dependencies.parcona_postgres.namespace }}'
            namespace: '{{ Jannah.stages.bootstrap.deploy.dependencies.parcona_postgres.namespace }}'
        state: absent
      tags:
        - "docker_desktop_infra"
        - "molecule_cleanup"
        - "operator_e2e"
        - "debug_task"
  rescue:
    - name: "Clean Prepared Operator MacOs Docker Desktop Exception"
      ansible.builtin.debug:
        msg: 'Clean Prepared Operator MacOs Docker Desktop Exception'
      tags:
        - "docker_desktop_infra"
        - "molecule_cleanup"
        - "operator_e2e"
        - "debug_task"
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "docker_desktop_infra"
        - "molecule_cleanup"
        - "operator_e2e"
        - "debug_task"
  ignore_errors: false
