---
- name: "Stop nginx docker containers"
  block:
    - name: "Stop nginx container "
      shell: |
        docker container stop \
          {{ Jannah.stages.bootstrap.deploy.helm_values.images.proxy.name }};
        exit 0;
      async: 9800
      poll: 5
      tags:
        - "cleanup_images"
        - "molecule_cleanup"
        - "operator_e2e"
  rescue:
    - name: "Tag and Push Ubuntu Docker Images Exception"
      ansible.builtin.debug:
        msg: "Tag and Push Ubuntu Docker Images Exception"
      tags:
        - "cleanup_images"
        - "molecule_cleanup"
        - "operator_e2e" 
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "cleanup_images"
        - "molecule_cleanup"
        - "operator_e2e"
  ignore_errors: false
