---
- name: "Stop containers from Ubuntu frontend docker images"
  block:
    - name: "Docker stop Jannah frontend arm64/ubuntu image in dev (container) mode"
      shell: |
        docker container stop \
        {{ Jannah.stages.bootstrap.deploy.helm_values.images.frontend.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.arm }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.ubuntu }};
        exit 0;
      when: ansible_facts['architecture'] != "x86_64"
      async: 600
      poll: 5
      tags:
        - "deploy_images"
        - "stop_frontend_images"
        - "molecule_cleanup"
        - "operator_e2e"
    - name: "Docker rm Jannah frontend arm64/ubuntu image in dev (container) mode"
      shell: |
        docker container rm -f \
        {{ Jannah.stages.bootstrap.deploy.helm_values.images.frontend.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.arm }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.ubuntu }};
        exit 0;
      when: ansible_facts['architecture'] != "x86_64"
      async: 600
      poll: 5
      tags:
        - "deploy_images"
        - "stop_frontend_images"
        - "molecule_cleanup"
        - "operator_e2e"
    - name: "Docker stop Jannah frontend amd64/ubuntu image in dev (container) mode"
      shell: |
        docker container stop \
        {{ Jannah.stages.bootstrap.deploy.helm_values.images.frontend.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.amd }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.ubuntu }};
        exit 0;
      when: ansible_facts['architecture'] == "x86_64"
      async: 600
      poll: 5
      tags:
        - "deploy_images"
        - "stop_frontend_images"
        - "molecule_cleanup"
        - "operator_e2e"
    - name: "Docker rm Jannah frontend amd64/ubuntu image in dev (container) mode"
      shell: |
        docker container rm -f \
        {{ Jannah.stages.bootstrap.deploy.helm_values.images.frontend.name }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.amd }}-{{ Jannah.stages.bootstrap.deploy.helm_values.common.ubuntu }};
        exit 0;
      when: ansible_facts['architecture'] == "x86_64"
      async: 600
      poll: 5
      tags:
        - "deploy_images"
        - "stop_frontend_images"
        - "molecule_cleanup"
        - "operator_e2e"
  rescue:
    - name: "Stop Ubuntu Frontend Exception"
      ansible.builtin.debug:
        msg: 'Stop Ubuntu Frontend Exception'
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "cleanup_ubuntu_frontend_images"
        - "stop_frontend_images"
        - "build_ubuntu_images"
        - "molecule_cleanup"
        - "operator_e2e"
  ignore_errors: false
