---
- name: "Clean up base images"
  block:
    - name: "docker buildx stop"
      shell: |
        docker buildx stop kube;
        exit 0;
      tags:
        - "cleanup_base_images"
        - "molecule_cleanup"
        - "operator_e2e"
  rescue:
    - name: "Cleanup Base_Images Exception"
      ansible.builtin.debug:
        msg: "Cleanup Base_Images Exception"
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "cleanup_base_images"
        - "molecule_cleanup"
        - "operator_e2e"
  ignore_errors: false
