---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: true
  tasks:
    - name: "Create multipass VM environment if developing on MacOs"
      block:
        - name: "Import multipass (Ubuntu on Darwin) build infra tasks"
          include_tasks: '{{ create_task_item }}'
          with_fileglob:
            - tasks/create/main.yml
          loop_control:
            loop_var: create_task_item
          tags:
            - "multipass_infra"
            - "molecule_create"
            - "operator_e2e"
            - "dev_debug"
      rescue:
        - name: "Create multipass exception is thrown"
          ansible.builtin.debug:
            msg: 'Create multipass exception is thrown'

        - name: Re-emit failure
          vars:
            failed_task:
              result: '{{ ansible_failed_result }}'
          fail:
            msg: '{{ failed_task }}'
