---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: true
  no_log: "{{ molecule_no_log }}"
  tasks:
    - name: "Destroy environment for Jannah"
      block:
        - name: "Import destroy tasks - Darwin"
          include_tasks: '{{ destroy_exec_task_item }}'
          with_fileglob:
            - tasks/destroy/exec_destroy.yml
          loop_control:
            loop_var: destroy_exec_task_item
          when: ansible_facts['os_family'] == "Darwin"
          tags:
            - "multipass_infra"
            - "molecule_destroy"
            - "operator_e2e"
        - name: "Import destroy tasks - Ubuntu, Darwin arm64"
          include_tasks: '{{ destroy_inline_task_item }}'
          with_fileglob:
            - tasks/destroy/inline_destroy.yml
          loop_control:
            loop_var: destroy_inline_task_item
          when: ansible_facts['os_family'] != "Darwin" or ansible_facts['architecture'] == "arm64"
          tags:
            - "multipass_infra"
            - "molecule_destroy"
            - "operator_e2e"
#        - name: "Print os_family"
#          ansible.builtin.debug:
#            var: ansible_facts['os_family']
      rescue:
        - name: "Prepare exception is thrown"
          ansible.builtin.debug:
            msg: 'Prepare exception is thrown'
        - name: Re-emit failure
          vars:
            failed_task:
              result: '{{ ansible_failed_result }}'
          fail:
            msg: '{{ failed_task }}'