---
- name: Prepare
  hosts: localhost
  connection: local
  gather_facts: true
  tasks:
    - name: "Prepare environment for deploying Jannah"
      block:
        - name: "Import prepare tasks"
          include_tasks: '{{ item }}'
          with_fileglob:
            - tasks/prepare/main.yml
          tags:
            - "multipass_infra"
            - "molecule_prepare"
            - "operator_e2e"
      rescue:
        - name: "Prepare exception is thrown"
          ansible.builtin.debug:
            msg: 'Prepare exception is thrown'
        - name: Re-emit failure
          vars:
            failed_task:
              result: '{{ ansible_failed_result }}'
          fail:
            msg: '{{ failed_task }}'