---
# https://docs.docker.com/build/drivers/kubernetes/#example-creating-a-buildx-builder-in-kubernetes
- name: "Use Docker buildx to create starter images"
  block:
    - name: "Create MOLECULE_EPHEMERAL_DIRECTORY directory"
      file:
        path: "$MOLECULE_EPHEMERAL_DIRECTORY/jannah_services"
        state: directory
        mode: 0755
      tags:
        - "buildx_infra"

    - name: "Git clone frontend application"
      git:
        repo: '{{  Jannah.stages.bootstrap.build.builderx[0].services[0].giturl }}'
        dest: "$MOLECULE_EPHEMERAL_DIRECTORY/jannah_services/frontend"
      tags:
        - "buildx_infra"

    - name: "Git clone middleware application"
      git:
        repo: '{{  Jannah.stages.bootstrap.build.builderx[0].services[1].giturl }}'
        dest: "$MOLECULE_EPHEMERAL_DIRECTORY/jannah_services/middleware"
      tags:
        - "buildx_infra"

    - name: "Create a new Buildx builder with the Kubernetes driver"
      shell: |
        docker buildx create \
        --bootstrap \
        --name={{  Jannah.stages.bootstrap.build.builderx[0].name }} \
        --driver={{ Jannah.stages.bootstrap.build.builderx[0].driver }} \
        --buildkitd-flags='--allow-insecure-entitlement security.insecure' \
        --driver-opt=namespace={{ Jannah.global.namespace }}; \
        docker buildx ls;
      tags:
        - "buildx_infra"

    - name: "Build the image for the frontend application"
      shell: |
          git checkout task-kSPivE2w-jannah-vue-js.loginlogout;
          ls -lrt;
          docker buildx build \
          --builder={{  Jannah.stages.bootstrap.build.builderx[0].name }} \
          --allow security.insecure \
           --file="$MOLECULE_EPHEMERAL_DIRECTORY/jannah_services/frontend/multiplatform/Jannah/Dockerfile" \
          -t {{  Jannah.stages.bootstrap.build.builderx[0].services[0].image }} \
           --push . ; 
          docker images;
      args:
        chdir: "$MOLECULE_EPHEMERAL_DIRECTORY/jannah_services/frontend"
      tags:
        - "buildx_infra"

    - name: "Build the image for the middleware application"
      shell: |
        git checkout task-aVYVi17T-base-jannah-django-app-model.login_jannah.graphql;
        ls -lrt;
        docker buildx build \
        --builder={{  Jannah.stages.bootstrap.build.builderx[0].name }} \
        --allow security.insecure \
         --file="$MOLECULE_EPHEMERAL_DIRECTORY/jannah_services/middleware/Dockerfile" \
        -t {{  Jannah.stages.bootstrap.build.builderx[0].services[1].image }} \
         --push . ; 
        docker images;
      args:
        chdir: "$MOLECULE_EPHEMERAL_DIRECTORY/jannah_services/middleware"
      tags:
        - "buildx_infra"


