---
dependency:
  name: galaxy
  options:
    role-file: ./requirements.yml
    #requirements-file: ./collections.yml
driver:
  name: delegated
lint: |
  set -e
  yamllint -d "{extends: relaxed, rules: {line-length: {max: 120}}}" .
platforms:
  - name: cluster
    groups:
      - k8s
provisioner:
  name: ansible
  lint: |
    set -e
    ansible-lint
  playbooks:
    cleanup: cleanup.yml
  inventory:
    group_vars:
      all:
        namespace: ${TEST_OPERATOR_NAMESPACE:-osdk-test}
    host_vars:
      localhost:
        ansible_python_interpreter: '{{ ansible_playbook_python }}'
        config_dir: ${MOLECULE_PROJECT_DIRECTORY}/config
        samples_dir: ${MOLECULE_PROJECT_DIRECTORY}/config/samples
        operator_image: ${OPERATOR_IMAGE:-""}
        operator_pull_policy: ${OPERATOR_PULL_POLICY:-"Always"}
        kustomize: ${KUSTOMIZE_PATH:-kustomize}
  env:
    K8S_AUTH_KUBECONFIG: ${KUBECONFIG:-"~/.kube/config"}
    KUSTOMIZE_PATH: "/usr/local/bin/kustomize"
    OPERATOR_IMAGE: "docker.io/USERID/OPERATOR-NAME:v0.0.1"
    TEST_OPERATOR_NAMESPACE: "test-operator-system"
verifier:
  name: ansible
  lint: |
    set -e
    ansible-lint
