---
- name: "Test deployments for Jannah"
  block:
    - name: "Import verify  docker desktop tasks - Darwin"
      include_tasks: '{{ verify_deploy_to_macos_docker_desktop_task_items }}'
      with_fileglob:
        - verify_deploy_to_macos_docker_desktop.yml
      loop_control:
        loop_var: verify_deploy_to_macos_docker_desktop_task_items
      when: ansible_facts['os_family'] == "Darwin"
      tags:
        - "docker_desktop_infra"
        - "molecule_verify"
        - "operator_e2e"
    - name: "Import tasks to verify deploy build to streamos nodes - StreamOS"
      include_tasks: '{{ verify_deploy_to_streamos_nodes_task_items }}'
      with_fileglob:
        - verify_deploy_to_streamos_nodes.yml
      loop_control:
        loop_var: verify_deploy_to_streamos_nodes_task_items
      when: ansible_facts['os_family'] != "Darwin" and ansible_facts['os_family'] != "Debian"
      tags:
        - "docker_desktop_infra"
        - "molecule_verify"
        - "operator_e2e"
    - name: "Import tasks to verify deploy builds to ubuntu nodes"
      include_tasks: '{{ converge_deploy_to_ubuntu_nodes_task_items }}'
      with_fileglob:
        - verify_deploy_to_ubuntu_nodes.yml
      loop_control:
        loop_var: converge_deploy_to_ubuntu_nodes_task_items
      when: ansible_facts['os_family'] == "Debian"
      tags:
        - "docker_desktop_infra"
        - "molecule_verify"
        - "operator_e2e"
        - "dev_debug"
  rescue:
    - name: "Prepare Jannah Tasks Exception"
      ansible.builtin.debug:
        msg: 'Prepare Jannah Tasks Exception'
      register: verify_jannah_tasks_debug_resources
    - debug: var=verify_jannah_tasks_debug_resources
      tags:
        - "verify_jannah"
        - "operator_e2e"
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
  ignore_errors: false

