---
- name: "Verify (Deploy) Jannah Tasks"
  block:
    - name: "set_fact jannah_stages_bootstrap_deploy_destination"
      ansible.builtin.set_fact:
        jannah_stages_bootstrap_deploy_destination: "{{ Jannah.stages.bootstrap.deploy.destination }}"
      tags:
        - "deploy_images"
        - "molecule_converge"
        - "operator_e2e"
        - "debug_task"
    - name: "Import verify  docker desktop tasks - Darwin"
      include_tasks: '{{ verify_deploy_to_macos_docker_desktop_task_items }}'
      with_fileglob:
        - verify_deploy_to_macos_docker_desktop.yml
        - verify_deploy_storage_to_macos_docker_desktop.yml
      loop_control:
        loop_var: verify_deploy_to_macos_docker_desktop_task_items
      when: ansible_facts['os_family'] == "Darwin" and (
                                                        jannah_stages_bootstrap_deploy_destination == "docker-desktop"
                                                        or
                                                        jannah_stages_bootstrap_deploy_destination == "kind"
                                                        )
      tags:
        - "docker_desktop_infra"
        - "molecule_converge"
        - "operator_e2e"
        - "debug_task"
  rescue:
    - name: "Verify Deploy Jannah Tasks Exception"
      ansible.builtin.debug:
        msg: 'Verify Deploy Jannah Tasks Exception'
      register: verify_deploy_jannah_tasks_debug_resources
    - debug: var=verify_deploy_jannah_tasks_debug_resources
      tags:
        - "deploy_jannah"
        - "operator_e2e"
        - "debug_task"
        - "molecule_converge"
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "deploy_jannah"
        - "operator_e2e"
        - "debug_task"
        - "molecule_converge"
  ignore_errors: false
