---
- name: "Verify Operator Deployment to MacOs Docker Desktop"
  block:
    - name: "kubectl get pods -n kubeflow"
      shell: |
        kubectl get pods -n kubeflow
      tags:
        - "docker_desktop_infra"
        - "molecule_verify"
        - "operator_e2e"
    - name: "kubectl get deployment -n kubeflow"
      shell: |
        kubectl get deployment -n kubeflow
      tags:
        - "docker_desktop_infra"
        - "molecule_verify"
        - "operator_e2e"
    - name: "Docker logs jallohmediabuild/jannah-ubuntu-middleware-arm64"
      shell: |
        docker logs jannah-ubuntu-middleware-arm64;
      when: ansible_facts['architecture'] != "x86_64"
      async: 600
      poll: 5
      tags:
        - "verify_images"
        - "molecule_verify"
        - "operator_e2e"
    - name: "Docker logs jallohmediabuild/jannah-ubuntu-middleware-amd64"
      shell: |
        docker logs jannah-ubuntu-middleware-amd64;
      when: ansible_facts['architecture'] == "x86_64"
      async: 600
      poll: 5
      tags:
        - "verify_images"
        - "molecule_verify"
        - "operator_e2e"
    - name: "Docker logs jallohmediabuild/jannah-streamos-middleware-arm64"
      shell: |
        docker logs jannah-streamos-middleware-arm64;
      when: ansible_facts['architecture'] != "x86_64"
      async: 600
      poll: 5
      tags:
        - "verify_images"
        - "molecule_verify"
        - "operator_e2e"
    - name: "Docker logs jallohmediabuild/jannah-streamos-middleware-amd64"
      shell: |
        docker logs jannah-streamos-middleware-amd64;
      when: ansible_facts['architecture'] == "x86_64"
      async: 600
      poll: 5
      tags:
        - "verify_images"
        - "molecule_verify"
        - "operator_e2e"
    - name: "Docker logs jallohmediabuild/jannah-ubuntu-frontend-web-arm64"
      shell: |
        docker logs jannah-ubuntu-frontend-web-arm64;
      when: ansible_facts['architecture'] != "x86_64"
      async: 600
      poll: 5
      tags:
        - "verify_images"
        - "build_frontend_images"
        - "molecule_cleanup"
        - "operator_e2e"
    - name: "Docker logs jallohmediabuild/jannah-ubuntu-frontend-web-amd64"
      shell: |
        docker logs jannah-ubuntu-frontend-web-amd64;
      when: ansible_facts['architecture'] == "x86_64"
      async: 600
      poll: 5
      tags:
        - "verify_images"
        - "build_frontend_images"
        - "molecule_cleanup"
        - "operator_e2e"
    - name: "Docker logs jallohmediabuild/jannah-streamos-frontend-web-arm64"
      shell: |
        docker logs jannah-streamos-frontend-web-arm64;
      when: ansible_facts['architecture'] != "x86_64"
      async: 600
      poll: 5
      tags:
        - "verify_images"
        - "build_frontend_images"
        - "molecule_cleanup"
        - "operator_e2e"
        - "dev_debug"
    - name: "Docker logs jallohmediabuild/jannah-streamos-frontend-web-amd64"
      shell: |
        docker logs jannah-streamos-frontend-web-amd64;
      when: ansible_facts['architecture'] == "x86_64"
      async: 600
      poll: 5
      tags:
        - "verify_images"
        - "build_frontend_images"
        - "molecule_cleanup"
        - "operator_e2e"
  rescue:
    - name: "Inline Prepare Operator MacOs Docker Desktop Exception"
      ansible.builtin.debug:
        msg: 'Inline Prepare Operator MacOs Docker Desktop Exception'
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "multipass_infra"
        - "molecule_verify"
        - "operator_e2e"
  ignore_errors: false
