---
# Implements
# https://docs.percona.com/percona-operator-for-postgresql/2.0/kubectl.html#procedure
- name: "Verify Deployed Operators Storage to MacOs Docker Desktop"
  block:
    - name: "set_fact jannah_stages_bootstrap_deploy_destination"
      ansible.builtin.set_fact:
        jannah_stages_bootstrap_deploy_destination: "{{ Jannah.stages.bootstrap.deploy.destination }}"
      tags:
        - "molecule_verify"
        - "operator_e2e"
    - name: "Verify Deployed Percona Postgresql Operator - docker-desktop"
      shell: |
        kubectl get pods \
        -n "{{ Jannah.stages.bootstrap.deploy.dependencies.parcona_postgres.namespace }}";
      when: jannah_stages_bootstrap_deploy_destination == "docker-desktop"
      register: query_to_verify_storage_pods_result_docker_desktop
      tags:
        - "molecule_verify"
        - "operator_e2e"
    - name: "Verify Deployed Percona Postgresql Operator - kind-cluster"
      environment:
        - KUBECONFIG: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/kind/config"
      shell: |
        kubectl get pods \
        -n "{{ Jannah.stages.bootstrap.deploy.dependencies.parcona_postgres.namespace }}";
      when: jannah_stages_bootstrap_deploy_destination == "kind"
      register: query_to_verify_storage_pods_result_kind_cluster
      tags:
        - "molecule_verify"
        - "operator_e2e"
    - name: "query_to_verify_storage_pods_result_docker_desktop"
      debug: var=query_to_verify_storage_pods_result_docker_desktop
        - "molecule_verify"
        - "operator_e2e"
    - name: "query_to_verify_storage_pods_result_kind_cluster"
      debug: var=query_to_verify_storage_pods_result_kind_cluster
      tags:
        - "molecule_verify"
        - "operator_e2e"
    - name: "Assert that non empty result list for query_to_verify_storage_pods_result_docker_desktop"
      assert:
        that:
          - query_to_verify_storage_pods_result_docker_desktop['stdout_lines'] | length >= 3
      tags:
        - "molecule_verify"
        - "operator_e2e"
    - name: "Assert that non empty result list for query_to_verify_storage_pods_result_kind_cluster"
      assert:
        that:
          - query_to_verify_storage_pods_result_kind_cluster['stdout_lines'] | length >= 3
      tags:
        - "molecule_verify"
        - "operator_e2e"
  rescue:
    - name: "Deploy Operators Storage to MacOs Docker Desktop Exception"
      ansible.builtin.debug:
        msg: 'Deploy Operators Storage to MacOs Docker Desktop Exception'
      tags:
        - "molecule_verify"
        - "operator_e2e"
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "molecule_verify"
        - "operator_e2e"
  ignore_errors: false
