---
- name: Check Image Registry Secret
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: '{{ Jannah.stages.bootstrap.secrets.image_registry.name }}'
    namespace: '{{ Jannah.global.namespace }}'
  register: bootstrap_sc

- name: "bootstrap_sc"
  debug: var=bootstrap_sc
- assert:
    that:
      - bootstrap_sc['api_found'] == true
      - bootstrap_sc['resources'][0]['metadata']['name'] == '{{ Jannah.stages.bootstrap.secrets.image_registry.name }}'

- name: Check Image Root Cert Registry Secret
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: '{{ Jannah.stages.bootstrap.secrets.root_cert.name }}'
    namespace: '{{ Jannah.global.namespace }}'
  register: bootstrap_root_cert_sc
- debug: var=bootstrap_root_cert_sc
- assert:
    that:
      - bootstrap_root_cert_sc['api_found'] == true

- name: Check Default Service Account
  kubernetes.core.k8s_info:
    api_version: v1
    kind: ServiceAccount
    name: '{{ Jannah.stages.bootstrap.secrets.root_cert.namespace }}'
  register: bootstrap_root_cert_svc_actn
- debug: var=bootstrap_root_cert_svc_actn
- assert:
    that:
      - bootstrap_root_cert_svc_actn['api_found'] == true