---
# Implements:
# https://juju.is/docs/sdk/set-up-your-development-environment
# However, we are assuming the playbook running on a Mac or Ubuntu
# https://linuxcontainers.org/lxd/getting-started-cli/
# https://formulae.brew.sh/formula/juju
# https://discourse.charmhub.io/t/ann-charmcraft-can-now-be-install-from-homebrew/5259
- name: "Kubernetes on Ubuntu VM environment"
  block:
#    - name: Output gathered resources
#      debug:
#        var: ansible_facts['os_family']
    - name: "Install lxc juju charmcraft - Darwin"
      shell: |
        brew install lxc juju charmcraft;
      when: ansible_facts['os_family'] == "Darwin"
      async: 600
      poll: 5
      tags:
        - "multipass_infra"
        - "operator_e2e"
    - name: "Install lxc juju charmcraft - Ubuntu"
      shell: |
        sudo snap install lxd;
        sudo snap install charmcraft --classic;
        sudo snap install juju --classic;
      when: ansible_facts['os_family'] != "Darwin"
      async: 600
      poll: 5
      tags:
        - "multipass_infra"
        - "operator_e2e"
    - name: "Initialize lxd"
      shell: |
        sudo lxd init --auto;
      async: 600
      poll: 5
      register: multipass_infra_charm_lxd_init
      tags:
        - "multipass_infra"
        - "operator_e2e"
    - name: "install microk8s"
      shell: |
        sudo snap install microk8s --channel 1.25-strict/stable
      when: ansible_facts['os_family'] != "Darwin"
      async: 600
      poll: 5
      register: multipass_infra_install_microk8s
      tags:
        - "multipass_infra"
        - "operator_e2e"
    - name: "add ubuntu to snap_microk8s"
      shell: |
        sudo usermod -a -G snap_microk8s ubuntu;
      when: ansible_facts['os_family'] != "Darwin"
      async: 600
      poll: 5
      register: multipass_infra_add_ubuntu_to_snap_microk8s
      tags:
        - "multipass_infra"
        - "operator_e2e"
    - name: "Give the ubuntu user permissions to read the ~/.kube, and Jannah.global.ansible.working_dir"
      shell: |
        sudo chown -f -R ubuntu:ubuntu ~/.kube;
        exit 0;
      when: ansible_facts['os_family'] != "Darwin"
      async: 600
      poll: 5
      register: multipass_infra_chown_kube_and_working_dir
      tags:
        - "multipass_infra"
        - "operator_e2e"
    - name: "Create the 'microk8s' group"
      shell: |
        sudo newgrp snap_microk8s;
      when: ansible_facts['os_family'] != "Darwin"
      async: 600
      poll: 5
      register: multipass_infra_create_microk8s
      tags:
        - "multipass_infra"
        - "operator_e2e"
    - name: "Enable the necessary MicroK8s addons:"
      shell: |
        sudo microk8s enable hostpath-storage dns
      when: ansible_facts['os_family'] != "Darwin"
      async: 600
      poll: 5
      register: multipass_infra_enable_microK8s_addons
      tags:
        - "multipass_infra"
        - "operator_e2e"
    - name: "Set up a short alias for the Kubernetes CLI:"
      shell: |
        sudo snap alias microk8s.kubectl kubectl;
      when: ansible_facts['os_family'] != "Darwin"
      async: 600
      poll: 5
      register: multipass_infra_short_alias_kubernetes_cli
      tags:
        - "multipass_infra"
        - "operator_e2e"
    - name: "Since the juju package is strictly confined, you also need to manually create a path"
      shell: |
        sudo mkdir -vp /home/ubuntu/.local/share;
      when: ansible_facts['os_family'] != "Darwin"
      async: 600
      poll: 5
      register: multipass_infra_manually_create_path
      tags:
        - "multipass_infra"
        - "operator_e2e"
    - name: "juju clouds"
      shell: |
        juju clouds;
        exit 0;
      register: multipass_infra_juju_clouds
      tags:
        - "multipass_infra"
        - "operator_e2e"
    - name: "Create MOLECULE_EPHEMERAL_DIRECTORY"
      file:
        path: "$MOLECULE_EPHEMERAL_DIRECTORY"
        state: directory
        mode: 0755
      register: multipass_infra_create_ephemeral_dir
      tags:
        - "multipass_infra"
        - "operator_e2e"
#    - name: "lxc launch Jannah.stages.bootstrap.build.juju.containers.base.name "
#      shell: |
#        multipass exec {{ Jannah.stages.bootstrap.build.vm.name }} \
#        -- lxc launch ubuntu:22.04 {{ Jannah.stages.bootstrap.build.juju.containers.base.name }};
#      tags:
#        - "multipass_infra"
#        - "operator_e2e"
#    - name: "lxc stop Jannah.stages.bootstrap.build.juju.containers.base.name "
#      shell: |
#        multipass exec {{ Jannah.stages.bootstrap.build.vm.name }} \
#        -- lxc stop {{ Jannah.stages.bootstrap.build.juju.containers.base.name }};
#      tags:
#        - "multipass_infra"
#        - "operator_e2e"
#    - name: "lxc publish Jannah.stages.bootstrap.build.juju.containers.middleware.name"
#      shell: |
#        multipass exec {{ Jannah.stages.bootstrap.build.vm.name }} \
#        -- lxc publish {{ Jannah.stages.bootstrap.build.juju.containers.base.name }} \
#        --alias {{ Jannah.stages.bootstrap.build.juju.containers.middleware.name }};
#      tags:
#        - "multipass_infra"
#        - "operator_e2e"
#    - name: "publish Jannah.stages.bootstrap.build.juju.containers.frontend.name"
#      shell: |
#        multipass exec {{ Jannah.stages.bootstrap.build.vm.name }} \
#        -- lxc launch ubuntu:22.04 {{ Jannah.stages.bootstrap.build.juju.containers.frontend.name }};
#        multipass exec {{ Jannah.stages.bootstrap.build.vm.name }} \
#        -- lxc stop {{ Jannah.stages.bootstrap.build.juju.containers.frontend.name }};
#        multipass exec {{ Jannah.stages.bootstrap.build.vm.name }} \
#        -- lxc publish {{ Jannah.stages.bootstrap.build.juju.containers.frontend.name }} \
#        --alias {{ Jannah.stages.bootstrap.build.juju.containers.frontend.name }};
#      tags:
#        - "multipass_infra"
#        - "operator_e2e"
#    - name: "Install juju controller into microk8s cloud"
#      shell: |
#        multipass exec {{ Jannah.stages.bootstrap.build.vm.name }} \
#        -- juju bootstrap --show-log=true --verbose=true microk8s \
#        {{ Jannah.stages.bootstrap.build.juju.controller.name }};
##      async: 60
##      poll: 3
#      register: multipass_infra_install_juju_controller_into_microk8s_cloud
#      tags:
#        - "multipass_infra"
#        - "operator_e2e"
#    - debug: var=multipass_infra_install_juju_controller_into_microk8s_cloud
#      tags:
#        - "multipass_infra"
#        - "operator_e2e"
#    - name: "Create a workspace/model, on the controller"
#      shell: |
#        multipass exec {{ Jannah.stages.bootstrap.build.vm.name }} \
#        -- juju add-model {{ Jannah.stages.bootstrap.build.juju.model.name }};
##      async: 60
##      poll: 3
#      register: multipass_infra_create_a_workspace_model_on_the_controller
#      tags:
#        - "multipass_infra"
#        - "operator_e2e"
#    - debug: var=multipass_infra_create_a_workspace_model_on_the_controller
#      tags:
#        - "multipass_infra"
#        - "operator_e2e"
#
#    - name: "Deploy operator"
#      shell: |
#        multipass exec {{ Jannah.stages.bootstrap.build.vm.name }} \
#        -- juju add-model {{ Jannah.stages.bootstrap.build.juju.model.name }};
#      #      async: 60
#      #      poll: 3
#      register: multipass_infra_create_a_workspace_model_on_the_controller
#      tags:
#        - "multipass_infra"
#        - "operator_e2e"
#    - debug: var=multipass_infra_create_a_workspace_model_on_the_controller
#      tags:
#        - "multipass_infra"
#        - "operator_e2e"

  rescue:
    - name: "Multipass Infra Exception"
      ansible.builtin.debug:
        msg: 'Multipass Infra Exception'
      register: multipass_infra_debug_resources
    - debug: var=multipass_infra_debug_resources
      tags:
        - "multipass_infra"
        - "operator_e2e"
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
  ignore_errors: false
