---
- name: "Cleanup artifacts from MacOs Docker Desktop"
  block:
    - name: "Kubeflow uninstall"
      shell: |
        kubectl delete all --all -n kubeflow;
        exit 0;
      tags:
        - "docker_desktop_infra"
        - "molecule_prepare"
        - "operator_e2e"
#    - name: "knative-eventing uninstall"
#      shell: |
#        kubectl delete all --all -n knative-eventing;
#        exit 0;
#      tags:
#        - "docker_desktop_infra"
#        - "molecule_prepare"
#        - "operator_e2e"
#    - name: "cert-manager uninstall"
#      shell: |
#        kubectl delete all --all -n cert-manager;
#        exit 0;
#      tags:
#        - "docker_desktop_infra"
#        - "molecule_prepare"
#        - "operator_e2e"
#    - name: "istio-system uninstall"
#      shell: |
#        kubectl delete all --all -n istio-system
#      tags:
#        - "docker_desktop_infra"
#        - "molecule_prepare"
#        - "operator_e2e"
#    - name: "auth uninstall"
#      shell: |
#        kubectl delete all --all -n auth;
#        exit 0;
#      tags:
#        - "docker_desktop_infra"
#        - "molecule_prepare"
#        - "operator_e2e"
    - name: "Remove install_kustomize download directory"
      file:
        path: "${MOLECULE_EPHEMERAL_DIRECTORY}/install_kustomize"
        state: absent
      tags:
        - "docker_desktop_infra"
        - "molecule_cleanup"
        - "operator_e2e"
    - name: "unalias kustomize "
      shell: |
        unalias kustomize;
        exit 0;
      tags:
        - "docker_desktop_infra"
        - "molecule_cleanup"
        - "operator_e2e"
    - name: "Remove kubeflow download directory"
      file:
        path: "${MOLECULE_EPHEMERAL_DIRECTORY}/kubeflow/manifests"
        state: absent
      tags:
        - "docker_desktop_infra"
        - "molecule_cleanup"
        - "operator_e2e"
  rescue:
    - name: "Clean Prepared Operator MacOs Docker Desktop Exception"
      ansible.builtin.debug:
        msg: 'Clean Prepared Operator MacOs Docker Desktop Exception'
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "multipass_infra"
        - "molecule_cleanup"
        - "operator_e2e"
  ignore_errors: false
