---
volumes:
  - name: certs
    secret:
      secretName: dex-certs
volumeMounts:
  - name: certs
    readOnly: true
    mountPath: /certs
https:
  enabled: true
service:
  type: NodePort
  ports:
    https:
      nodePort: 31000

# Dex configuration
config:
  issuer: https://{{ ansible_facts['all_ipv4_addresses'][1] }}:31000/dex
  storage:
    type: memory
  web:
    https: 0.0.0.0:5554
    tlsCert: /certs/tls.crt
    tlsKey: /certs/tls.key
  staticClients:
    - name: Kubernetes
      id: kubernetes
      secret: super-safe-client-secret
      redirectURIs:
        - http://localhost:8000  # for kubelogin
  enablePasswordDB: true
  staticPasswords:
    - email: "admin@example.com"
      # bcrypt hash of the string "password": $(echo password | htpasswd -BinC 10 admin | cut -d: -f2)
      hash: "$2y$10$crvReP80rTwzeggTwOfs5eZ1sHqqbQKRbsZVSmGXwT6Z973oPP7GK"
      username: "admin"
      userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"