- name: "Remove Kind infra"
  block:
    - name: "kind delete cluster"
      environment:
        KUBECONFIG: "${MOLECULE_EPHEMERAL_DIRECTORY}/kind/config"
        PIPELINE_VERSION: "1.8.5"
      shell: |
        kubectl delete -k "github.com/kubeflow/pipelines/manifests/kustomize/env/platform-agnostic-pns?ref=$PIPELINE_VERSION";
        kubectl delete -k "github.com/kubeflow/pipelines/manifests/kustomize/cluster-scoped-resources?ref=$PIPELINE_VERSION";
        exit 0;
      tags:
        - "kind_infra"
        - "molecule_cleanup"
        - "operator_e2e"
        - "dev_debug"

    - name: "kind delete cluster"
      shell: |
        kind delete cluster --name "{{ Jannah.stages.bootstrap.build.vm.name }}-kind" 
        exit 0;
      tags:
        - "kind_infra"
        - "molecule_cleanup"
        - "operator_e2e"
        - "dev_debug"

    - name: "Remove MOLECULE_EPHEMERAL_DIRECTORY/kind directory"
      file:
        path: "${MOLECULE_EPHEMERAL_DIRECTORY}/kind"
        state: absent
      tags:
        - "kind_infra"
        - "molecule_cleanup"
        - "operator_e2e"
        - "dev_debug"
        -