---
# Implements
# https://docs.percona.com/percona-operator-for-postgresql/2.0/kubectl.html#procedure
- name: "Deploy Storage Operator to MacOs Docker Desktop"
  block:
    - name: "set_fact tmp_EPHEMERAL_cr_jannah_stages_bootstrap_deploy_wait_time"
      ansible.builtin.set_fact:
        tmp_EPHEMERAL_cr_jannah_stages_bootstrap_deploy_wait_time: "{{ Jannah.stages.bootstrap.deploy.wait_time }}"
      tags:
        - "molecule_create"
        - "operator_e2e"
        - "molecule_create_debug"
    # - name: "Create tmp/EPHEMERAL/cr directory - docker-desktop"
    #   file:
    #     path: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/percona-postgresql-operator"
    #     state: directory
    #     mode: 0755
    #   tags:
    #     - "molecule_create"
    #     - "operator_e2e"
    #     - "molecule_create_debug"
    # - name: "Git checkout repository"
    #   ansible.builtin.git:
    #     repo: "https://github.com/percona/percona-postgresql-operator" 
    #     dest: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/percona-postgresql-operator"
    #     version: "v2.2.0"
    #     force: yes 
    #   tags:
    #     - "molecule_create"
    #     - "operator_e2e"
    #     - "molecule_create_debug"
    # - name: "Generate update postgres for with custom user and database - docker-desktop"
    #   template:
    #     src: "files/templates/helm/percona/deploy/cr.yaml"
    #     dest: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/percona-postgresql-operator/deploy/cr.yaml"
    #   tags:
    #     - "molecule_create"
    #     - "operator_e2e"
    #     - "molecule_create_debug"
    # - name: "helm repo add percona https://percona.github.io/percona-helm-charts - docker-desktop"
    #   shell: |
    #     helm repo add percona https://percona.github.io/percona-helm-charts;
    #     helm repo update;
    #   tags:
    #     - "molecule_create"
    #     - "operator_e2e"
    #     - "molecule_create_debug"
    # - name: "helm install jannah-parcona-operator percona/pg-operator - docker-desktop"
    #   shell: |
    #     helm install jannah-parcona-operator percona/pg-operator \
    #     --namespace \
    #     "{{ Jannah.stages.bootstrap.deploy.dependencies.parcona_postgres.namespace }}";
    #   tags:
    #     - "molecule_create"
    #     - "operator_e2e"
    #     - "molecule_create_debug"
    # - name: "helm repo add percona https://percona.github.io/percona-helm-charts - docker-desktop"
    #   shell: |
    #     helm install jannahdb-cluster percona/pg-db  \
    #     --namespace \
    #     "{{ Jannah.stages.bootstrap.deploy.dependencies.parcona_postgres.namespace }}";
    #   tags:
    #     - "molecule_create"
    #     - "operator_e2e"
    #     - "molecule_create_debug"
    - name: "Deploy Percona Postgresql Operator CRD - docker-desktop"
      shell: |
        kubectl apply --server-side -f \
        {{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/percona-postgresql-operator/deploy/crd.yaml \
        -n "{{ Jannah.stages.bootstrap.deploy.dependencies.parcona_postgres.namespace }}";
      tags:
        - "molecule_create"
        - "operator_e2e"
        - "molecule_create_debug"
    - name: "Deploy Percona Distribution for PostgreSQL cluster rbac - docker-desktop"
      shell: |
        kubectl apply -f \
        {{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/percona-postgresql-operator/deploy/rbac.yaml \
        -n "{{ Jannah.stages.bootstrap.deploy.dependencies.parcona_postgres.namespace }}";
      tags:
        - "molecule_create"
        - "operator_e2e"
        - "molecule_create_debug"   
    - name: "Deploy Percona Distribution for PostgreSQL operator - docker-desktop"
      shell: |
        kubectl apply -f \
        {{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/percona-postgresql-operator/deploy/operator.yaml \
        -n "{{ Jannah.stages.bootstrap.deploy.dependencies.parcona_postgres.namespace }}";
      tags:
        - "molecule_create"
        - "operator_e2e"
        - "molecule_create_debug"
    - name: "Deploy Percona Postgresql Operator CR - docker-desktop - wait for crd/perconapgclusters.pgv2.percona.com"
      shell: |
        kubectl wait --for=condition=Established=True --timeout=60s crd/perconapgclusters.pgv2.percona.com;
      tags:
        - "molecule_create"
        - "operator_e2e"
        - "molecule_create_debug"
    - name: "Wait for Deploy Percona Distribution for PostgreSQL cluster - docker-desktop"
      shell: |
        sleep "{{ Jannah.stages.bootstrap.deploy.wait_time }}";
      when: tmp_EPHEMERAL_cr_jannah_stages_bootstrap_deploy_wait_time | int != 0
      tags:
        - "molecule_create"
        - "operator_e2e"
        - "molecule_create_debug"   
    - name: "Apply update postgres for with custom user and database - docker-desktop"
      shell: |
        kubectl apply -f \
        {{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/percona-postgresql-operator/deploy/cr.yaml \
        -n "{{ Jannah.stages.bootstrap.deploy.dependencies.parcona_postgres.namespace }}";
      tags:
        - "molecule_create"
        - "operator_e2e"
        - "molecule_create_debug" 
  rescue:
    - name: "Deploy Operators Storage to MacOs Docker Desktop Exception"
      ansible.builtin.debug:
        msg: 'Deploy Operators Storage to MacOs Docker Desktop Exception'
      tags:
        - "deploy_storage"
        - "molecule_create"
        - "operator_e2e"
        - "molecule_create_debug"
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "deploy_storage"
        - "molecule_create"
        - "operator_e2e"
        - "molecule_create_debug"
  ignore_errors: false
