---
# Implements
# https://docs.percona.com/percona-operator-for-postgresql/2.0/kubectl.html#procedure
- name: "Deploy Storage Operator to MacOs Docker Desktop"
  block:
    - name: "Deploy Percona Postgresql Operator - docker-desktop"
      shell: |
        kubectl apply --server-side -f \
        https://raw.githubusercontent.com/percona/percona-postgresql-operator/v2.2.0/deploy/bundle.yaml \
        -n "{{ Jannah.stages.bootstrap.deploy.dependencies.parcona_postgres.namespace }}";
      tags:
        - "molecule_create"
        - "operator_e2e"
        - "molecule_create_debug"
    - name: "Deploy Percona Distribution for PostgreSQL cluster - docker-desktop"
      shell: |
        kubectl apply -f https://raw.githubusercontent.com/percona/percona-postgresql-operator/v2.2.0/deploy/cr.yaml \
        -n "{{ Jannah.stages.bootstrap.deploy.dependencies.parcona_postgres.namespace }}";
      tags:
        - "molecule_create"
        - "operator_e2e"
        - "molecule_create_debug"
    - name: "Deploy Percona Postgresql Operator CR - docker-desktop - wait for crd/perconapgclusters.pgv2.percona.com"
      shell: |
        kubectl wait --for=condition=Established=True --timeout=60s crd/perconapgclusters.pgv2.percona.com;
      tags:
        - "molecule_create"
        - "operator_e2e"
        - "molecule_create_debug"
    - name: "Get pgbouncer-uri - docker-desktop"
      shell: |
        kubectl get secret cluster1-pguser-cluster1 -n "{{ Jannah.stages.bootstrap.deploy.helm_values.common.namespace }}" \
        --template='{{ '{{' }}index .data "pgbouncer-uri" | base64decode {{ '}}' }}';
      # To be used downstream as environment variable in the middleware
      register: cluster1_pguser_cluster1_pgbouncer_uri
      tags:
        - "molecule_create"
        - "operator_e2e"
        - "molecule_create_debug"
    - name: 'Create pgbouncer_uri secret'
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            namespace: "{{ Jannah.stages.bootstrap.deploy.helm_values.common.namespace }}"
            name: "{{ Jannah.stages.bootstrap.secrets.percona_db.name }}"
          stringData:
            pgbouncer-uri: "{{ cluster1_pguser_cluster1_pgbouncer_uri['stdout_lines'][0]  }}"
      tags:
        - "pepare_images"
        - "molecule_prepare"
        - "operator_e2e"
        - "molecule_create_debug" 
  rescue:
    - name: "Deploy Operators Storage to MacOs Docker Desktop Exception"
      ansible.builtin.debug:
        msg: 'Deploy Operators Storage to MacOs Docker Desktop Exception'
      tags:
        - "deploy_storage"
        - "molecule_create"
        - "operator_e2e"
        - "molecule_create_debug"
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "deploy_storage"
        - "molecule_create"
        - "operator_e2e"
        - "molecule_create_debug"
  ignore_errors: false
