---
# Implements
# https://docs.percona.com/percona-operator-for-postgresql/2.0/kubectl.html#procedure
- name: "Deploy Operators Storage to MacOs Docker Desktop"
  block:
    - name: "set_fact jannah_stages_bootstrap_deploy_type"
      ansible.builtin.set_fact:
        jannah_stages_bootstrap_deploy_type: "{{ Jannah.stages.bootstrap.deploy.type }}"
      tags:
        - "deploy_storage"
        - "molecule_converge"
        - "operator_e2e"
        - "debug_task"
    - name: "set_fact jannah_stages_bootstrap_deploy_destination"
      ansible.builtin.set_fact:
        jannah_stages_bootstrap_deploy_destination: "{{ Jannah.stages.bootstrap.deploy.destination }}"
      tags:
        - "deploy_storage"
        - "molecule_converge"
        - "operator_e2e"
        - "debug_task"
    - name: 'Create Storage (Parcona Postgres) Namespace'
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ Jannah.stages.bootstrap.deploy.dependencies.parcona_postgres.namespace }}"
      tags:
        - "deploy_storage"
        - "molecule_converge"
        - "operator_e2e"
        - "debug_task"
    - name: "Deploy Percona Postgresql Operator"
      shell: |
        kubectl apply --server-side -f \
        https://raw.githubusercontent.com/percona/percona-postgresql-operator/v2.2.0/deploy/bundle.yaml \
        -n "{{ Jannah.stages.bootstrap.deploy.dependencies.parcona_postgres.namespace }}";
      tags:
        - "docker_desktop_infra"
        - "molecule_converge"
        - "operator_e2e"
        - "debug_task"
    - name: "Deploy Percona Distribution for PostgreSQL cluster"
      shell: |
        sleep 10;
        kubectl apply -f https://raw.githubusercontent.com/percona/percona-postgresql-operator/v2.2.0/deploy/cr.yaml \
        -n "{{ Jannah.stages.bootstrap.deploy.dependencies.parcona_postgres.namespace }}";
      tags:
        - "docker_desktop_infra"
        - "molecule_converge"
        - "operator_e2e"
        - "debug_task"
    - name: "Check the Operator and replica set Pods status"
      shell: |
        sleep 10;
        kubectl get pg -n postgres-operator;
      tags:
        - "docker_desktop_infra"
        - "molecule_converge"
        - "operator_e2e"
        - "debug_task"
  rescue:
    - name: "Deploy Operators Storage to MacOs Docker Desktop Exception"
      ansible.builtin.debug:
        msg: 'Deploy Operators Storage to MacOs Docker Desktop Exception'
      tags:
        - "deploy_storage"
        - "molecule_converge"
        - "operator_e2e"
        - "debug_task"
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "deploy_storage"
        - "molecule_converge"
        - "operator_e2e"
        - "debug_task"
  ignore_errors: false
