---
- name: "Deploy Operator to MacOs Docker  Kind Cluster"
  block:
    - name: "set_fact jannah_stages_bootstrap_deploy_type"
      ansible.builtin.set_fact:
        jannah_stages_bootstrap_deploy_type: "{{ Jannah.stages.bootstrap.deploy.type }}"
      tags:
        - "deploy_images"
        - "molecule_converge"
        - "operator_e2e"
    - name: "set_fact jannah_stages_bootstrap_deploy_os"
      ansible.builtin.set_fact:
        jannah_stages_bootstrap_deploy_os: "{{ Jannah.stages.bootstrap.deploy.os }}"
      tags:
        - "deploy_images"
        - "molecule_converge"
        - "operator_e2e"
    - name: "set_fact jannah_stages_bootstrap_deploy_mode"
      ansible.builtin.set_fact:
        jannah_stages_bootstrap_deploy_mode: "{{ Jannah.stages.bootstrap.deploy.mode }}"
      tags:
        - "deploy_images"
        - "molecule_converge"
        - "operator_e2e"
    - name: "Kubeflow install (standalone deployment) kind cluster scoped-resources"
      environment:
        - PIPELINE_VERSION: "2.0.1"
        - KUBECONFIG: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/kind/config"
      shell: |
        kubectl apply -k \
        "github.com/kubeflow/pipelines/manifests/kustomize/cluster-scoped-resources?ref=$PIPELINE_VERSION";
      when: (
              jannah_stages_bootstrap_deploy_type == "standalone"
              or
              jannah_stages_bootstrap_deploy_type == "local"
          )
      args:
        chdir: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/kind/"
      tags:
        - "docker_desktop_infra"
        - "molecule_converge"
        - "operator_e2e"
    - name: "Kubeflow install (standalone deployment) kind cluster - wait for crd/applications.app.k8s.io"
      environment:
        - PIPELINE_VERSION: "2.0.1"
        - KUBECONFIG: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/kind/config"
      shell: |
        kubectl wait --for condition=established --timeout=60s crd/applications.app.k8s.io;
        exit 0;
      when: (
              jannah_stages_bootstrap_deploy_type == "standalone"
              or
              jannah_stages_bootstrap_deploy_type == "local"
        )
      args:
        chdir: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/kind/"
      tags:
        - "docker_desktop_infra"
        - "molecule_converge"
        - "operator_e2e"
    - name: "Kubeflow install (standalone deployment) - kind - dev?ref"
      environment:
        - PIPELINE_VERSION: "2.0.1"
        - KUBECONFIG: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/kind/config"
      shell: |
        kubectl apply -k "github.com/kubeflow/pipelines/manifests/kustomize/env/dev?ref=$PIPELINE_VERSION";
      when: jannah_stages_bootstrap_deploy_type == "standalone"
      args:
        chdir: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/kind/"
      tags:
        - "docker_desktop_infra"
        - "molecule_converge"
        - "operator_e2e"
    - name: "Kubeflow install (local deployment) - kind - platform-agnostic-pns"
      environment:
        - PIPELINE_VERSION: "2.0.1"
        - KUBECONFIG: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/kind/config"
      shell: |
        kubectl apply -k "github.com/kubeflow/pipelines/manifests/kustomize/env/platform-agnostic-pns?ref=$PIPELINE_VERSION"
      args:
        chdir: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/kind/"
      when: jannah_stages_bootstrap_deploy_type == "local"
      tags:
        - "docker_desktop_infra"
        - "molecule_converge"
        - "operator_e2e"
    - name: "Create kubeflow download directory"
      file:
        path: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/kubeflow/manifests"
        state: directory
        mode: 0755
      when: jannah_stages_bootstrap_deploy_type == "full"
      tags:
        - "docker_desktop_infra"
        - "molecule_converge"
        - "operator_e2e"
    - name: "Read-write git checkout kubeflow/manifests.git"
      ansible.builtin.git:
        repo: "https://github.com/kubeflow/manifests.git"
        dest: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/kubeflow/manifests"
      when: jannah_stages_bootstrap_deploy_type == "full"
      tags:
        - "docker_desktop_infra"
        - "molecule_converge"
        - "operator_e2e"
    - name: "set_fact kubeconfig_path"
      ansible.builtin.set_fact:
        kubeconfig_path: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/kind/config"
      tags:
        - "deploy_images"
        - "molecule_converge"
        - "operator_e2e"
    # - name: "kind export kubeconfig to /kubeflow/config - Darwin(amd64)"
    #   shell: |
    #     KUBECONFIG=config kind export kubeconfig --name {{ Jannah.stages.bootstrap.deploy.kind.name }}
    #   when: jannah_stages_bootstrap_deploy_type == "full"
    #   args:
    #     chdir: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/kubeflow/"
    #   async: 600
    #   poll: 5
    #   tags:
    #     - "molecule_converge"
    #     - "operator_e2e"
    - name: "Kubeflow install (full deployment to kind cluster)"
      environment:
        - PIPELINE_VERSION: "2.0.1"
        - KUBECONFIG: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/kind/config"
      shell: |
        while ! {{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/install_kustomize/kustomize build example | awk '!/well-defined/' | kubectl apply -f -; do echo "Retrying to apply resources"; sleep 10; done;
      when: jannah_stages_bootstrap_deploy_type == "full" 
      args:
        chdir: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/kubeflow/manifests"
      tags:
        - "docker_desktop_infra"
        - "molecule_converge"
        - "operator_e2e"
    - name: "Generate Helm values file off off the molecule configuration file - amd64/ubuntu"
      template:
        src: "files/templates/helm/amd64/ubuntu/values.yml"
        dest: "{{ Jannah.global.ansible.working_dir }}/jannah-operator/values.yaml"
      when: ansible_facts['architecture'] == "x86_64" and jannah_stages_bootstrap_deploy_os == "ubuntu" 
      tags:
        - "docker_desktop_infra"
        - "molecule_converge"
        - "operator_e2e" 
    - name: "Generate Helm values file off off the molecule configuration file - amd64/streamos"
      template:
        src: "files/templates/helm/amd64/streamos/values.yml"
        dest: "{{ Jannah.global.ansible.working_dir }}/jannah-operator/values.yaml"
      when: ansible_facts['architecture'] == "x86_64" and jannah_stages_bootstrap_deploy_os == "streamos" 
      tags:
        - "docker_desktop_infra"
        - "molecule_converge"
        - "operator_e2e"  
    - name: "Generate Helm values file off off the molecule configuration file - arm64/ubuntu"
      template:
        src: "files/templates/helm/arm64/ubuntu/values.yml"
        dest: "{{ Jannah.global.ansible.working_dir }}/jannah-operator/values.yaml"
      when: ansible_facts['architecture'] != "x86_64" and jannah_stages_bootstrap_deploy_os == "ubuntu" 
      tags:
        - "docker_desktop_infra"
        - "molecule_converge"
        - "operator_e2e" 
    - name: "Generate Helm values file off off the molecule configuration file - arm64/streamos"
      template:
        src: "files/templates/helm/arm64/streamos/values.yml"
        dest: "{{ Jannah.global.ansible.working_dir }}/jannah-operator/values.yaml"
      when: ansible_facts['architecture'] != "x86_64" and jannah_stages_bootstrap_deploy_os == "streamos" 
      tags:
        - "docker_desktop_infra"
        - "molecule_converge"
        - "operator_e2e" 
    - name: "deploy-to-kind-cluster-full-ubuntu-dev-mode"
      environment:
        - KUBECONFIG: "{{ Jannah.global.ansible.working_dir }}/tmp/EPHEMERAL/kind/config"
      shell: |
        helm install \
        -n {{ Jannah.stages.bootstrap.deploy.helm_values.common.namespace }} \
        --create-namespace  --generate-name \
        {{ Jannah.global.ansible.working_dir }}/jannah-operator;
      args:
        chdir: "{{ Jannah.global.ansible.working_dir }}"
      tags:
        - "docker_desktop_infra"
        - "molecule_converge"
        - "operator_e2e"
  rescue:
    - name: "Inline Prepare Operator MacOs Docker Desktop Exception"
      ansible.builtin.debug:
        msg: 'Inline Prepare Operator MacOs Docker Desktop Exception'
      tags:
        - "deploy_images"
        - "molecule_converge"
        - "operator_e2e"
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "deploy_images"
        - "molecule_converge"
        - "operator_e2e"
  ignore_errors: false
