---
- name: "Converge Jannah Tasks"
  block:
    - name: "Import converge  docker desktop tasks - Darwin"
      include_tasks: '{{ converge_deploy_to_macos_docker_desktop_task_items }}'
      with_fileglob:
        - deploy_to_macos_docker_desktop.yml
      loop_control:
        loop_var: converge_deploy_to_macos_docker_desktop_task_items
      when: ansible_facts['os_family'] == "Darwin"
      tags:
        - "docker_desktop_infra"
        - "molecule_converge"
        - "operator_e2e"
        - "standalone_implementation"
    - name: "Import tasks to deploy build to streamos nodes - StreamOS"
      include_tasks: '{{ converge_deploy_to_streamos_nodes_task_items }}'
      with_fileglob:
        - deploy_to_streamos_nodes.yml
      loop_control:
        loop_var: converge_deploy_to_streamos_nodes_task_items
      when: ansible_facts['os_family'] != "Darwin" and ansible_facts['os_family'] != "Debian"
      tags:
        - "docker_desktop_infra"
        - "molecule_converge"
        - "operator_e2e"
    - name: "Import tasks to deploy builds to ubuntu nodes"
      include_tasks: '{{ converge_deploy_to_ubuntu_nodes_task_items }}'
      with_fileglob:
        - deploy_to_ubuntu_nodes.yml
      loop_control:
        loop_var: converge_deploy_to_ubuntu_nodes_task_items
      when: ansible_facts['os_family'] == "Debian"
      tags:
        - "docker_desktop_infra"
        - "molecule_converge"
        - "operator_e2e"
  rescue:
    - name: "Deploy Jannah Tasks Exception"
      ansible.builtin.debug:
        msg: 'Deploy Jannah Tasks Exception'
      register: deploy_jannah_tasks_debug_resources
    - debug: var=deploy_jannah_tasks_debug_resources
      tags:
        - "deploy_jannah"
        - "operator_e2e"
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
  ignore_errors: false
