---
- name: "Converge (Deploy) Jannah Tasks"
  block:
    - name: "set_fact jannah_stages_bootstrap_deploy_destination"
      ansible.builtin.set_fact:
        jannah_stages_bootstrap_deploy_destination: "{{ Jannah.stages.bootstrap.deploy.destination }}"
      tags:
        - "deploy_images"
        - "molecule_converge"
        - "operator_e2e"
        - "molecule_converge_debug"
    - name: "Import converge  docker desktop tasks - Darwin"
      include_tasks: '{{ converge_deploy_to_macos_docker_desktop_task_items }}'
      with_fileglob:
        - deploy_to_macos_docker_desktop.yml
      loop_control:
        loop_var: converge_deploy_to_macos_docker_desktop_task_items
      when: ansible_facts['os_family'] == "Darwin" and (
                                                        jannah_stages_bootstrap_deploy_destination == "docker-desktop"
                                                        )
      tags:
        - "deploy_images"
        - "molecule_converge"
        - "operator_e2e"
        - "molecule_converge_debug"
    - name: "Import converge kind cluster tasks - Darwin"
      include_tasks: '{{ converge_deploy_to_kind_cluster_task_items }}'
      with_fileglob:
        - deploy_to_kind_cluster.yml
      loop_control:
        loop_var: converge_deploy_to_kind_cluster_task_items
      when: ansible_facts['os_family'] == "Darwin" and (
                                                        jannah_stages_bootstrap_deploy_destination == "kind"
                                                        )
      tags:
        - "deploy_images"
        - "molecule_converge"
        - "operator_e2e"
        - "molecule_converge_debug"
  rescue:
    - name: "Deploy Jannah Tasks Exception"
      ansible.builtin.debug:
        msg: 'Deploy Jannah Tasks Exception'
      register: deploy_jannah_tasks_debug_resources
      tags:
        - "deploy_images"
        - "molecule_converge"
        - "operator_e2e"
        - "molecule_converge_debug"
    - debug: var=deploy_jannah_tasks_debug_resources
      tags:
        - "deploy_images"
        - "molecule_converge"
        - "operator_e2e"
        - "molecule_converge_debug"
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
      tags:
        - "deploy_images"
        - "molecule_converge"
        - "operator_e2e"
        - "molecule_converge_debug"
  ignore_errors: false
