---
- name: "Kubernetes/Charmcraft tooling - Inline"
  block:
    # Note: Ubuntu already comes with LXC.
    - name: "Initialize lxd"
      shell: |
        lxd init --auto;
      when: ansible_facts['os_family'] == "Ubuntu"
      async: 600
      poll: 5
      tags:
        - "multipass_infra"
        - "molecule_create"
        - "operator_e2e"
    - name: "install charmcraft - Inline/Ubuntu"
      shell: |
        sudo snap install charmcraft --classic;
      when: ansible_facts['os_family'] == "Ubuntu"
      async: 600
      poll: 5
      tags:
        - "multipass_infra"
        - "molecule_create"
        - "operator_e2e"
    - name: "install microk8s  - Inline/Ubuntu"
      shell: |
        sudo snap install microk8s --channel 1.25-strict/stable;
      when: ansible_facts['os_family'] == "Ubuntu"
      async: 1200
      poll: 5
      tags:
        - "multipass_infra"
        - "molecule_create"
        - "operator_e2e"
    - name: "add ubuntu to snap_microk8s  - Inline/Ubuntu"
      shell: |
        sudo usermod -a -G snap_microk8s ubuntu;
      when: ansible_facts['os_family'] == "Ubuntu"
      async: 600
      poll: 5
      tags:
        - "multipass_infra"
        - "molecule_create"
        - "operator_e2e"
    - name: "Give the ubuntu user permissions to read the ~/.kube  - Inline/Ubuntu"
      shell: |  
        sudo chown -f -R ubuntu ~/.kube;
        exit 0;
      when: ansible_facts['os_family'] == "Ubuntu"
      async: 600
      poll: 5
      tags:
        - "multipass_infra"
        - "molecule_create"
        - "operator_e2e"
    - name: "change to the 'microk8s' group  - Inline/Ubuntu"
      shell: |
        newgrp snap_microk8s;
      when: ansible_facts['os_family'] == "Ubuntu"
      async: 600
      poll: 5
      tags:
        - "multipass_infra"
        - "molecule_create"
        - "operator_e2e"
    - name: "Enable the necessary MicroK8s addons:  - Inline/Ubuntu"
      shell: |
        sudo microk8s enable hostpath-storage dns;
        sleep 10;
      when: ansible_facts['os_family'] == "Ubuntu"
      async: 1200
      poll: 15
      tags:
        - "multipass_infra"
        - "molecule_create"
        - "operator_e2e"
    - name: "Set up a short alias for the Kubernetes CLI:  - Inline/Ubuntu"
      shell: |
        sudo snap alias microk8s.kubectl kubectl;
      when: ansible_facts['os_family'] == "Ubuntu"
      async: 600
      poll: 5
      tags:
        - "multipass_infra"
        - "molecule_create"
        - "operator_e2e"
  rescue:
    - name: "Kubernetes/Charmcraft Tooling Exception"
      ansible.builtin.debug:
        msg: 'Kubernetes/Charmcraft Tooling Exception'
      register: molecule_create_inline_debug_resources
    - name: Re-emit failure
      vars:
        failed_task:
          result: '{{ ansible_failed_result }}'
      fail:
        msg: '{{ failed_task }}'
  ignore_errors: false
